[ja_JP] Translate "identity.md" into Japanese
hyperledger/fabric-docs-i18n pull request #131
Opened 2020-09-03 03:42 UTC by siburu

Fix https://github.com/hyperledger/fabric-docs-i18n/issues/101

Signed-off-by: YOSHIDA Masanori <masanori.yoshida@gmail.com>

2020-09-03 23:41 UTC, shimos requested changes
PRありがとうございます。細かいところですが、いくつかコメントをしました。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +これらの各アクター(サービスを消費できるネットワークの内部または外部のアクティブな要素)は、X.509デジタル証明書にカプセル化されたデジタルIDを持っています。
"identity" は他の訳と合わせて、"アイデンティティ"と訳したほうがよいと思います。 cf. https://github.com/hyperledger/fabric-docs-i18n/pull/77#discussion_r469004190
なお、以下の出現例ではコメントを省略します。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +さらにデジタルIDには、Fabricがアクセス権を決定するために使用するいくつかの追加属性があり、IDとそれに関連付けられた属性の組み合わせに特別な名前(**プリンシパル**)を与えます。
```suggestion
さらにデジタルIDには、Fabricがアクセス権を決定するために使用するいくつかの追加属性があり、IDとそれに関連付けられた属性の組み合わせに特別な名前(**プリンシパル**)が与えられています。
```

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +プリンシパルとは、アクセス権を決定するプロパティです。
```suggestion
このドキュメントでは、プリンシパルとは、アクセス権を決定するプロパティのことを指します。
```
"When we talk about principals," を敢えて訳す必要もないかもしれませんが、「この文章(トピック or ドキュメント?)では」をつけたほうが、原文のニュアンスに近いでしょうか。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +*有効なクレジットカードを持っているだけでは十分ではなく、お店にも受け入れてもらわないといけません！
専門用語ではないのであまり重要ではないのですが、storeが以下の文章で「お店」「店舗」「ストア」と訳されているようですので、どれかに統一した方がよいかもしれないです。（ストアは、別のテクニカルタームを指してると思われるかもしれないので、それ以外がいいでしょうか）

これも以下ではコメントを省略します。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +一方、MSPは、店舗が受け入れるカード・プロバイダーのリストのようなものであり、どのIDが店舗支払いネットワークの信頼できるメンバー(アクター)であるかを決定します。
```suggestion
一方、MSPは、店舗が受け入れるカード・プロバイダーのリストのようなものであり、どのIDが店舗支払いネットワークの信頼できるメンバー(アクター)であるかを決定するのに相当します。
```
"determining..."がどこにかかってるかが微妙ですが、内容的には、"the list of card providers" (likeの延長) だと思われます。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +**S**を**HTTPS**に加えるのがPKIです。
```suggestion
**HTTPS**を**S**たらしめているのがPKIです。
```
上記はあまりいい訳が思い浮かばなかったのでご参考ですが、元の翻訳だと、HTTPSにさらにSを加えているように読めてしまうかと思います。もしくは、原文を離れてもっと意味を分かりやすく訳してもよいかと思います。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +たとえば、ミシガン州デトロイト市のMitchell Carsの製造部門のメアリーモリスが、`SUBJECT`属性が`C=US`、`ST=Michigan`、`L=Detroit`、`O=Mitchell Cars`、`OU=Manufacturing`、`CN=Mary Morris /UID=123456`のデジタル証明書を持っているとします。
```suggestion
たとえば、ミシガン州デトロイト市のMitchell Carsの製造部門のメアリー・モリス(Mary Morris)が、`SUBJECT`属性が`C=US`、`ST=Michigan`、`L=Detroit`、`O=Mitchell Cars`、`OU=Manufacturing`、`CN=Mary Morris /UID=123456`のデジタル証明書を持っているとします。
```
後続のCNでアルファベット表記がでてくるので、併記したほうが親切かもしれません。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +Maryは証明書の`SUBJECT`であり、強調表示された`SUBJECT`のテキストは、Maryに関する重要な事実を示します。
```suggestion
メアリーは証明書の`SUBJECT`であり、強調表示された`SUBJECT`のテキストは、メアリーに関する重要な事実を示します。
```
上記でメアリーと訳しているので、それに統一した方がよいでしょう。なお、これも以下の文章についてはコメントを省略します。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +重要なのは、Maryのすべての属性が、暗号技術(文字通り「*秘密の書き込み*」)と呼ばれる数学的手法を使用して記録され、改ざんすれば証明書が無効になることです。
```suggestion
重要なのは、Maryのすべての属性が、暗号技術(文字通りには「*秘密の書き込み*」)と呼ばれる数学的手法を使用して記録され、改ざんすれば証明書が無効になることです。
```
literallyは、この場合は、言葉の字面としての意味としては～という注釈をつけているものかと思います。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +**秘密鍵とそれに対応する公開鍵との間のユニークな関係は、安全な通信を可能にする暗号マジックです**。
```suggestion
**秘密鍵とそれに対応する公開鍵との間の固有の関係は、安全な通信を可能にする暗号マジックです**。
```

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +鍵間の固有の数学的関係は、対応する公開鍵のみが適合できる署名をメッセージに対して生成し、それも同一メッセージに対してのみ有効な署名を生成するために、秘密鍵を使用することができるような関係である。
```suggestion
鍵間の固有な数学的関係は、対応する公開鍵のみが同じメッセージに対してのみマッチする署名を、秘密鍵が作成できるというようなものです。
```
これもあまりよいsuggestionではありませんが・・

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +*認証局は、異なる主体に証明書を配布します。
```suggestion
*認証局は、異なるアクターに証明書を配布します。
```

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +その結果、CAを信頼する(そして、その公開鍵を知っている)場合、そのアクターの証明書上のCAの署名を検証することによって、その特定のアクターが、その証明書に含まれる公開鍵にバインドされ、証明書に含まれる属性を所有することを信頼することができます。*
```suggestion
その結果、CAを信頼する(そして、その公開鍵を知っている)場合、そのアクターの証明書上のCAの署名を検証することによって、その特定のアクターが、その証明書に含まれる公開鍵に結びついており、証明書に含まれる属性を所有することを信頼することができます。*
```

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +これにより、特定のCAによって発行されたIDのコンシューマは、証明書が対応する秘密鍵の所有者(CA)によってのみ生成されえたことを確認することによって、IDを検証できます。
```suggestion
これにより、特定のCAによって発行されたIDを受け取った側は、証明書が対応する秘密鍵の所有者(CA)によってのみ生成されえたことを確認することによって、IDを検証できます。
```
あまりいい訳語が思いつかなかったので、ご参考です。

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +これらの中間CAは、ルートCAまたは別の中間CAによって発行された証明書を有し、チェーン内の任意のCAによって発行された任意の証明書のための「信頼のチェーン」の確立を可能にする。
```suggestion
これらの中間CAは、ルートCAまたは別の中間CAによって発行された証明書を有し、チェーン内の任意のCAによって発行された任意の証明書のための「信頼のチェーン」の確立を可能にします。
```

2020-09-03 23:41 UTC, shimos commented on docs/locale/ja_JP/source/identity/identity.md
> +ただし、CAを**いくつか**使用してIDを管理する必要があるため(テスト環境でも)、Fabric CAを使用して証明書を提供および管理できます。
```suggestion
ただし、**なんらかの**CAを使用してIDを管理する必要があるため(テスト環境でも)、Fabric CAを使用して証明書を提供および管理できます。
```

2020-09-04 04:37 UTC, siburu commented
@shimos 丁寧なレビューありがとうございます！反映します！

2020-09-07 08:49 UTC, siburu commented on docs/locale/ja_JP/source/identity/identity.md
> +*有効なクレジットカードを持っているだけでは十分ではなく、お店にも受け入れてもらわないといけません！
店舗に統一しました！

2020-09-07 08:50 UTC, siburu commented on docs/locale/ja_JP/source/identity/identity.md
> +これらの各アクター(サービスを消費できるネットワークの内部または外部のアクティブな要素)は、X.509デジタル証明書にカプセル化されたデジタルIDを持っています。
一通り「アイデンティティ」化しました

2020-09-07 08:50 UTC, siburu commented on docs/locale/ja_JP/source/identity/identity.md
> +一方、MSPは、店舗が受け入れるカード・プロバイダーのリストのようなものであり、どのIDが店舗支払いネットワークの信頼できるメンバー(アクター)であるかを決定します。
「決定する仕組みに相当します」と訳し直してみました

2020-09-08 09:20 UTC, siburu commented
@shimos レビューで頂いた各指摘に対応しました。
また、ヘッダ及びタイトルを追加で訳しました。

2020-09-08 17:01 UTC, shimos approved these changes
@siburu 修正ありがとうございました

2020-09-08 17:01 UTC, merged