[ja_JP] Key Concepts >> Introduction
hyperledger/fabric-docs-i18n pull request #132
Opened 2020-09-04 08:07 UTC by nekia

Signed-off-by: Atsushi Neki <atsushin@fast.au.fujitsu.com>

Resoloved #98

2020-09-08 12:49 UTC, Naoya-Horiguchi requested changes
いくつかコメントさせていただきました。ご確認をお願いいたします。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +**協力して** データを保持することから、多くの場合、 **分散型** と呼ばれます。
decentralized は「分散型」と「非中央集権型」のどちらにするか決まっていませんが、より一般的に glossary に訳語がない用語をどう統一していくか決めてから必要に応じてまとめて変換したほうが良い気もするので、ここではこのままで良いと思います。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +このデータの分散化と参加者の協力関係が、企業が現実世界で商品やサービスをやりとりする行為を
```suggestion
このデータの分散化と参加者の協力関係が、企業が現実世界で商品やサービスをやりとりする方法を
```

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +**コンセンサス**
Consensus を「コンセンサス」とするか「合意形成」かとするか、glossary と統一取れないでしょうか? この訳文内でも、両方の訳語が混在しているようです。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +適切な参加者によって取引が承認された場合にのみ台帳が更新され、台帳の更新時に同じ取引が同じ順序で更新されるように、ネットワーク全体で台帳取引を同期化するプロセスのことを **コンセンサス** と呼びます。
transaction はビジネスの文脈では「取引」でもよいのですが、Fabric の内部用語としては「トランザクション」としたほうがよいのではないでしょうか?

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +更新しただけのものです。16世紀のフランダース地方の織物であろうと、今日の証券であろうと、
一文めと二文めが入れ替わっていますが、原文を尊重するのがよいのではないでしょうか。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +それは商品を販売する事業者が現在その所有権を持っていることを一連の所有権の情報によって
```suggestion
それは商品を販売する事業者が現在その所有権を持っていることを所有権の変遷の情報によって
```
"chain of title" は「所有権の変遷」を意味するようです。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +ビジネス・ネットワークにネットワーク上でのIDの確立、トランザクションの実行、
```suggestion
ビジネス・ネットワークにネットワーク上での身元確認、トランザクションの実行、
```
identity と ID は別の概念というのと、L89 で「身元」としているのでそれに揃えてはいかがでしょうか。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +これがブロックチェーン・ネットワークであり、すべての参加者が独自のレプリケートされた
```suggestion
これがブロックチェーン・ネットワークであり、すべての参加者が独自の複製された
```

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +ブロックチェーン上の台帳は、ネットワーク参加者の多くにレプリケートされ、各参加者が
```suggestion
ブロックチェーン上の台帳は、ネットワーク参加者の多くに複製され、各参加者が
```
L65 で replicated を複製と訳しているので、それに揃えてはいかがでしょうか。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +共有台帳を通じてビジネス・ネットワークを制御する機能により、
```suggestion
共有台帳を通じてビジネス・ネットワークを統合する機能により、
```

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +ブロックチェーン・ネットワークは、信頼性と可視性を向上させながら、個人情報と処理に
```suggestion
ブロックチェーン・ネットワークは、信頼性と可視性を向上させながら、プライベートな情報とプロセスに
```
原文L114あたりの翻訳と語彙を揃えてはいかがでしょう。

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +主要な標準の採用が促進されています。
```suggestion
主要な標準の採用を促進しています。
```

2020-09-08 12:49 UTC, nhoriguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +他のブロックチェーン・テクノロジと同様に、台帳があり、スマートコントラクトを使用し、
```suggestion
他のブロックチェーン技術と同様に、台帳があり、スマートコントラクトを使用し、
```
前の段落と訳語を統一するのがよいでしょう。

2020-09-08 12:49 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +信頼できる **Membership Service Provider(MSP)** を通じて登録します。
```suggestion
信頼できる **メンバーシップサービスプロバイダ (MSP)** を通じて登録します。
```

2020-09-08 12:49 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +ワールドステートの現在値となるまでのすべての取引が記録されます。
```suggestion
ワールドステートが現在の値となるまでのすべての取引が記録されます。
```

2020-09-08 12:49 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +台帳には、ワールドステートのデータ・ストアは変更が可能です。既定では、
```suggestion
台帳には、ワールドステートに対する変更可能なデータストアがあります。既定では、
```
「データ・ストア」と「データストア」という表記ゆれがあるので、どちらかに寄せるのがよいでしょう。

2020-09-08 12:49 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +ブロックチェーン・ネットワークで使用されている台帳データベースの変更前の値と
訳文全体にわたって「ブロックチェーンネットワーク」と「ブロックチェーン・ネットワーク」の表記ゆれがあるようです。

2020-09-08 12:49 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +トランザクションは、ネットワーク内の異なる参加者の間で発生したものであっても、
```suggestion
トランザクションは、ネットワーク内の参加者の異なるセットの間で発生したものであっても、
```

2020-09-08 12:49 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +たとえば、PBFT(実用的ビザンチン障害耐性)は、不正・不良が発生した場合でも
```suggestion
たとえば、PBFT(実用的ビザンチン障害耐性)は、故障が発生した場合でも
```

2020-09-08 12:49 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/blockchain.rst
> +競合するコンピューターが、それ以降のすべてのプロセスが構築されるブロックの順序を
原文が悪文ですが、"all process subsequently build upon" の部分は、全てのプロセスがその後「定義された順序」に基づいて事を進める、という意味に読めます。

2020-09-08 14:28 UTC, nekia commented
レビューどうもありがとうございます! 確認してアップデートします。

2020-09-10 08:31 UTC, nekia commented on docs/locale/ja_JP/source/blockchain.rst
> +**コンセンサス**
glossaryに合わせて「合意形成」に統一します

2020-09-10 10:43 UTC, nekia commented on docs/locale/ja_JP/source/blockchain.rst
> +更新しただけのものです。16世紀のフランダース地方の織物であろうと、今日の証券であろうと、
そうですね、順序を正します

2020-09-10 10:43 UTC, nekia commented on docs/locale/ja_JP/source/blockchain.rst
> +適切な参加者によって取引が承認された場合にのみ台帳が更新され、台帳の更新時に同じ取引が同じ順序で更新されるように、ネットワーク全体で台帳取引を同期化するプロセスのことを **コンセンサス** と呼びます。
他の「取引」「トランザクション」利用箇所を見直します

2020-09-10 11:00 UTC, nekia commented on docs/locale/ja_JP/source/blockchain.rst
> +トランザクションは、ネットワーク内の異なる参加者の間で発生したものであっても、
「の」が続いたので少し加筆して「ネットワークにおいて参加者の異なるセットの間で発生したものであっても」にしようと思います。

2020-09-10 11:14 UTC, nekia commented on docs/locale/ja_JP/source/blockchain.rst
> +競合するコンピューターが、それ以降のすべてのプロセスが構築されるブロックの順序を
以下のようにアップデートします。

一方、Bitcoinでは、マイニングと呼ばれるプロセスを通じて順序付けが行われ、
競合するコンピューターが、ブロックの順序を定義する暗号パズルを解く競争をし、
その定義された順序に基づいて、その後の全てのプロセスが進められます。

2020-09-10 11:37 UTC, nekia commented
アップデートしました。 d713225753245f37e5350ad4e25b4e11bac29a6a
修正確認のほどどうぞよろしくお願いします。
@Naoya-Horiguchi

2020-09-12 05:12 UTC, Naoya-Horiguchi approved these changes
どうもありがとうございました。

2020-09-12 05:12 UTC, Naoya-Horiguchi commented
/azu run

2020-09-12 05:22 UTC, Naoya-Horiguchi commented
docs/readthedocs.org:fabric-docs-ml-in の失敗ですが、私も同じ問題に遭遇したことがあり、そのときはベースとなるコミットを最新の release-2.2 ブランチに更新したら解消しました。お手数ですが、リベースしてブランチを更新していただけますでしょうか?

2020-09-13 01:22 UTC, nekia commented
@Naoya-Horiguchi 確認ありがとうございます。rebase & squashしました。

2020-09-13 05:16 UTC, merged