[ja_JP] Key Concepts >> Blockchain network
hyperledger/fabric-docs-i18n pull request #141
Opened 2020-09-07 15:05 UTC by Naoya-Horiguchi

I translated `network/network.md` into Japanese. Any comments are welcomed. Thank you.

2020-09-10 00:30 UTC, shimos requested changes
大変長い文章の翻訳ありがとうございます。いくつかコメントをしました。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +
> This topic will use a manageable worked example that introduces all of the major components in a blockchain network.

この文を訳し忘れているようです。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +このトピックを呼んでポリシーの概念を理解したあとは、デプロイされた Hyperledgger Fabric ネットワークを制御するポリシーを確立するために組織間の決定について確かな理解が得られるでしょう。
```suggestion
このトピックを呼んでポリシーの概念を理解したあとは、デプロイされた Hyperledger Fabric ネットワークを制御するポリシーを確立するために組織間の決定について確かな理解が得られるでしょう。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +一言で言えば、Hyperledger Fabric の主要な技術的なコンポーネントと、それらについて組織が行う意思決定について理解できるでしょう。
```suggestion
一言で言えば、Hyperledger Fabric の主要な技術的なコンポーネントと、それらについて組織が行う必要がある意思決定について理解できるでしょう。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +各ピアノード内で、トランザクションは台帳のコピー上に不変なものとして記録されます。
```suggestion
各ピアノード内で、トランザクションは台帳のコピー上にイミュータブルなものとして記録されます。
```
Glossaryなどでも、イミュータブルとして訳していたと思いますので、統一した方がいいかと思います。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +次のフェーズでは、組織R1のユーザにネットワークの権利者権限を与えます。
```suggestion
次のフェーズでは、組織R1のユーザにネットワークの管理権限を与えます。
```
「管理者権限」のtypoと思われますが、administer/administrative rightsは、特に理由がなければ同じ訳語（「者」なし）で統一したほうがよいかと思います。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +これは組織R1のユーザーを確認するために使用されます。
```suggestion
これは組織R1のユーザーを同定するために使用されます。
```
上でidentifyを同定と訳していたので、同様に訳した方がよいかと思います。もしくは、最後の行で使用している「識別」でもよいかと思います。以下の文章でもいくつかありました。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +OrdererノードO4はR4の基盤上で走行していますが、R1はネットワークアクセスがある限り、これに対する管理者権限を共有しています。
```suggestion
OrdererノードO4はR4の基盤上で実行されていますが、R1はネットワークアクセスがある限り、これに対する管理権限を共有しています。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +最も単純な形では、オーダリングサービスはネットワーク内の一つのノードで、図にもそのようになっています。
```suggestion
最も単純な形では、オーダリングサービスはネットワーク内の一つのノードで、この例でもそのようになっています。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +オーダリングサービスは通常複数ノードであり、複数の組織に複数のノードでを持つよう設定されることもあります。
```suggestion
オーダリングサービスは通常複数ノードであり、複数の組織が複数のノードを持つよう設定されることもあります。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +しかし現時点では、単にオーダリングサービスは一つの管理点で、ネットワークに対する制御されたアクセス制御を様々な組織に与えるものだと考えておいてください。
```suggestion
しかし現時点では、単にオーダリングサービスは一つの管理点で、ネットワークに対するアクセス制御を様々な組織に与えるものだと考えておいてください。
```
重複なので省いてよいと思います。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +また、R2のユーザを確認するために、CA2が追加されていることも示しています。
```suggestion
また、R2のユーザを同定するために、CA2が追加されていることも示しています。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +チャネルは主要な
```suggestion
チャネルは
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +R3とR4は、R1あるいはR2がチャネル設定CC1を適切なポリシーを追加された場合のみ、C1と相互作用することができます。
```suggestion
R3とR4は、R1あるいはR2がチャネル設定CC1を適切なポリシーを追加された場合のみ、C1とやりとりすることができます。
```
"interact with (a channel)"のちょうどよい日本語が思いつきませんが、これくらいでしょうか・・

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +ある例は誰がチャネルに新しい組織を追加できるかを定義しています。
```suggestion
一つの例としては、誰がチャネルに新しい組織を追加できるかの定義です。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +*ピアノードP1がチャネルC1に参加します。
```suggestion
*ピアノードP1がチャネルC1に参加しています。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +後ほど、ピアが果たす異なる役割について少し見ていきます。
```suggestion
少し後で、ピアが果たす異なる役割について見ていきます。
```
たぶん"a little"は"later"にかかっているだけに思えます(なので、あえて「少し」を訳出する必要もないかもしれません)

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +S5を台帳に対する共通のアクセスパターンの全てを定義していると考えてください。
```suggestion
S5が台帳に対する共通のアクセスパターンの全てを定義していると考えてください。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +スマートコントラクトは、コンソーシアムメンバ間で共有されるビジネスプロセスを実装するために、各組織に属するアプリケーション開発者によって作成されます。
```suggestion
スマートコントラクトは、コンソーシアムメンバ間で共有されるビジネスプロセスを実装するために、各組織に属するアプリケーション開発者が作成することができます。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +スマートコントラクトは、ネットワーク内の各ノードに後々分配されうるトランザクションの生成を助けるために使用されます。
```suggestion
スマートコントラクトは、ネットワーク内の各ノードに後々配布されうるトランザクションの生成を助けるために使用されます。
```
もしくは「分散させうる」でしょうか。"distribute"は分割するイメージがない気がするので、"dispense"とは訳語を変えた方がいいかもしれません。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +スマートコントラクトはトランザクションと管理するもので、一方、チェーンコードはスマートコントラクトがデプロイのためにどのようにパッケージされているかを管理していると考えてください。
```suggestion
スマートコントラクトはトランザクションを管理するもので、一方、チェーンコードはスマートコントラクトがデプロイのためにどのようにパッケージされているかを管理していると考えてください。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +クライアントアプリケーションは、スマートコントラクトのエンドースメントポリシーによって指定された組織が所有するピアに対してトランザクション提案を送信することによってインストールを実行します。
```suggestion
クライアントアプリケーションは、スマートコントラクトのエンドースメントポリシーによって指定された組織が所有するピアに対してトランザクション提案を送信することによってスマートコントラクトをinvokeします。
```
原文があまりよくない気がしますが、"do this"は、"it [a smart contract] can be invoked"を受けて"invoke a smart contract"を指していると解釈するのが、一番文意が通る気がします。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +トランザクション応答はピアノードからクライアントアプリケーションに返却されます。
```suggestion
ピアノードは、トランザクション応答をクライアントアプリケーションに返します。
```
通信の文脈で「返却」はしっくりこない気がしました。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +完全にエンドースされたトランザクション (ネットワーク全体に分配されるのはこのトランザクションです) を作成するためにトランザクション提案とともにパッケージされるのはこれらのトランザクション応答です。
```suggestion
完全にエンドースされたトランザクション (ネットワーク全体に配布されるのはこのトランザクションです) を作成するためにトランザクション提案とともにパッケージされるのはこれらのトランザクション応答です。
```
l.273と同様です。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +また、P2はアプリケーションA2を保有し、チャネルC1に参加します。
> A2 and P2 are identified using certificates from CA2

が訳し忘れているようです。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +常に台帳のコピーをホストしているピアノードとは対照的に、ピアノードには二つの異なる種類、つまりスマートコントラクトをホストするものとしないものがあることが分かります。
```suggestion
ピアノードには、台帳のコピーは常にホストしているのとは対照的に、スマートコントラクトをホストするものとしないものという二つの異なる種類があることがわかります。
```

原文が変な気がしますので、ここは意訳のほうがわかりやすいと思います。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +しかし、より大きなネットワークでは、スマートコントラクトのコピーををホストしないピアノードが多数あるでしょう。
```suggestion
しかし、より大きなネットワークでは、スマートコントラクトのコピーをホストしないピアノードが多数あるでしょう。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +しかし、そのピアはチャネルに接続されることによってスマートコントラクトのインターフェースについて**知る**ことができます。
```suggestion
ピアは、スマートコントラクトがインストールされたときのみ、それを*実行*することができますが、チャネルに接続されることでスマートコントラクトのインタフェースを*知る*ことはできます。
```

この節全体として主意が不明瞭なのですが、この文のcanは、いずれも"可能である"という意味な気がします。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +    コミットピアは生成されたトランザクションのブロックを受信し、それを検証した後、append 操作のようにピアノードの台帳のコピーにトランザクションをコミットします。
```suggestion
    コミットピアは生成されたトランザクションのブロックを受信し、それを検証した後、追記操作としてピアノードの台帳のコピーにトランザクションをコミットします。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +    このことは、ある組織のピアには、オーダリングサービスに接続する一つ以上のリーダーがあることを意味します。
```suggestion
    このことは、ある組織のピアには、オーダリングサービスに接続する一つ以上のリーダーが存在しうることを意味します。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +私たちのネットワークでは、チャネルC1は二つのクライアントアプリケーション、二つのピアノード、そしてオーダリングサービスに接続しています。
```suggestion
私たちのネットワークでは、チャネルC1は二つのクライアントアプリケーション、二つのピアノード、そしてオーダリングサービスが接続しています。
```
より原文に近いのは「をつないでいます」でしょうけど、この言い方の方が自然な気がします。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +さらに、各組織内のピアが効率よく互いを発見し、コミュニケートするための技術的なメカニズム、つまり[ゴシッププロトコル](../gossip.html#gossip-protocol)、によってそのようなトポロジーの多数のピアノードを収容するでしょう。
```suggestion
さらに、各組織内のピアが効率よく互いを発見し、やりとりするための技術的なメカニズム、つまり[ゴシッププロトコル](../gossip.html#gossip-protocol)、によってそのようなトポロジーの多数のピアノードを収容するでしょう。
```
communicateを「やりとりする」となっている箇所が多いようです。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +チャネルC2が作成されると、組織R2とR3によって他のネットー枠要素とは独立に管理されます。
```suggestion
チャネルC2が作成されると、組織R2とR3によって他のネットワーク要素とは独立に管理されます。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +ネットワークの**秘密情報**がO4が従うネットワークNC4に含まれていることを意味します。
```suggestion
ネットワークの**知性**がO4が従うネットワークNC4に含まれていることを意味します。
```

比喩的な表現で、正直真意がわからないのですが、何か秘匿されている情報というよりは、ネットワークが正しく管理されていく上で必要な判断をするもの、のような意味かと思われます。なので、「知能」や「知性」と訳すほうがよいかなと思います。
(他にご意見があればお願いいたします)

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +私たちのネットワークにおいて、P1とP2は同じようにアクターです。
```suggestion
私たちのネットワークにおいて、P1とP2は同じように正しいアクターです。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +ピアノードP1とP2がクライアントアプリケーションA1およびA2と相互作用するとき、
```suggestion
ピアノードP1とP2がクライアントアプリケーションA1およびA2とやりとりするとき、
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +例えば、もしA1がピアノードP1あるいはP2上のスマートコントラクト (チェーンコード) S5にアクセスしたいとき、各ピアーノードはCC1のコピーを用いて、A1が実行できる操作を判断します。
```suggestion
例えば、もしA1がピアノードP1あるいはP2上のスマートコントラクト (チェーンコード) S5にアクセスしたいとき、各ピアノードはCC1のコピーを用いて、A1が実行できる操作を判断します。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +ネットワーク・チャネル設定を変更するために、管理者はコンフィギュレーショントランザクションを発行なければなりません。
```suggestion
ネットワーク・チャネル設定を変更するために、管理者はコンフィギュレーショントランザクションを発行しなければなりません。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +システムチャネルを用いて、オーダリングサービスノードはネットワークのコンフィギュレーショントランザクションを分配します。
```suggestion
システムチャネルを用いて、オーダリングサービスノードはネットワークのコンフィギュレーショントランザクションを配布します。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +同様に、**アプリケーションチャネル**内のピアノードは、チャネルのコンフィギュレーショントランザクションを分配できます。
```suggestion
同様に、**アプリケーションチャネル**内のピアノードは、チャネルのコンフィギュレーショントランザクションを配布できます。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +例えば、ネットワーク設定のようなオブジェクトは論理的に一つですが、物理的にはオーダリングサービスノードのセットの間で複製ていることが分かります。
```suggestion
例えば、ネットワーク設定のようなオブジェクトは論理的に一つですが、物理的にはオーダリングサービスノードのセットの間で複製されていることが分かります。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +とりわけ、チャネル設定CC1に含まれるポリシーは、P2がチャネルC1上で取引するときに用いられる操作を記述しており、一方チャネルC2におけるP2の振る舞いを管理するのはチャネル設定CC2内のポリシーです。
```suggestion
とりわけ、チャネル設定CC1に含まれるポリシーは、P2がチャネルC1上で取引するときに用いることができる操作を記述しており、一方チャネルC2におけるP2の振る舞いを管理するのはチャネル設定CC2内のポリシーです。
```
or 「利用可能な」

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +再び、R2とR1がチャネルC1に対するルールについて同意し、一方R2とR3がチャネルC2に対するルールについて同意することが望ましいです。
```suggestion
繰り返しますが、R2とR1がチャネルC1に対するルールについて同意し、一方R2とR3がチャネルC2に対するルールについて同意しているので、これは望ましいことです。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +Ordererを管理するネットワーク設定ポリシーNC4にR1とR4を追加しましたが、このノードはR4の基盤として稼働しています。
```suggestion
Ordererを管理するネットワーク設定ポリシーNC4にR1とR4を追加しましたが、このノードはR4の基盤の上で稼働しています。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +非中央集権的な世界で、これは間違っているように見えます!
```suggestion
非中央集権的な世界では、これは間違っているように見えます!
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +なぜならO1とO4はいずれもネットワーク設定NC4のポリシーで定義されているように同じ様に振る舞うからです。
```suggestion
なぜならO1とO4はいずれもネットワーク設定NC4のポリシーで定義されている通りに同じ様に振る舞うからです。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +つまり、トランザクションの分配ポイントであるということです。
```suggestion
つまり、トランザクションの配布ポイントであるということです。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +各コミットピアでは、トランザクションが妥当かどうかが記録され、台帳のローカルコピーが適切に更新されます。
```suggestion
各コミットピアでは、妥当であるかどうかにかかわらずトランザクションが記録され、台帳のローカルコピーが適切に更新されます。
```
実際、validかどうかは記録されるのですが、原文の"whether [they be] valid or invalid"は、are recordedの主語でなく、その文を修飾してるようにみえます。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +オーダリングサービスノードは、ネットワーク内の複数の組織を通して要求されたときには、複数ノードに分散させることが可能です。
```suggestion
オーダリングサービスノードは、必要に応じて、ネットワーク内の複数の組織にノードを分散させることが可能です。
```

"throughout ..." と "as required" は両方とも"distributed"にかかっていると思われます。

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +根底にある哲学は、ポリシーの変更が、組織内のものであろうと組織間のものであろうと、あるいは外部の調整者によって課されたものであろうと、不変のものであるということです。
```suggestion
根底にある哲学は、ポリシーの変更が、組織内のものであろうと組織間のものであろうと、あるいは外部の規制機関によって課されたものであろうと、常に起こりうるものであるということです。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +R4は、チャネル作成とコンソーシアム作成のポリシーにR1をを追加することで、これを実行しました。
```suggestion
R4は、チャネル作成とコンソーシアム作成のポリシーにR1を追加することで、これを実行しました。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +実際は、R4はmod_policyを設定して、R4が変更を承認する必要があるとするか、あるいはmod_policyの全ての組織がその変更を承認する必要があるとするでしょう。
```suggestion
実際は、R4はmod_policyを設定して、R4も変更を承認する必要があるとするか、あるいはmod_policyの全ての組織がその変更を承認する必要があるとするでしょう。
```

2020-09-10 00:30 UTC, shimos commented on docs/locale/ja_JP/source/network/network.md
> +基本的な設定を洗練された設定に素直に発展させていくことができる、これがmod_policyの作用です。
```suggestion
基本的な設定を洗練された設定に徐々に発展させていくことができる、これがmod_policyの作用です。
```
ここでのgracefulは、コンピュータ用語での"gradual”の意味だと思います。

2020-09-10 12:20 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/network/network.md
> +チャネルは主要な
余分な改行が残されたままでしたので、合わせて修正いたします。

2020-09-10 13:37 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/network/network.md
> +スマートコントラクトは、ネットワーク内の各ノードに後々分配されうるトランザクションの生成を助けるために使用されます。
distribute は全体的に「分配」と訳してしまった気がするので、当該箇所を再点検して「配布」にします。

2020-09-10 14:27 UTC, nhoriguchi commented on docs/locale/ja_JP/source/network/network.md
> +さらに、各組織内のピアが効率よく互いを発見し、コミュニケートするための技術的なメカニズム、つまり[ゴシッププロトコル](../gossip.html#gossip-protocol)、によってそのようなトポロジーの多数のピアノードを収容するでしょう。
他にも「コミュニケートする」がありますので、「やりとりする」に揃えます。

2020-09-11 00:30 UTC, Naoya-Horiguchi commented
@shimos さん、レビューありがとうございました (誤字脱字等基本的なミスが多くてすみません)。いただいたコメントを元にブランチを修正しました (diff は[こちら](https://github.com/hyperledger/fabric-docs-i18n/compare/4712678b45bb69d40492de9e5419bdc3752b6f53..bf6923d3d5575ec5256352b3bbabbcebed9463b2)) ので、ご確認をお願いいたします。

2020-09-11 03:38 UTC, shimos approved these changes
修正ありがとうございました。LGTM

2020-09-11 03:39 UTC, merged