[ja_JP]Translate "CONTRIBUTING.rst" into japanese(#47)
hyperledger/fabric-docs-i18n pull request #188
Opened 2020-09-16 10:28 UTC by Skurimura

This patch translates CONTRIBUTING.rst into japanese
issue #47

Signed-off-by: shogo kurimura <e35857@jp.ibm.com>

2020-09-16 20:30 UTC, shimos requested changes
@Skurimura 翻訳ありがとうございます。いくつか気になった点について、コメントを加えましたので、確認をお願いいたします。

なお、関係のないファイル(.DS_Store)がcommitに含まれているようですので、これはcommitから削除してください。
Fabricのドキュメントには、`git add .`と書かれていますが、このように意図しないファイル(macOSの場合は特に.DS_Store)を含んでしまう可能性があるので、`git add (翻訳したファイル名)`のように、明示的にファイルを指定してaddすることをお勧めします。
余計なファイルが含まれているかは、commitの前の`git status`や、commit後の`git show`で変更を加えた内容をチェックするのもよいと思います。
whitespace errorに関しては、`git diff --check`などでチェックすることをお勧めします。

また、CIのエラーは、最新のrelease-2.2にrebaseすると直ることがあるようですので、次のpushではあわせてお願いいたします。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +  ライターのコミュニティを形成したり、コントリビューションを構成したりする必要があるため、作業量は多くなりますが、
```suggestion
  ライターのコミュニティを形成したり、貢献をまとめる必要があるため、作業量は多くなりますが、
```
他の文章でも、貢献と訳しているようですので、統一した方がよいかと思います。(以下、何個か出てくるのでそちらも同様です)

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +ライターまたは情報開発者として:
「情報開発者」は、該当する日本語の一般的な職名が特にないようなので、そのままインフォメーション・デベロッパーなどとするのはいかがでしょうか。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +  `release roadmap <https://jira.hyperledger.org/secure/Dashboard.jspa?selectPageId=10104>`_ で興味のあるEpicを見つけたら、Jiraの作業項目か,
```suggestion
  `release roadmap <https://jira.hyperledger.org/secure/Dashboard.jspa?selectPageId=10104>`_ で興味のあるEpicを見つけたら、Jiraの作業項目か、
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +- あなたのFabricの経験とこのドキュメントを使用して、既存のトピックを改善したり、新規トピックを作成するなど、このドキュメントを更新します。
```suggestion
- あなたのFabricの経験とこのドキュメントを使用して、既存のトピックを改善したり、新規トピックを作成するなど、このドキュメントを更新します。
```
trailing whitespaceがあるようです。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +- フルタイムで開発を行うことができるのであれば、新しい機能を提案して(`Making Feature/Enhancement Proposals`_ を参照してください)
```suggestion
- フルタイムで開発を行うことができるのであれば、新しい機能を提案して(`Making Feature/Enhancement Proposals`_ を参照してください)
```
これもwhitespace errorです

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +これは迅速かつ簡単に行うことができ、適切に構成されたマシン(必要な事前要件ソフトウェアを含む)を用意しながら、
```suggestion
これは迅速かつ簡単に行うことができ、適切に構成されたマシン(必要な事前要件ソフトウェアを含む)があることを確認しつつ、
```
もしくは、「マシンが適切に構成されていることを確認しつつ、」などのほうが自然でしょうか。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +削除の提案についても、過半数の承認が必要です。
```suggestion
解任の提案についても、過半数の承認が必要です。
```
ここでのremovalは解任に統一したほうがよいと思います。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +RocketChatの#fabric-releaseチャネルのディスカッション内容を確認してください
```suggestion
RocketChatの#fabric-releaseチャネルのディスカッション内容を確認してください。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +コントリビュータミーティングの目的は、リリースとコントリビュータの進捗を計画し、レビューし、プロジェクトとサブプロジェクトの技術的および運用上の方向性を議論することである。
```suggestion
コントリビュータミーティングの目的は、リリースとコントリビュータの進捗を計画し、レビューし、プロジェクトとサブプロジェクトの技術的および運用上の方向性を議論することです。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +EpicsのFabricリリースロードマップは `JIRA <https://jira.hyperledger.org/secure/Dashboard.jspa?selectPageId=10104>`__ で管理されています。
```suggestion
EpicのFabricリリースロードマップは `JIRA <https://jira.hyperledger.org/secure/Dashboard.jspa?selectPageId=10104>`__ で管理されています。
```
これはスタイルの問題なので、単なるsuggestionですが、アルファベットのまま使う場合でも、単数形のままにしたほうが日本語として統一感があるように見えます。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +`community <https://www.hyperledger.org/community>`__ はいつでも助たいと思っています。
```suggestion
`community <https://www.hyperledger.org/community>`__ はいつでも助けたいと思っています。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +ほとんどの人は噛みついたり、笑ったりしないし、喜んで助けます。
```suggestion
ほとんどの人は噛みついたり、喜んで助けます。
```
原文にはないので不要ではないでしょうか(:grin:は、biteに対する絵文字だと思います)。絵文字は、readthedocsでは出力されていないようなので削除でよいと思います。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +以前に報告されたことがある場合は、問題の修正を確認したいというコメントを追加できます。
```suggestion
以前に報告されたことがある場合は、不具合が修正されてほしいというコメントを追加できます。
```
なお、以下でも、defectが不具合・欠陥と統一されていないようですので、いずれかの語に統一した方がよいかと思います。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +これまでに報告されていない場合は、欠陥と修正を記述した文書化されたcommitメッセージとともにPRを提出するか、新しいJIRAを作成することができます。
```suggestion
これまでに報告されていない場合は、欠陥と修正を記述した文書化されたコミットメッセージとともにPRを提出するか、新しいJIRAを作成することができます。
```
他の文章でもコミットに翻訳しているようですし、l.288もそのように訳しているので統一するのがよいと思います。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +例えば、docのバグは ``#fabric-documentation`` に、データベースのバグは ``#fabric-ledger`` にブロードキャストされるべきです。
```suggestion
例えば、ドキュメントのバグは ``#fabric-documentation`` に、データベースのバグは ``#fabric-ledger`` にブロードキャストされるべきです。
```
原文で略しているのに特に明確な理由はなさそうですので、ドキュメントとしたほうがわかりやすいと思います。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +バグの発見をJIRAで報告するか、もしくは修正を提供したいのであれば、喜んで歓迎します。
```suggestion
バグの発見をJIRAで報告して、修正を提供したいのであれば、喜んで歓迎します。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +適切な時間内に終了できない場合は、割り当てを取り消してください。また、もう少し時間が必要な場合は、まだ問題に取り組んでいるというコメントを追加してください。
"be considerate"の訳が抜けてるようです。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +その結果、メンテナンス担当者はPRをより迅速に処理できるようになり、誰もがPRから利益を得ることができます。
```suggestion
その結果、メンテナンス担当者はPRをより迅速に処理できるようになり、誰もがそれから利益を得ることができます。
```
them(=PRs)ではないので、PRそのものというよりかは、迅速に処理できるようになること全体を指すものと思われます。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +ほとんどのプロジェクトが直面している問題の1つは、バックログとFabricを効果的に管理することです。
```suggestion
ほとんどのプロジェクトが直面している問題の1つは、バックログを効果的に管理することで、Fabricも例外ではありません。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +PRが2週間更新されていない場合は、PRを更新して未解決のコメントに対処するか、またはPRが撤回される場合は破棄するかのいずれかを求める注意喚起コメントが追加されます。
```suggestion
PRが2週間更新されていない場合は、PRを更新して未解決のコメントに対処するか、またはPRが撤回されるべき場合は破棄するかのいずれかを求める注意喚起コメントが追加されます。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +提出されたPRがすべての検証に合格したが、72時間(3日間)の間にレビューされなかった場合、レビューコメントを受け取るまで、毎日#fabric-pr-reviewチャネルにフラグが付けられます。
```suggestion
提出されたPRがすべての検証に合格したが、72時間(3日間)の間にレビューされなかった場合、レビューコメントを受け取るまで、毎日#fabric-pr-reviewチャネルに通知されます。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +   回帰(退行)があった場合、コードの大部分に影響を与える複合的な変更がある場合よりも、原因となるコミットを特定する方がはるかに容易です。
```suggestion
   リグレッションがあった場合、コードの大部分に影響を与える複合的な変更がある場合よりも、原因となるコミットを特定する方がはるかに容易です。
```
この用法の場合、カタカナで記述することが多いような気がしますがいかがでしょうか。(～テストの場合は、回帰テストなどとする場合がありますが・・)

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +   なぜなら、a)何をいつ提供できるかをより適切に判断するために、開発速度を追跡したいからです。b)より効果的に変更が適切であるか判断できるからです。
```suggestion
   なぜなら、a)何をいつ提供できるかをより適切に判断するために、開発速度を追跡したいからです。また、b)より効果的に変更が適切であるか判断できるからです。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +   多くの場合、提案された変更に関して何らかの話し合いが必要であり、変更自体からその変更にリンクしたいと考えています。
```suggestion
   多くの場合、提案された変更に関して何らかの話し合いが必要であり、話し合いからその変更にリンクしたいと考えています。
```
thatはdiscussionを指していると思います。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +   それ以外はユニット・テストではなく、定義による統合テストです。なぜなら、多くのオープンソース開発者がテスト駆動開発を行っているからです。
```suggestion
   それ以外はユニット・テストではなく、定義によれば統合テストです。なぜなら、多くのオープンソース開発者がテスト駆動開発を行っているからです。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +   可能な場合は、変更内容を200〜300行以下に抑えてください。大きな変更がある場合は、それを複数の変更に分割してください。
```suggestion
   可能な場合は、変更内容を200〜300LOC以下に抑えてください。大きな変更がある場合は、それを複数の変更に分割してください。
```
他はLOCのままなので、統一するのがよいと思います。

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +リベースが必要になるほどのレビューコメントを含むプルリクエストを放置してはなりません。
```suggestion
リベースが必要になるほどまで、レビューコメントのついたプルリクエストを放置してはなりません。
```
such that以下は、let ... festerにかかっていると思います

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +**注意:** 各ソースファイルには、Apache Software License2.0のライセンスヘッダーを含める必要があります。
```suggestion
**注意:** 各ソースファイルには、Apache Software License 2.0のライセンスヘッダーを含める必要があります。
```

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +何か取り組むものを探していたり、問題をデバッグしたり問題の修正をしたりするのに専門家の助けが必要なとき、私たちの
```suggestion
何か取り組むものを探していたり、問題をデバッグしたり問題の修正をしたりするのに専門家の助けが必要なとき、私たちの
```
whitespace errorです

2020-09-16 20:30 UTC, shimos commented on docs/locale/ja_JP/source/CONTRIBUTING.rst
> +
```suggestion

```
whitespace errorです

2020-09-24 01:48 UTC, Skurimura commented
@shimos ご確認いただきありがとうございます。コメント頂いた点を反映いたしました。

2020-09-24 19:06 UTC, shimos approved these changes
@Skurimura 修正ありがとうございました

2020-09-24 19:09 UTC, merged