Update test_network.md
hyperledger/fabric-docs-i18n pull request #193
Opened 2020-09-21 04:00 UTC by browncrane

翻译部分内容，并修改markdown格式错误

2020-09-21 06:02 UTC, stone-ch commented
DCO问题，请在本地仓库执行如下两个命令解决：
git commit --amend --signoff
git push --force-with-lease origin patch-1

2020-09-21 06:10 UTC, stone-ch requested changes
本文档剩余内容是否会继续翻译？

2020-09-21 06:10 UTC, stone-ch commented on docs/locale/zh_CN/source/test_network.md
> +然后，您可以通过发出以下命令来启动网络。如果您尝试从另一个目录运行脚本，则会遇到问题：
发出->执行

2020-09-21 06:10 UTC, stone-ch commented on docs/locale/zh_CN/source/test_network.md
> +如果命令完成成功，您将看到已创建的节点的日志：
会达成->实现  完成成功->执行成功

2020-09-21 08:24 UTC, browncrane commented
可以，会在稍后找时间翻译

2020-09-22 14:55 UTC, stone-ch reviewed
有一些翻译不妥的地方，修改一下。

2020-09-22 14:55 UTC, stone-ch commented on docs/locale/zh_CN/source/test_network.md
> +## 在通道开始一个链码
开始->启动

2020-09-22 14:55 UTC, stone-ch commented on docs/locale/zh_CN/source/test_network.md
> +运行以下命令以获取已添加到频道账本中的汽车列表：
频道->通道

2020-09-22 14:55 UTC, stone-ch commented on docs/locale/zh_CN/source/test_network.md
> +## 与认证机构建立网络
与->使用

2020-09-22 14:55 UTC, stone-ch commented on docs/locale/zh_CN/source/test_network.md
> +Hyperledger Fabric使用公钥基础架构(PKI)来验证所有网络参与者的行为。
PKI：公钥基础设施

2020-09-24 14:25 UTC, stone-ch approved these changes
LGTM

2020-09-24 14:25 UTC, merged