[ja_JP]Translate "capabilities_concept.md" into japanese(#108)
hyperledger/fabric-docs-i18n pull request #228
Opened 2020-09-25 05:15 UTC by Skurimura

This patch translates capabilities_concept.md into japanese
issue(#108)

Signed-off-by: shogo kurimura <e35857@jp.ibm.com>

2020-09-29 04:59 UTC, satota2 requested changes

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +Fabricは分散システムであり、通常は複数の組織が関与するため、異なるバージョンのFabricコードが、ネットワーク内の異なるノードおよびそのネットワーク内のチャネルに存在する可能性があります。Fabricでは、すべてのピアとオーダリングサービスが同じバージョンレベルである必要はありません。実際、異なるバージョンレベルをサポートすることで、Fabricノードのローリングアップグレードが可能にな
```suggestion
Fabricは通常、複数の組織が関与する分散システムであるため、異なるバージョンのFabricコードが、ネットワーク内の異なるノードおよびそのネットワーク内のチャネルに存在する可能性があります。Fabricでは、すべてのピアとオーダリングサービスが同じバージョンレベルである必要はありません。実際、異なるバージョンレベルをサポートすることで、Fabricノードのローリングアップグレードが可能になります。
```

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +重要なのは、ネットワークとチャネルが同じ方法で処理し、チャネル構成の更新やチェーンコード呼び出しなどの確定的な結果を生成することです。確定的な結果が得られない場合、チャネル上のあるピアがトランザクションを無効にし、別のピアがトランザクションを検証する可能性があります。
```suggestion
重要なのは、ネットワークとチャネルが同じ方法で処理し、チャネル設定の更新やチェーンコード呼び出しなどの決定的な結果を生成することです。結果が決定的でなければ、チャネル上のあるピアがトランザクションを正当としない(無効)一方で、別のピアはトランザクションを正当とするかもしれません。
```

- deterministicは決定的と訳すのがよいかと思います。(他のページでもそう訳しているようです。)
- configurationは他のページに倣って「設定」がよいかと思います。同件の修正もお願いいたします。
- 最後の一文は意味合いがわかりやすいように、修正をしてみました。

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +そのために、Fabricは「ケーパビリティ(capabilities)」と呼ばれるレベルを定義します。これらのケーパビリティは、各チャネルの設定で定義され、動作が一貫した結果を生成するレベルを定義することによって、確定性を保証します。これらのケーパビリティには、ノード・バイナリー・バージョンと密接に関連したバージョンがあります。ケーパビリティにより、異なるバージョンレベルで実行されているノードは
```suggestion
そのために、Fabricは「ケーパビリティ(capabilities)」と呼ばれるレベルを定義します。これらのケーパビリティは、各チャネルの設定で定義され、動作が一貫した結果を生成するレベルを定義することによって、決定性を保証します。これらのケーパビリティには、ノード・バイナリ・バージョンと密接に関連したバージョンがあります。ケーパビリティにより、異なるバージョンレベルで実行されているノードは、特定のブロックの高さでのチャネル設定を前提として、互換性のある一貫した方法で動作することができます。また、特定のタスクを行うための管理領域ごとに定義されたケーパビリティが、設定ツリーの多くの部分に存在することもわかります。
```
- 「ブロック高さ」は間に「の」を挟んだほうがより自然かと思いました。
- 最後の一文は、原文的に訳しづらいですね。やや意訳気味ですが、私は意味合い的にはこういうことが言いたいものと解釈したのですが、いかがでしょうか。もし改悪しているようでしたら、元の訳文のままでも構いません。

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +* **リリースごとに新しいケーパビリティ・レベルがあるとは限りません**。
```suggestion
* **リリースごとに新しいケーパビリティレベルがあるとは限りません**。
```
この用語以外にもですが、中点をいれている箇所とそうでない箇所の表記ゆれがあるようですので、文章中での統一をお願いいたします（他の用語も含めて、同件の指摘は割愛します）。
個人的には、上記くらいの単語であれば、中点なしでもよいのかなと思います。

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +  ピアがチャネルに参加すると、台帳内のすべてのブロックが順番に読み取られます。これは、チャネルのジェネシスブロックから始まり、トランザクションブロックおよびそれ以降のすべての構成ブロックにわたって続きます。ピアなどのノードが、認識できないケーパビリティの更新を含むブロックを読み取ろうとした場合(たとえば、v1.4.xピアがv2.0アプリケーション・ケーパビリティを含むブロックを読み取ろうとした
```suggestion
  ピアがチャネルに参加すると、台帳内のすべてのブロックが順番に読み取られます。これは、チャネルのジェネシスブロックから始まり、トランザクションブロックおよびそれ以降のすべてのコンフィグレーションブロックにわたって続きます。ピアなどのノードが、認識できないケーパビリティの更新を含むブロックを読み取ろうとした場合(たとえば、v1.4.xピアがv2.0アプリケーション・ケーパビリティを含むブロックを読み取ろうとした場合)、 **ピアはクラッシュします**。v1.4.xピアはこの時点を過ぎてもトランザクションの検証やコミットを試行しないため、このクラッシュ動作は意図的なものです。チャネルに参加する前に、**ノードが、そのノードに関連するチャネル設定で指定されたケーパビリティのFabricバージョン(バイナリ)レベル以上であることを確認してください**。どのケーパビリティがどのノードに関連するかについては、後で説明します。といっても、ユーザーはノードがクラッシュすることを望んでいないため、ケーパビリティを更新する前に、すべてのノードを必要なレベル(できれば最新リリース)に更新することを強くお勧めします。これは、**常に**最新のバイナリおよびケーパビリティレベルにするというデフォルトのFabricの推奨事項に沿っています。
```
- configuration blockについては、コンフィグレーションブロックと訳しています。(Glossary参照) (同件の確認もお願いします。)
- 他の箇所は、文章がより自然になるように修正してみました。

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +* **オーダリングサービス**: これらのケーパビリティは、オーダリングサービス専用のタスクと処理を制御します。これらのケーパビリティには、トランザクションやピアに影響を与えるプロセスが含まれていないため、これらのケーパビリティの更新は、オーダリングサービスの管理に委ねられています。(ピアはOrdererのケーパビリティを理解する必要がないため、Ordererのケーパビリティがいずれかのバージ
```suggestion
* **Orderer**: これらのケーパビリティは、オーダリングサービス専用のタスクと処理を制御します。これらのケーパビリティには、トランザクションやピアに影響を与えるプロセスが含まれていないため、これらのケーパビリティの更新は、オーダリングサービスの管理者に委ねられています。(ピアはOrderer・ケーパビリティを理解する必要がないため、Orderer・ケーパビリティが何に更新されてもクラッシュしません)。ただし、**チャネル**のセクションで説明するように、これは、v1.1のオーダリングノードがv1.4.2より低いケーパビリティ・レベルのすべてのチャネルで機能することを意味するわけではありません。
```
- この箇条書きのラベル名(* **Orderer**:など)は、実際の設定ファイル中でも利用される表記であるため、英語表記のままにするか、あるいはカッコ書きで残しておいたほうが親切かと思います。
- このラベル(Orderer)については、訳注で「Ordererのケーパビリティ」と「オーダリングサービスのケーパビリティ」が表記揺れもしているようですので、原文を尊重してOrdererに統一するのがよいかと思いました。
- また、各種ケーパビリティは、アプリケーション・ケーパビリティに倣って、中点区切り(あるいは区切りなしでもよいかもしれません)に統一するのがよいかと思います。(お手数ですが同件の確認もお願いします。)

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +* **アプリケーション**: これらのケーパビリティは、ピア専用のタスクと処理を制御します。オーダリングサービスの管理は、ピア組織間のトランザクションの性質を決定する役割を持たないため、このケーパビリティ・レベルの変更は、ピア組織間に限定されます。たとえば、プライベート・データは、v1.2(またはそれ以降)のアプリケーション・グループ・ケーパビリティが有効になっているチャネルでのみ有効にできま
```suggestion
* **アプリケーション (Application) **: これらのケーパビリティは、ピア専用のタスクと処理を制御します。オーダリングサービスの管理者は、ピア組織間のトランザクションの性質を決定する役割を持たないため、このケーパビリティ・レベルの変更は、ピア組織間に限定されます。たとえば、プライベートデータは、v1.2(またはそれ以降)のアプリケーション・グループ・ケーパビリティが有効になっているチャネルでのみ有効にできます。プライベートデータの場合、チャネル管理やオーダリングサービスによるトランザクションの処理方法を変更する必要がないため、これが唯一有効にしなければいけないケーパビリティとなります。
```

- Private dataは中点なくプライベートデータと訳しているようです。(Glossary参照)
- 最後の一文はシンプルになるように修正してみました。

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +* **チャネル**: このグループには、ピア組織とオーダリングサービスが**共同で管理する**タスクが含まれます。たとえば、ピア組織によって開始され、オーダリングサービスによって調整されたチャネル構成の更新が処理されるレベルを定義するケーパビリティです。実用的なレベルでは、**このグループ化は、チャネル内のすべてのバイナリの最小レベルを定義します。これは、オーダリングサービスとピアの両方が、ケ
```suggestion
* **チャネル (Channel) **: このグループには、ピア組織とオーダリングサービスが**共同で管理する**タスクが含まれます。たとえば、ピア組織によって開始されオーダリングサービスによってオーケストレーションされるチャネル構成の更新が処理されるレベルを定義するケーパビリティです。実用的なレベルでは、**このグループは、チャネル内のすべてのバイナリの最小レベルを定義します。これは、オーダリングサービスとピアの両方が、ケーパビリティを処理するために、少なくともこのケーパビリティに対応するバイナリ・レベルでなければならないためです**。
```
- Orchestrateは調整するというと若干違和感がある気がしたので、無理に英訳しなくてもよいかと思いました。

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +チャネルの**オーダリングサービス**と**チャネル**ケーパビリティは、デフォルトではオーダリングシステムチャネルから継承されます。このチャネルの変更は、オーダリングサービス管理者だけの権限です。そのため、ピア組織は、ピアをチャネルに参加させる前に、チャネルのジェネシスブロックを検査する必要があります。チャネルケーパビリティは、(コンソーシアムのメンバーシップと同様に)オーダリングシステムチャ
```suggestion
チャネルの**Orderer**と**チャネル**ケーパビリティは、デフォルトではオーダリングシステムチャネルから継承されます。このチャネルの変更は、オーダリングサービス管理者だけの権限です。そのため、ピア組織は、ピアをチャネルに参加させる前に、チャネルのジェネシスブロックを検査する必要があります。チャネルケーパビリティは、(コンソーシアムのメンバーシップと同様に)オーダリングシステムチャネルのOrdererによって管理されますが、一般的に、オーダリングサービス管理者は、コンソーシアムの準備ができたときにのみチャネルケーパビリティがアップグレードされるように、コンソーシアムの管理者と調整します。
```

2020-09-29 04:59 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +現在有効なオーダリングサービス、アプリケーション、およびチャネルのケーパビリティの詳細については、「Capabilities」セクションにリストされている[sample `configtx.yaml` file](http://github.com/hyperledger/fabric/blob/{BRANCH}/sampleconfig/configtx.yaml)を参照してください。
```suggestion
現在有効なOrderer、アプリケーション、およびチャネル・ケーパビリティの詳細については、「Capabilities」セクションにリストされている[sample `configtx.yaml` file](http://github.com/hyperledger/fabric/blob/{BRANCH}/sampleconfig/configtx.yaml)を参照してください。
```

2020-09-29 05:01 UTC, satota2 commented
翻訳投稿ありがとうございます。

- 上記の通り、いくつかコメントさせて頂きましたのでご確認お願いします (同件の指摘は割愛しておりますので、再投稿前に同件チェックもしていただけると幸いです)。

- 細かいですが、コミットメッセージのjapaneseの先頭は大文字のJapaneseにしたほうがよいかと思います。

- また、今回のパッチに関係のないファイル「docs/locale/ja_JP/source/advice_for_writers.md」
の更新がコミットに含まれるようですので、こちらの削除もお願いします。

お手数ですが、アップデートお願いいたします。

2020-10-08 08:33 UTC, Skurimura commented
@satota2 レビューありがとうございました。ご指摘頂いた点を修正いたしました。

2020-10-09 19:36 UTC, satota2 requested changes
@Skurimura 
修正ありがとうございます。

何か所か表記ゆれが残っていたようなので、Suggested changeを使ってコメントさせて頂きました。確認並びに修正をお願いします。
  - 特にケーパビリティ(アプリケーションケーパビリティなど)に関しては、中点の有無、カタカナor英語の表記ゆれが残っているようです。どう統一するかは悩ましいですが、他の文書ではカタカナに訳しているようなので、一旦、カタカナで統一するのではいかがでしょうか。
ただし、このラベル名自体は設定ファイルでも使われるため、この見出しのみかっこ書きで英語表記も残しています。

また無関係のファイル`docs/locale/ja_JP/source/advice_for_writers.md`が削除されてしまっているようなので、ファイルそのものを削除するのではなく、削除操作自体をコミットから取り除いていただけますでしょうか。やり方は色々あるかと思いますが例えば以下でしょうか。
```
git checkout HEAD^ -- docs/locale/ja_JP/source/advice_for_writers.md
git add docs/locale/ja_JP/source/advice_for_writers.md
git commit --amend
```

最後に、CIが失敗しているのは、最新のrelease-2.2から分岐していないことが原因かもしれませんので、次のパッチ投稿前にはrebaseをお願いいたします。

以上です。お手数ですが、上記の対応をよろしくお願いいたします。

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +そのために、Fabricは「ケーパビリティ(capabilities)」と呼ばれるレベルを定義します。これらのケーパビリティは、各チャネルの設定で定義され、動作が一貫した結果を生成するレベルを定義することによって、決定性を保証します。これらのケーパビリティには、ノード・バイナリバージョンと密接に関連したバージョンがあります。ケーパビリティにより、異なるバージョンレベルで実行されているノードは、特
```suggestion
そのために、Fabricは「ケーパビリティ(capabilities)」と呼ばれるレベルを定義します。これらのケーパビリティは、各チャネルの設定で定義され、動作が一貫した結果を生成するレベルを定義することによって、決定性を保証します。これらのケーパビリティには、ノードのバイナリバージョンと密接に関連したバージョンがあります。ケーパビリティにより、異なるバージョンレベルで実行されているノードは、特定のブロックの高さでのチャネル設定を前提として、互換性のある一貫した方法で動作することができます。また、特定のタスクを行うための管理領域ごとに定義されたケーパビリティが、設定ツリーの多くの部分に存在することもわかります。
```
- ノード・バイナリバージョンは「の」で区切ったほうが自然かと思います。

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +* **Orderer**: これらのケーパビリティは、オーダリングサービス専用のタスクと処理を制御します。これらのケーパビリティには、トランザクションやピアに影響を与えるプロセスが含まれていないため、これらのケーパビリティの更新は、オーダリングサービスの管理者に委ねられています。(ピアはOrderer・ケーパビリティを理解する必要がないため、Orderer・ケーパビリティが何に更新されてもクラ
```suggestion
* **Orderer**: これらのケーパビリティは、オーダリングサービス専用のタスクと処理を制御します。これらのケーパビリティには、トランザクションやピアに影響を与えるプロセスが含まれていないため、これらのケーパビリティの更新は、オーダリングサービスの管理者に委ねられています。(ピアはOrdererケーパビリティを理解する必要がないため、Ordererケーパビリティが何に更新されてもクラッシュしません)。ただし、**チャネル**のセクションで説明するように、これは、v1.1のオーダリングノードがv1.4.2より低いケーパビリティレベルのすべてのチャネルで機能することを意味するわけではありません。
```

- 表記ゆれの統一:  ケーパビリティ・レベル、XXX・ケーパビリティから中点を除きました。

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +* **Application**: これらのケーパビリティは、ピア専用のタスクと処理を制御します。オーダリングサービスの管理者は、ピア組織間のトランザクションの性質を決定する役割を持たないため、このケーパビリティレベルの変更は、ピア組織間に限定されます。たとえば、プライベートデータは、v1.2(またはそれ以降)のアプリケーション・グループ・ケーパビリティが有効になっているチャネルでのみ有効にで
```suggestion
* **アプリケーション (Application)**: これらのケーパビリティは、ピア専用のタスクと処理を制御します。オーダリングサービスの管理者は、ピア組織間のトランザクションの性質を決定する役割を持たないため、このケーパビリティレベルの変更は、ピア組織間に限定されます。たとえば、プライベートデータは、v1.2(またはそれ以降)のアプリケーション・グループ・ケーパビリティが有効になっているチャネルでのみ有効にできます。プライベートデータの場合、チャネル管理やオーダリングサービスによるトランザクションの処理方法を変更する必要がないため、これが唯一有効にしなければいけないケーパビリティとなります。
```

- 表記ゆれの統一: アプリケーションケーパビリティとApplicationケーパビリティの表記ゆれが残っているようです。
  - どちらに統一するかは悩ましいですが、他の文書ではアプリケーションケーパビリティとカタカナに訳しているようなので、一旦、カタカナで統一するのではいかがでしょうか。
  - ただし、このラベル名自体は設定ファイルでも使われるため、この見出しのみかっこ書きで英語表記も残しています。

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +* **Channel**: このグループには、ピア組織とオーダリングサービスが**共同で管理する**タスクが含まれます。たとえば、ピア組織によって開始されオーダリングサービスによってオーケストレーションされるチャネル設定の更新が処理されるレベルを定義するケーパビリティです。実用的なレベルでは、**このグループ化は、チャネル内のすべてのバイナリの最小レベルを定義します。これは、オーダリングサービ
```suggestion
* **チャネル (Channel)**: このグループには、ピア組織とオーダリングサービスが**共同で管理する**タスクが含まれます。たとえば、ピア組織によって開始されオーダリングサービスによってオーケストレーションされるチャネル設定の更新が処理されるレベルを定義するケーパビリティです。実用的なレベルでは、**このグループは、チャネル内のすべてのバイナリの最小レベルを定義します。これは、オーダリングサービスとピアの両方が、ケーパビリティを処理するために、少なくともこのケーパビリティに対応するバイナリ・レベルでなければならないためです**。
```

- 表記ゆれの統一: チャネルケーパビリティとChannelケーパビリティ。
    - 統一方針はアプリケーションケーパビリティと同様です。

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +チャネルの**Orderer**と**Channel**ケーパビリティは、デフォルトではオーダリングシステムチャネルから継承されます。このチャネルの変更は、オーダリングサービス管理者だけの権限です。そのため、ピア組織は、ピアをチャネルに参加させる前に、チャネルのジェネシスブロックを検査する必要があります。チャネルケーパビリティは、(コンソーシアムのメンバーシップと同様に)オーダリングシステムチャ
```suggestion
チャネルの**Orderer**ケーパビリティと**チャネル**ケーパビリティは、デフォルトではオーダリングシステムチャネルから継承されます。このチャネルの変更は、オーダリングサービス管理者だけの権限です。そのため、ピア組織は、ピアをチャネルに参加させる前に、チャネルのジェネシスブロックを検査する必要があります。チャネルケーパビリティは、(コンソーシアムのメンバーシップと同様に)オーダリングシステムチャネルのOrdererによって管理されますが、一般的に、オーダリングサービス管理者は、コンソーシアムの準備ができたときにのみチャネルケーパビリティがアップグレードされるように、コンソーシアムの管理者と調整します。
```
- 表記ゆれの統一。

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +オーダリングシステムチャネルは**Application**ケーパビリティを定義しないため、チャネルのジェネシスブロックを作成するときに、このケーパビリティをチャネルプロファイルで指定する必要があります。
```suggestion
オーダリングシステムチャネルは**アプリケーション**ケーパビリティを定義しないため、チャネルのジェネシスブロックを作成するときに、このケーパビリティをチャネルプロファイルで指定する必要があります。
```

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +現在有効なOrderer、アプリケーション、およびチャネル・ケーパビリティの詳細については、「Capabilities」セクションにリストされている[sample `configtx.yaml` file](http://github.com/hyperledger/fabric/blob/{BRANCH}/sampleconfig/configtx.yaml)を参照してください。
```suggestion
現在有効なOrderer、アプリケーション、およびチャネルケーパビリティの詳細については、「Capabilities」セクションにリストされている[sample `configtx.yaml` file](http://github.com/hyperledger/fabric/blob/{BRANCH}/sampleconfig/configtx.yaml)を参照してください。
```

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +  ピアがチャネルに参加すると、台帳内のすべてのブロックが順番に読み取られます。これは、チャネルのジェネシスブロックから始まり、トランザクションブロックおよびそれ以降のすべてのコンフィグレーションブロックにわたって続きます。ピアなどのノードが、認識できないケーパビリティの更新を含むブロックを読み取ろうとした場合(たとえば、v1.4.xピアがv2.0アプリケーション・ケーパビリティを含むブロックを
```suggestion
  ピアがチャネルに参加すると、台帳内のすべてのブロックが順番に読み取られます。これは、チャネルのジェネシスブロックから始まり、トランザクションブロックおよびそれ以降のすべてのコンフィグレーションブロックにわたって続きます。ピアなどのノードが、認識できないケーパビリティの更新を含むブロックを読み取ろうとした場合(たとえば、v1.4.xピアがv2.0アプリケーションケーパビリティを含むブロックを読み取ろうとした場合)、 **ピアはクラッシュします**。v1.4.xピアはこの時点を過ぎてもトランザクションの検証やコミットを試行しないため、このクラッシュ動作は意図的なものです。チャネルに参加する前に、**ノードが、そのノードに関連するチャネル設定で指定されたケーパビリティのFabricバージョン(バイナリ)レベル以上であることを確認してください**。どのケーパビリティがどのノードに関連するかについては、後で説明します。といっても、ユーザーはノードがクラッシュすることを望んでいないため、ケーパビリティを更新する前に、すべてのノードを必要なレベル(できれば最新リリース)に更新することを強くお勧めします。これは、**常に**最新のバイナリおよびケーパビリティレベルにするというデフォルトのFabricの推奨事項に沿っています。
```

2020-10-09 19:36 UTC, satota2 commented on docs/locale/ja_JP/source/capabilities_concept.md
> +  新しいケーパビリティを確立する必要性は、ケースバイケースで判断され、主に新しい機能と古いバイナリバージョンの後方互換性に依存します。例えば、v1.4.1でRaftオーダリングサービスを追加した時も、トランザクションやオーダリングサービス機能の処理方法は変わらないので、新しいケーパビリティを確立する必要はありませんでした。一方で [Private Data](./private-data/pr
```suggestion
  新しいケーパビリティを確立する必要性は、ケースバイケースで判断され、主に新しい機能と古いバイナリバージョンの後方互換性に依存します。例えば、v1.4.1でRaftオーダリングサービスを追加した時も、トランザクションやオーダリングサービス機能の処理方法は変わらないので、新しいケーパビリティを確立する必要はありませんでした。一方で [Private Data](./private-data/private-data.html)はv1.2より前のピアでは処理できず、v1.2のケーパビリティレベルを確立する必要がありました。すべてのリリースにトランザクションの処理方法を変更する新機能(またはバグ修正)が含まれているわけではないため、特定のリリース(v1.4など)では新しいケーパビリティは必要ありませんが、特定のレベル(v1.2やv1.3など)でのみ新しいケーパビリティが必要なリリースもあります。ケーパビリティの「レベル」と、それらのケーパビリティが設定ツリーのどこにあるかについては、後ほど説明します。
```

2020-10-29 18:24 UTC, Skurimura commented
@satota2 
対応遅れてしまい申し訳ありません。ご確認いただきありがとうございました。
ご指摘いただいた翻訳文ついては修正したのですが、CIのチェックを通すことができていません。
お手数おかけし申し訳ありませんが、対応方法についてご教授いただけないでしょうか。

2020-10-29 23:45 UTC, satota2 commented
@Skurimura 修正ありがとうございます。

> CIのチェックを通すことができていません。
> お手数おかけし申し訳ありませんが、対応方法についてご教授いただけないでしょうか。

CIが失敗しているのは、最新のrelease-2.2から分岐していないことが原因かもしれませんので、rebaseをしたうえで、パッチの再投稿を試してみて頂けないででしょうか。やり方は色々あるかと思いますが例えば以下でしょうか。おそらく大丈夫かと思いますが、ローカルにごみなどがあると、コンフリクトなど発生するかもしれませんのでご留意ください。

```bash
git checkout release-2.2
git pull https://github.com/hyperledger/fabric-docs-i18n.git release-2.2
git checkout <YOUR_BRANCH> #おそらくはrelease-2.2_capabilities_conceptでしょうか。
git rebase release-2.2
```

2020-10-30 09:21 UTC, Skurimura commented
@satota2 
ありがとうございます、大変助かります。
コミットしましたが、余計なファイルを含めてしまったので再度対応します。

2020-11-05 12:03 UTC, Skurimura commented
@satota2 余分なファイルを削除し再投稿しました。ご確認お願いいたします。

2020-11-05 18:36 UTC, satota2 approved these changes

2020-11-05 18:37 UTC, merged

2020-11-05 18:38 UTC, satota2 commented
@Skurimura 翻訳ありがとうございました。