[ja_JP] Translate source/prereqs.rst into Japanese
hyperledger/fabric-docs-i18n pull request #229
Opened 2020-09-25 23:33 UTC by satota2

This patch translates source/prereqs.rst into Japanese.

Solves #196

2020-09-28 12:39 UTC, Naoya-Horiguchi requested changes
翻訳ありがとうございました。一点だけ簡単なコメントがあります。お手数ですがアップデートをよろしくお願いいたします。

2020-09-28 12:39 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/prereqs.rst
> +GitとDockerToolboxに付属している ``curl`` コマンドは古く、
```suggestion
GitとDocker Toolboxに付属している ``curl`` コマンドは古く、
```
細かいですが...

2020-09-28 17:00 UTC, satota2 commented
@Naoya-Horiguchi レビューありがとうございます。

パッチを更新いたしました。差分は以下の通りです。
https://github.com/hyperledger/fabric-docs-i18n/compare/90c6631246b3a2cb77e8fd6568f40aa4c870c392..ab54251e6b0de19e52c71c877a9dd7745e1d5b70

お手数ですがご確認よろしくお願いします。

2020-09-29 00:38 UTC, Naoya-Horiguchi approved these changes
ありがとうございました。

2020-09-29 00:38 UTC, merged