Prerequisites Translation
hyperledger/fabric-docs-i18n pull request #235
Opened 2020-10-06 07:33 UTC by jdo-commiter

2020-10-06 15:10 UTC, camohe90 requested changes, later dismissed
En este PR esta perfecto el archivo docs/locale/es/source/prereqs.rst

Pero teniendo en cuenta la el PR 234 donde modificaste el archivo docs/locale/es/source/tutorials.rst y las sugerencias que te hice en ese PR, creo que se deberia dejar el PR 235 solo para el archivo de prerequisitos

2021-03-05 20:39 UTC, ryjones approved these changes

2021-03-10 19:36 UTC, ryjones commented
@camohe90 could this be merged and edited later?

2021-03-10 20:03 UTC, camohe90 commented
@ryjones Sure,  excuse me for the late reply

2021-03-11 01:41 UTC, merged