[ja_JP]Translate "private-data/private-data.md" into Japanese(#107)
hyperledger/fabric-docs-i18n pull request #240
Opened 2020-10-08 10:50 UTC by Skurimura

This patch translates private-data/private-data.md into Japanese(#107)

2020-10-09 18:18 UTC, shimos requested changes
翻訳ありがとうございます。いくつか気になる点をコメントしましたので、確認をお願いいたします。
また、CI(check)が通っていないのは、最新のrelease-2.2から分岐していないためと思われますので、次にpushされるときは、最新のものにrebaseした上でお願いいたします。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +これが、Fabricが**プライベートデータコレクション**を提供する理由です。プライベートデータコレクションにより、新たにチャネルを作成する必要なく、チャネル内の組織のサブセットに、プライベートデータの承認、コミット、あるいはクエリーを行わせることができるのです。
```suggestion
これが、Fabricが**プライベートデータコレクション**を提供する理由です。プライベートデータコレクションにより、新たにチャネルを作成する必要なく、チャネル内の組織のサブセットに、プライベートデータのエンドースメント、コミット、あるいはクエリーを行わせることができるのです。
```
endorse(ment)が、下記のほとんどの箇所で「承認」となっているようです。Glossaryにあわせて、エンドースする・エンドースメントに統一したほうがよいと思います。

cf. https://hyperledger-fabric.readthedocs.io/ja/latest/glossary.html#endorsement

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +1. **実際のプライベートデータ**。そのデータを見る権限のある組織にのみ、[ゴシッププロトコル](../gossip.html)でのpeer-to-peer通信でデータが送信されます。このデータは、許可された組織のピア内のプライベートステートデータベースに保管され、これら許可されたピア上のチェーンコードからアクセスすることができます。オーダリングサービスはこれら許可されたピアには含まれず、プ
```suggestion
1. **実際のプライベートデータ**。そのデータを見る権限のある組織にのみ、[ゴシッププロトコル](../gossip.html)でのpeer-to-peer通信でデータが送信されます。このデータは、許可された組織のピア内のプライベートステートデータベースに保管され、これら許可されたピア上のチェーンコードからアクセスすることができます。オーダリングサービスはここでは関与しないので、プライベートデータを見ることはありません。ゴシッププロトコルにより、許可された組織間のpeer-to-peer通信でプライベートデータが配布されるので、組織間の通信を開始するため、チャネル内にアンカーピアを設定し、各ピアにCORE_PEER_GOSSIP_EXTERNALENDPOINTを設定する必要があることに注意してください。
```
大意は同じですが若干ニュアンスが異なる気がしますので、原文に近くするとこういう感じでしょうか。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +2. **該当データのハッシュ**。このハッシュ値は、承認され、順序付けされ、チャネル上の各ピアの台帳に書き込まれます。ハッシュはトランザクションの証拠となり、ステートの検証に使われるとともに、監査目的で利用することもできます。
```suggestion
2. **そのデータのハッシュ**。このハッシュ値は、エンドースされ、順序付けされ、チャネル上の各ピアの台帳に書き込まれます。ハッシュはトランザクションの証拠となり、ステートの検証に使われるとともに、監査目的で利用することもできます。
```
もしくは「当該データ」でしょうか。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +係争に巻き込まれたり、資産を第3者に譲渡したいと行った場合に、コレクションのメンバーはプライベートデータを他のメンバーに共有するようにすることもできます。その場合、第三者がプライベートデータのハッシュを計算し、特定の時点でのコレクションのメンバー間で共有しているステートを証明するために、それがチャネル台帳のステートと一致するかを確認することができます。
```suggestion
係争に巻き込まれたり、資産を第三者に譲渡したいといった場合に、コレクションのメンバーはプライベートデータを他のメンバーに共有するようにすることもできます。その場合、第三者がプライベートデータのハッシュを計算し、それがチャネル台帳のステートと一致するかを確認して、コレクションのメンバー間で共有しているステートが特定の時点で存在していたことを証明することができます。
```
proving以下は、目的というよりも結果と考えた方が通りがいいような気がします。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +ケースによっては、単一の組織のみが所有するコレクションのセットを定義することもできます。例えば、ある組織が自身のコレクションにプライベートデータを記録しておいて、後ほどチャネル内の他のメンバーに共有、チェーンコードトランザクションから参照してもらうということもできます。この具体的な例については、下のSharing private dataのトピックをご参照ください。
```suggestion
ケースによっては、単一の組織のみからなるコレクションのセットを定義することもできます。例えば、ある組織が自身のコレクションにプライベートデータを記録しておいて、後ほどチャネル内の他のメンバーに共有、チェーンコードトランザクションから参照してもらうということもできます。この具体的な例については、下のSharing private dataのトピックをご参照ください。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +* 取引(および台帳)全体の秘匿性を、チャネルのメンバーとなっている組織群の間で確保必要がある場合には、**チャネル**を使用してください。
```suggestion
* 取引(および台帳)全体の秘匿性を、チャネルのメンバーとなっている組織群の間で確保する必要がある場合には、**チャネル**を使用してください。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +**Distributor**は、**Retailer**よりも低価格を請求するために、**Wholesaler**との別のプライベートデータリレーションシップを持ちたい場合もあります。
```suggestion
**Distributor**は、**Retailer**よりも低価格を請求するために、**Wholesaler**との別のプライベートデータの関係を持ちたい場合もあります。
```
ここのrelationshipは、Fabricの用語ではないので、単純に「関係」で統一した方がよいと思います。(以下複数個所ありますが省略します)

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +プライベートデータコレクションがチェーンコードから参照される時には、トランザクションの承認要求、承認、および台帳へのコミットという一連のトランザクションフローは、プライベートデータの機密性の保護のため通常とやや異なります。
```suggestion
プライベートデータコレクションがチェーンコードから参照される時には、トランザクションの提案、エンドースメント、および台帳へのコミットという一連のトランザクションフローは、プライベートデータの機密性の保護のため通常とやや異なります。
```
cf. https://hyperledger-fabric.readthedocs.io/ja/latest/glossary.html#proposal

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +1. クライアントアプリケーションは、コレクションのアクセス許可のある組織内のエンドーシングピアに、チェーンコードの機能(プライベートデータの読み書き)を呼び出すための承認要求を発行します。プライベートデータ、あるいはプライベートデータをチェーンコード内で生成するために使われるデータは承認要求の`transient`データにて送信されます。
```suggestion
1. クライアントアプリケーションは、コレクションのアクセス許可のある組織内のエンドーシングピアに、チェーンコードの関数(プライベートデータの読み書き)を呼び出すための提案要求を発行します。プライベートデータ、あるいはプライベートデータをチェーンコード内で生成するために使われるデータは提案の`transient`フィールドにて送信されます。
```
cf. https://hyperledger-fabric.readthedocs.io/ja/latest/glossary.html#invoke

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +3. エンドーシングピアは承認結果をクライアントに返します。承認結果には、パブリックデータを含む承認時のread/writeセット、およびプライベートデータのキーとバリューのハッシュ値を含みます。*プライベートデータはクライアントに返されません*。プライベートデータを伴う承認(エンドースメント)の振る舞いのより詳しい情報については[こちら](../private-data-arch.html#e
```suggestion
3. エンドーシングピアは提案応答をクライアントに返します。提案応答には、パブリックデータを含むエンドースメント時のread/writeセット、およびプライベートデータのキーと値のハッシュ値を含みます。*プライベートデータはクライアントに返されません*。プライベートデータを伴うエンドースメントの振る舞いのより詳しい情報については[こちら](../private-data-arch.html#endorsement)をクリックください。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +4. クライアントアプリケーションは、トランザクション（プライベートデータのハッシュと承認結果を含む）をオーダリングサービスに送信します。プライベートデータのハッシュ付きのトランザクションは、通常どおりブロックに含まれます。プライベートデータハッシュを持つブロックは、すべてのピアに配布されます。このようにして、チャネル上のすべてのピアは、実際のプライベートデータを知らなくても、一貫した方法でプラ
```suggestion
4. クライアントアプリケーションは、トランザクション（プライベートデータのハッシュ付きの提案応答を含む）をオーダリングサービスに送信します。プライベートデータのハッシュ付きのトランザクションは、通常どおりブロックに含まれます。プライベートデータハッシュを持つブロックは、すべてのピアに配布されます。このようにして、チャネル上のすべてのピアは、実際のプライベートデータを知らなくても、一貫した方法でプライベートデータのハッシュを使用してトランザクションを検証できます。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +5. ブロックのコミット時には、許可されたピアはコレクションポリシーを使用してプライベートデータへのアクセス権限があるかどうかを判断します。もし権限があれば、そのピアは最初に、チェーンコードの承認時にプライベートデータをすでに受け取っているかを判断するために、ローカルの`transient data store`を確認します。もし権限がなければ、ピアは他の許可されたピアからプライベートデータを取
```suggestion
5. ブロックのコミット時には、許可されたピアはコレクションポリシーを使用してプライベートデータへのアクセス権限があるかどうかを判断します。もし権限があれば、そのピアは最初に、チェーンコードの承認時にプライベートデータをすでに受け取っているかを判断するために、ローカルの`transient data store`を確認します。もし受け取っていなければ、ピアは他の許可されたピアからプライベートデータを取得しようとします。その後、ピアはパブリックブロックの中のハッシュとの比較でプライベートデータを検証し、トランザクションとブロックをコミットします。検証/コミット時には、プライベードデータは、プライベートステートデータベースのコピーとプライベートライトセットストレージに移されます。その後、プライベートデータは、`transient data store`から削除されます。
```

意味的にも、if notは、権限があるうえで if they have not received the private data のことだと思います。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +プライベートデータコレクションの設計においては、多数の多面的なコレクションを定義するというオーバーヘッドなしに、プライベートデータを共有し転送する複数のパターンが利用可能です。チェーンコードアプリケーションが利用可能ないくつかの共有パターンを挙げます:
```suggestion
プライベートデータコレクションの設計においては、多数の複数組織間のコレクションを定義するというオーバーヘッドなしに、プライベートデータを共有し転送する複数のパターンが利用可能です。チェーンコードアプリケーションが利用可能ないくつかの共有パターンを挙げます:
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +  チェーンコードにアクセス制御を実装して、コレクション内のプライベートデータを照会できるクライアントを指定できます。例えば、プライベートデータコレクションキーまたはキーの範囲のアクセスコントロールリストを保存してから、(GetCreator()チェーンコードAPIまたはCIDライブラリAPIのGetID()またはGetMSPID()を使用して)クライアント送信者の資格情報をチェーンコード内で取
```suggestion
  チェーンコードにアクセス制御を実装して、コレクション内のプライベートデータをクエリできるクライアントを指定できます。例えば、プライベートデータコレクションキーまたはキーの範囲のアクセスコントロールリストを保存してから、(GetCreator()チェーンコードAPIまたはCIDライブラリAPIのGetID()またはGetMSPID()を使用して)クライアント送信者の資格情報をチェーンコード内で取得し、プライベートデータをクライアントに返す前にアクセス権があるかどうかを確認します。同様に、パスフレーズをチェーンコードに渡すようにクライアントに要求することもできます。プライベートデータにアクセスするには、パスフレーズがキーレベルで保存されているパスフレーズと一致している必要があります。このパターンは、公開されているステートデータへのクライアントからのアクセスを制限するためにも使用できます。
```
他の翻訳でも、「クエリ」としている例が多いようです。

cf. https://hyperledger-fabric.readthedocs.io/ja/latest/glossary.html#invoke

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +  前出のパターンの変形により、特定のトランザクションに対する取引者の漏洩を排除することもできます。例えば、買い手は自分のコレクションで購入することに同意することを示し、後続のトランザクションにおいて、売り手は自分のプライベートデータコレクションで購入者のプライベートデータを参照します。ハッシュ化した参照付きのトランザクションの証明は、オンチェーンに記録され、買い手と売り手だけが自分達が取引主体
```suggestion
  前出のパターンの変形により、特定のトランザクションに対する取引者の漏洩を排除することもできます。例えば、買い手は自分のコレクションで購入することに同意することを示し、後続のトランザクションにおいて、売り手は、買い手自身のプライベートデータコレクションで買い手のプライベートデータを参照します。ハッシュ化した参照付きのトランザクションの証明は、オンチェーンに記録され、買い手と売り手だけが自分達が取引主体であることを知っていることになります。しかし、ハッシュを検証できる別の当事者との後続のトランザクションなどで、知る必要が生じた場合には、事前イメージを明らかにすることができます。
```

このパターンの意味が正直わかりにくいのですが、売り手のプライベートデータコレクションから買い手のプライベートデータが見られることは意味が通らないので、売り手が買い手のプライベートデータのハッシュ値を確認するという意味で「参照」と言っているのではないかと思います。
すなわち、"their own collection"が(この場合のtheirは性別を特定しない三人称単数として使わているとして)、"the buyer's own collection"という解釈です。

別の解釈として、"their"が"the buyer and the seller"という意味と解釈できなくはないですが、そうすると取引する相手を秘匿するという目的からは意味が通らなくなりそうです。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +上記のパターンと組み合わせると、プライベートデータを使用したトランザクションは、通常のチャネルのステートデータと同様に、具体的には次の条件に紐付けることできます：
```suggestion
上記のパターンに加えて、プライベートデータを使用したトランザクションは、通常のチャネルのステートデータと同様に、具体的には次のような条件に紐付けることできます：
```

以下二つは、例としてとらえたほうがいい気がします。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +  プライベートデータ値に所有権資格証明を含めると、後続のトランザクションで、送信者がデータを共有または転送する所有者権限を持っていることを確認できます。この場合、チェーンコードは送信者の資格証明を取得し(例えば、GetCreator()チェーンコードAPIまたはCIDライブラリーAPIであるGetID()またはGetMSPID()を使用して)、それをチェーンコードに渡される他のプライベートデー
```suggestion
  プライベートデータ値に所有権資格情報を含めると、後続のトランザクションで、送信者がデータを共有または転送する所有者権限を持っていることを確認できます。この場合、チェーンコードは送信者の資格情報を取得し(例えば、GetCreator()チェーンコードAPIまたはCIDライブラリーAPIであるGetID()またはGetMSPID()を使用して)、それをチェーンコードに渡される他のプライベートデータと組み合わせてハッシュ化し、トランザクションを進める前にGetPrivateDataHash()を使用してオンチェーンのハッシュと一致することを確認します。
```
cf. https://hyperledger-fabric.readthedocs.io/ja/latest/glossary.html#membership-service-provider

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +  また、通常のチャネルのステートデータと同様に、ステートベースのエンドースメントを使用すると、SetPrivateDataValidationParameter()チェーンコードAPIを使用して、プライベートデータを共有または転送するトランザクションをどの組織が承認する必要があるかを指定できます。たとえば、所有者の組織ピア、保管者の組織ピア、または他の第3者のみがこのようなトランザクションを承
```suggestion
  また、通常のチャネルのステートデータと同様に、ステートベースのエンドースメントを使用すると、SetPrivateDataValidationParameter()チェーンコードAPIを使用して、プライベートデータを共有または転送するトランザクションをどの組織がエンドースする必要があるかを指定できます。たとえば、所有者の組織ピア、保管者の組織ピア、または他の第3者のみがこのようなトランザクションをエンドースする必要があることを指定できます。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +* 規制機関も各コレクションのメンバーであり、したがってプライベートデータを保管しますが、必ずしもそうである必要はありません。
```suggestion
* 必ずしもそうである必要はありませんが、規制機関も各コレクションのメンバーであり、したがってプライベートデータを保管すると仮定しましょう。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +4. 買い手はチェーンコードを呼び出して、入札の詳細を自身のプライベートデータコレクションに記録します。買い手のピアでチェーンコードが呼び出され、コレクションエンドースメントポリシーによって要求されている場合には、規制当局のピアでチェーンコードが呼び出される可能性があります。
```suggestion
4. 買い手はチェーンコードを呼び出して、入札の詳細を自身のプライベートデータコレクションに記録します。買い手のピアでチェーンコードが呼び出され、コレクションエンドースメントポリシーによって要求されている場合には、規制機関のピアでチェーンコードが呼び出される可能性があります。
```
regulatorに対して表記ゆれがあるようです。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +5. 現在の所有者(売り手)は、チェーンコードを呼び出して資産を販売および譲渡し、プライベートデータの詳細および入札情報を渡します。チェーンコードは、公開鍵のエンドースメントポリシー、ならびに買い手と売り手のプライベートデータコレクションのエンドースメントポリシーを満たすよう、売り手、買い手、および規制当局のピアにて起動します。
```suggestion
5. 現在の所有者(売り手)は、チェーンコードを呼び出して資産を販売および譲渡し、プライベートデータの詳細および入札情報を渡します。チェーンコードは、パブリックなキーのエンドースメントポリシー、ならびに買い手と売り手のプライベートデータコレクションのエンドースメントポリシーを満たすよう、売り手、買い手、および規制機関のピアにて起動します。
```
ここでのpublic keyは、公開鍵ではなく、少し前の文章に出てきたパブリックなステート(public chaincode state)のキーのことを指していると思います。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +6. チェーンコードは、送信クライアントが所有者であることを確認し、売り手のコレクションのハッシュに対してプライベートデータの詳細を確認し、買い手のコレクションのハッシュに対して入札詳細を確認します。次に、チェーンコードは、公開鍵のための提案された更新を書き込み(買い手に所有権を設定し、買い手の組織および規制機関としてエンドースメントポリシーを設定)、購入者のプライベートデータコレクションにプラ
```suggestion
6. チェーンコードは、送信クライアントが所有者であることを確認し、売り手のコレクションのハッシュに対してプライベートデータの詳細を確認し、買い手のコレクションのハッシュに対して入札詳細を確認します。次に、チェーンコードは、パブリックなキーに対する提案された更新を書き込み(買い手に所有権を設定し、買い手の組織および規制機関としてエンドースメントポリシーを設定)、買い手のプライベートデータコレクションにプライベートデータの詳細を書き込み、場合によっては、売り手のコレクションからプライベートデータの詳細を削除します。最終的なエンドースメントの前に、エンドーシングピアは、権限を持つ売り手と規制機関のすべてのピアにプライベートデータが確実に配布されるようにします。
```
buyerに表記ゆれがあるようです。

また、any other...は、そのほかのあらゆる、という意味でないと通らない気がします。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +8. 各ピアのブロック検証ロジックは、エンドースメントポリシーが満たされたこと(買い手、売り手、規制当局のすべてが承認したこと)を一貫して検証し、チェーンコードで読み取られたパブリックおよびプライベートのステートが、チェーンコードの実行後に他のトランザクションによって変更されていないことを検証します。
```suggestion
8. 各ピアのブロック検証ロジックは、エンドースメントポリシーが満たされたこと(買い手、売り手、規制機関のすべてがエンドースしたこと)を一貫して検証し、チェーンコードで読み取られたパブリックおよびプライベートのステートが、チェーンコードの実行後に他のトランザクションによって変更されていないことを検証します。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +9. すべてのピアは、検証チェックを通過したため、トランザクションを有効なものとしてコミットします。売り手のピアおよび規制機関のピアは、エンドースメント認時にプライベートデータを受信していなかった場合、他の承認されたピアからプライベートデータを取得し、そのプライベートデータを自身のプライベートデータのステートデータベースに保持します(プライベートデータがトランザクションのハッシュと一致すると仮定
```suggestion
9. すべてのピアは、検証チェックを通過したため、トランザクションを有効なものとしてコミットします。売り手のピアおよび規制機関のピアは、エンドースメント時にプライベートデータを受信していなかった場合、他の承認されたピアからプライベートデータを取得し、そのプライベートデータを自身のプライベートデータのステートデータベースに保持します(プライベートデータがトランザクションのハッシュと一致すると仮定します)。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +基本的な資産移転シナリオは、他の考慮事項にも拡張することができます。例えば、移転のチェーンコードは、実施前に、支払対引渡の要件を満たすために支払記録が利用可能であることを検証することができたり、銀行が信用状を提出したことを検証することができます。また、取引主が直接ピアを所有する代わりに、ピアを所有している管理組織を通じてトランザクションを実行することもできます。
```suggestion
基本的な資産移転シナリオは、他の考慮事項にも拡張することができます。例えば、移転のチェーンコードは、実行前に、支払対引渡の要件を満たすために支払記録が利用可能であることを検証することができたり、銀行が信用状を提出したことを検証することができます。また、取引者が直接ピアを所有する代わりに、ピアを所有している保管組織を通じてトランザクションを実行することもできます。
```
同じ文章内の他の部分の訳語を合わせたほうがよいかと思います。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +このような場合、プライベートデータは、ピアのブロックチェーンの外部のデータベースに複製されるようになるまで、ピアのプライベートデータベースに存在する必要があります。データは、チェーンコードビジネスプロセス(取引の決済、契約の履行など)が完了するまで、ピア上に存在していればよい場合もあります。
```suggestion
このような場合、いくつかのケースでは、プライベートデータは、ピアのブロックチェーンの外部のデータベースに複製されるようになるまでの間のみ、ピアのプライベートデータベースに存在する必要があります。データは、チェーンコードビジネスプロセス(取引の決済、契約の履行など)が完了するまで、ピア上に存在していればよい場合もあります。
```

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +これらの使用例をサポートするために、設定可能な数のブロックに対してプライベートデータが変更されていない場合は、プライベートデータをパージできます。パージされたプライベートデータは、チェーンコードから照会できません。また、他の要求元ピアからは使用できません。
```suggestion
これらの使用例をサポートするために、設定したブロック数にわたってプライベートデータが変更されていない場合は、プライベートデータをパージできます。パージされたプライベートデータは、チェーンコードから照会できません。また、他の要求元ピアからは使用できません。
```
少しわかりにくい気がしたので、変えてみました。

2020-10-09 18:18 UTC, shimos commented on docs/locale/ja_JP/source/private-data/private-data.md
> +ある組織のグループが、同じチャネル上の他の組織からデータを秘匿する必要がある場合には、データへのアクセスが必要な組織から構成される新しいチャネルを作成することができます。しかし、このようにケースに応じて別のチャネルを作成するのは、追加の管理オーバヘッド(チェーンコードのバージョン、ポリシー、MSPなど）となり、また、全ての参加者にトランザクションを見せつつ、データの一部の秘匿化する必要があるユー
```suggestion
ある組織のグループが、同じチャネル上の他の組織からデータを秘匿する必要がある場合には、データへのアクセスが必要な組織だけから構成される新しいチャネルを作成することができます。しかし、このようにケースに応じて別のチャネルを作成するのは、追加の管理オーバヘッド(チェーンコードのバージョン、ポリシー、MSPなど）となり、また、全ての参加者にトランザクションを見せつつ、データの一部の秘匿化する必要があるユースケースには対応ができなくなります。
```

2020-11-05 12:08 UTC, Skurimura commented
@shimos ご確認いただきありがとうございました。こちら対応遅れてしまい申し訳ありません。ご指摘いただいた点修正いたしましたのでご確認お願いいたします。

2020-11-05 22:13 UTC, shimos approved these changes
@Skurimura 修正ありがとうございました。LGTM

2020-11-05 22:13 UTC, merged