ENG - RUS translation of Hyperledger Fabric Model section
hyperledger/fabric-docs-i18n pull request #244
Opened 2020-10-11 22:58 UTC by denispokrovsky

ENG - RUS translation of Hyperledger Fabric Model section

2020-10-11 23:07 UTC, C0rWin commented
You need to run 

```
git commit --amend --signoff
```

to add signature to your commit.

2020-10-11 23:51 UTC, C0rWin requested changes

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +В этом разделе описываются ключевые черты конструкции, вплетенные в Hyperledger Fabric,
```suggestion
В этом разделе описываются ключевые концепции, используемые в Hyperledger Fabric, 
```

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +которые реализуют задачу создания подробного и кастомизируемого промышленного блокчейн-решения:
```suggestion
с помощью которых реализируется гибко настраиваемое блокчейн решение промышленного уровня : 
```

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +* `Свойства реестра`_ --- Неизменяемый, совместно используемый реестр хранит код
```suggestion
* `Свойства реестра`_ --- Неизменяемый, совместно используемый реестр хранит  
```

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +  истории всех транзакций каждого канала, и включает SQL-подобные возможности запросов
```suggestion
  истории всех транзакций каждого для канала, и включает SQL-подобные возможности запросов 
```

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +* `Приватность`_ --- Каналы и частные хранилища данных могут осуществлять частные и
Вот эта часть по русски вообще не читается, мне кажется нужно перефразировать.

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +  необходимую предприятию.
```suggestion
  необходимую для решений промышленного уровня. 
```

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +Активы могут быть как осязаемыми (пример: недвижимость и оборудование), так и нематериальными
```suggestion
Активы могут быть как материальными (пример: недвижимость и оборудование), так и нематериальными 
```

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +возможность изменять активы посредством транзакций чейн-кода.
```suggestion
возможность изменять активы посредством транзакций чейнкода. 
```

2020-10-11 23:51 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +Активы в Hyperledger Fabric представлены как собрание
```suggestion
Активы в Hyperledger Fabric представлены как композиция 
```

2020-10-12 05:58 UTC, denispokrovsky commented on docs/locale/ru_RU/source/fabric_model.rst
> +  истории всех транзакций каждого канала, и включает SQL-подобные возможности запросов
мне показалось, по смыслу правильнее: "... истории всех транзакций для каждого канала"?

2020-10-12 06:29 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +  истории всех транзакций каждого канала, и включает SQL-подобные возможности запросов
я не буду настаивать на этом конкретном изменении, но мне кажется что "транзакции каждого канала" вернее.

2020-10-12 07:11 UTC, C0rWin requested changes

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +Функции чейнкода исполняются на базе данных текущего состояния реестра и инициируются через предложение транзакции.
```suggestion
Функции чейнкода исполняются на основании текущего состояния реестра и вызываются через предложение транзакции. 
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +Исполнение чейнкода приводит к набору записей "ключ-значение" (набор записи), которые затем могут быть представлены
```suggestion
Исполнение чейнкода приводит к формированию списка записей "ключ-значение" (набор записи), которые затем могут быть посланы
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +в сеть и применены к реестру всеми равноправными узлами сети.
```suggestion
в сеть и привести к изменениям в реестре на всех узлах сети. 
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +Каждая транзакция приводит к набору пар "ключ-значение" для активов, которые затем предоставляются в реестр
```suggestion
Каждая транзакция приводит к набору пар "ключ-значение" для активов, которые затем сохраняются в реестре
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +- Как только транзакция валидирована и представлена, наступает неизменность
```suggestion
- Транзакция становиться неизменной сразу после валидации и сохранения ее в реестре
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +- Транзакции содержат подписи каждого подписывающего узла и предоставляются в службу упорядочения
```suggestion
- Транзакции содержат цифровые подписи каждого подписывающего узла и предоставляются в службу упорядочения
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +- Равноправные узлы валидируют транзакции, исходя из политик подписания и обеспечивают исполнение политик
```suggestion
- Узлы валидируют транзакции, на соответствие с установленными правилам подтверждения транзакций и тем самым гарантируют соответвие этим правилам
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +* `Услуги безопасности и членства`_ --- Разрешительное членство предоставляет
Что такое разрешительное членство, мне кажется это слишком буквальный перевод

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +- Прежде, чем применить блок, проводится проверка версии, чтобы гарантировать неизменность состояний активов за время исполнения чейнкода
```suggestion
- Прежде, чем сохранить блок, и последовательно применить изменения предлагаемые каждой транзакцией, проводится проверка версии ключей, что позволяет разрешить конфликты возникающие при возможных конкурентных изменениях одного и того же ключа разными транзакциями
```

я знаю что это не дословный перевод, но мне кажется это лучше отражает что происходит на самом деле

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +- Каналы содержат копии службы членства :ref:`MSP`, которые позволяют зашифрованным материалам вести происхождение от различных удостоверяющих центров
```suggestion
- Каналы содержат копии службы членства :ref:`MSP`, которые содержат криптографические материалам полученные от различных удостоверяющих центров
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +Hyperledger Fabric применяет неизменяемый реестр для каждого канала в отдельности,
```suggestion
Hyperledger Fabric предоставляет неизменяемый реестр для каждого канала в отдельности, 
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +пары ключ-значение). Реестр существует в масштабе канала - его можно распространить
```suggestion
пары ключ-значение). Реестр существует в контексте канала - его можно распространить
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +используется частное хранение данных, что позволяет хранить данные, логически отделенные от реестра канала, с
```suggestion
используется приватное хранение данных, что позволяет хранить данные, логически отделенные от реестра канала, с
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +имеют идентификацию. Инфраструктура публичного ключа (PKI) используется для генерации криптографических
```suggestion
имеют идентификатор. Инфраструктура публичного ключа (PKI) используется для генерации криптографических 
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +Как итог, как и в более широкой сети, так и на уровне каналов, можно контролировать и управлять доступом к данным.
```suggestion
В результате, как и в более широкой сети, так и на уровне каналов, можно контролировать и управлять доступом к данным.  
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +в полном потоке транзакций, от предложения/выдвижения и подписания до упорядочения, валидации, и предоставления.
```suggestion
в полном потоке транзакций, от предложения/выдвижения и подписания до упорядочения, валидации, и сохранения. 
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +явно соответствуют открытым критериям политик. Эта система сдержек и противовесов
```suggestion
явно соответствуют открытым критериям уставновленных правил. Эта система сдержек и противовесов
```

мне кажется нужно перечитать текст и избавится от использования термина "политик", а вместо него использовать "правила"

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +участников во всех направлениях транзакционного потока. Списки контроля доступа
```suggestion
участников принимающих участие в формировании транзакций. Списки контроля доступа 
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +транщакции проходит через различные архитектурные компоненты. В заключение, консенсус
```suggestion
транзакции проходит через различные архитектурные компоненты. В заключение, консенсус 
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +это не просто согласованный порядок пакета транзакций, а, скорее, всеохватная характеризация, достигаемая
```suggestion
это не просто согласованный порядок пакета транзакций, а общий результат, получаемый
```

2020-10-12 07:11 UTC, C0rWin commented on docs/locale/ru_RU/source/fabric_model.rst
> +от предложения до предоставления.
```suggestion
от формирования до сохранения. 
```

2020-10-12 09:18 UTC, denispokrovsky commented on docs/locale/ru_RU/source/fabric_model.rst
> +* `Услуги безопасности и членства`_ --- Разрешительное членство предоставляет
ну, в русском языке, особенно в юридической практике, такое слово есть - "разрешительный характер", например, но это может быть немного не то. мы подумаем над лучшим переводом.

2020-12-06 00:31 UTC, C0rWin commented
@denispokrovsky you still missing something sign-off from your recent commit and you have Japanese translation included into your pool request, you need to fix it before moving forward.

2020-12-06 01:09 UTC, C0rWin requested changes

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +Блокчейн это журнал транзакций, структурированный как хэш-связанные блоки, в котором каждый блок
```suggestion
Блокчейн это журнал транзакций, сформированный при помощи хэш-связанных блоков, в котором каждый блок
```

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +таким образом эффективно поддерживая режим "разрешена только запись" данных блокчейна.
В оригинале не идет речь о режиме только запись, тут скорее всего про то что данные добавляются и удалить или изменить их не возможно.

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +Вызовы чейнкода исполняют транзакции в данных текущего состояния. Чтобы придать взаимодействиям
```suggestion
Вызовы чейнкода исполняют транзакции на основе значений текущего состояния. Чтобы придать взаимодействиям
```

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +состояний автоматически восстановится (или заново сгенерируется, если нужно) после перезапуска однорангового узла.
Речь идет про то что состояние должно полностью восстановиться прежде чем узел сможет принимать транзакции для обработки.

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +Транзакционный поток
```suggestion
Транзакционный поток
----------------
```

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +Клиент составляет из одобрений так называемую "транзакционную полезную нагрузку" и сообщает их в службу
```suggestion
Клиент компонует из полученных одобрений  итоговую транзакционную и отсылает ее в службу
```

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +упорядочения. Служба упорядочения доставляет очередь транзакций в виде блоков всем одноранговым узлам в канале.
```suggestion
упорядочения. Служба упорядочения группирует транзакции в блоки послче чего доставляет блоки всем одноранговым узлам в канале.
```

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +в сравнении с транзакционной полезной нагрузкой.
Транзакционная полезная нагрузка не отражает смысл transaction payload, так как речь идет о содержимом транзакции.

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +Затем узлы проверяют номер версии в сравнении с "набором записи" транзакции, чтобы обеспечить сохранность
```suggestion
Затем узлы проверяют номер версии в сравнении с "набором записи" транзакции, чтобы обеспечить целостность
```

2020-12-06 01:09 UTC, C0rWin commented on docs/locale/ru_RU/source/ledger.rst
> +данных и защиту от "задвоения". В Hyperledger Fabric встроен контроль параллельного выполнения, посредством
```suggestion
данных и защиту от конкуретного доступа к данным. В Hyperledger Fabric встроен контроль параллельного выполнения, посредством
```

2020-12-08 20:56 UTC, closed without merging