[ja_JP] Key Concepts >> Peers
hyperledger/fabric-docs-i18n pull request #250
Opened 2020-10-18 13:52 UTC by nekia

Signed-off-by: Atsushi Neki <atsushin@fast.au.fujitsu.com>

2020-10-20 00:16 UTC, shimos requested changes
翻訳ありがとうございます。いくつかコメントをしましたので、確認をお願いいたします。

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +ピアをもう少し詳しく見てみましょう。台帳とチェーンコードの両方をピアはホストすることがわかります。より正確には、ピアは実際に台帳の*インスタンス*とチェーンコードの*インスタンス*をホストします。これにより、Fabricネットワークに意図的な冗長性が提供され、単一点障害が回避されます。ブロックチェーンネットワークの分散型および非中央集権型の性質については、このセクションの後半で詳しく説明します。
```suggestion
ピアをもう少し詳しく見てみましょう。台帳とチェーンコードの両方をピアはホストすることがわかります。より正確には、ピアは実際に台帳の*インスタンス*とチェーンコードの*インスタンス*をホストします。これにより、Fabricネットワークに意図的な冗長性が提供され、単一障害点が回避されます。ブロックチェーンネットワークの分散型および非中央集権型の性質については、このセクションの後半で詳しく説明します。
```
[別の翻訳](https://hyperledger-fabric.readthedocs.io/ja/release-2.2/blockchain.html)では、単一障害点としているので統一するのはいかがでしょうか。

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +ピアが台帳にアクセスするチェーンコードをホストせずに台帳インスタンスをホストすることは完全に可能ですが、ピアがこのように構成されることはまれです。大多数のピアには、ピアの台帳インスタンスを照会または更新できるチェーンコードが少なくとも1つインストールされています。なお付随する情報として言及しておくべき情報として、ユーザーが外部アプリケーションで使用するためにチェーンコードをインストールしたかどう
```suggestion
ピアが台帳にアクセスするチェーンコードをホストせずに台帳インスタンスをホストすることは完全に可能ですが、ピアがこのように構成されることはまれです。大多数のピアには、ピアの台帳インスタンスをクエリまたは更新できるチェーンコードが少なくとも1つインストールされています。なお付随する情報として言及しておくべき情報として、ユーザーが外部アプリケーションで使用するためにチェーンコードをインストールしたかどうかにかかわらず、ピアには常に存在する特別な**システムチェーンコード**もあります。これらについては、このトピックでは詳しく説明しません。
```

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +クエリを満たすために必要なすべての情報は、ピアのローカルにある台帳のコピーにあるため、ピアはククエリ結果をただちにアプリケーションに戻すことができます。ピアは、アプリケーションからのクエリに応答するために他のピアと協議することはありません。しかし、アプリケーションは1つ以上のピアに接続してクエリを発行できます。たとえば、複数のピア間で結果をまとめたり、情報が最新ではない可能性がある場合に別のピア
```suggestion
クエリを満たすために必要なすべての情報は、ピアのローカルにある台帳のコピーにあるため、ピアはクエリ結果をただちにアプリケーションに戻すことができます。ピアは、アプリケーションからのクエリに応答するために他のピアと協議することはありません。しかし、アプリケーションは1つ以上のピアに接続してクエリを発行できます。たとえば、複数のピア間で結果をまとめたり、情報が最新ではない可能性がある場合に別のピアから最新の結果を取得したりできます。この図では、台帳へのクエリが単純な3ステップのプロセスであることがわかります。
```

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +更新トランザクションは、クエリトランザクションと同じ方法で開始されますが、2つの追加ステップがあります。台帳更新アプリケーションはチェーンコードを起動するためにピアにも接続しますが、台帳クエリアプリケーションとは異なり、他のピアが最初に変更に同意する必要があるため(**コンセンサス**と呼ばれるプロセス)、個々のピアはこの時点で台帳更新を実行できません。そのため、ピアは、**提案された**更新を
```suggestion
更新トランザクションは、クエリトランザクションと同じ方法で開始されますが、2つの追加ステップがあります。台帳更新アプリケーションはチェーンコードを起動するためにピアにも接続しますが、台帳クエリアプリケーションとは異なり、他のピアが最初に変更に同意する必要があるため(**合意形成**と呼ばれるプロセス)、個々のピアはこの時点で台帳更新を実行できません。そのため、ピアは、**提案された**更新をアプリケーションに返します。この更新は、他のピアの事前の合意に従って、このピアが後に適用することになるものです。最初の追加ステップ ---ステップ4--- では、アプリケーションが、それぞれの台帳にコミットするためのトランザクションとして、一致する提案済の更新の適切なセットをピアのネットワーク全体に送信する必要があります。これは、**orderer**を使用してトランザクションをブロックにパッケージ化し、それらをピアのネットワーク全体に配布することで実現され、これらのトランザクションは、各ピアの台帳のローカルコピーに適用される前に検証できます。この順序付け処理全体が完了するまでに時間(数秒)がかかるため、ステップ5に示すように、アプリケーションは非同期で通知されます。
```

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +## ピアとアイデンティテ
```suggestion
## ピアとアイデンティティ
```
他の翻訳では、「アイデンティティ」としていますので、統一した方がよいと思います。以下、同じ表現が何カ所かありますが省略します。

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +フェーズ1は、アプリケーションが十分な数のピアから署名された提案応答を受信すると終了します。我々は、異なるピアが、*同じトランザクション提案に対して*、異なる、すなわち、一貫性のないトランザクション応答をアプリケーションに返す可能性があることに留意が必要です。単に、異なる状態の台帳を持つ異なるピアで異なる時間に結果が生成され、その場合、アプリケーションは単純に、より最新の提案応答を要求できます。
```suggestion
フェーズ1は、アプリケーションが十分な数のピアから署名された提案応答を受信すると終了します。我々は、異なるピアが、*同じトランザクション提案に対して*、異なる、すなわち、一貫性のないトランザクション応答をアプリケーションに返す可能性があることに留意が必要です。単に、異なる状態の台帳を持つ異なるピアで異なる時間に結果が生成されたということかもしれず、その場合、アプリケーションは単純に、より最新の提案応答を要求できます。可能性は低いが、より深刻なのは、チェーンコードが*非決定的である*ことにより、結果が異なる場合です。非決定性はチェーンコードと台帳の敵であり、それが発生した場合、矛盾した結果は明らかに台帳に適用できないので、提案されたトランザクションに重大な問題を示す。個々のピアは、トランザクションの結果が非決定的であることを知ることはできません。非決定的であることを検出する前に、比較のためにトランザクション応答を収集する必要があります。(厳密に言えば、これだけでは十分ではありませんが、この議論はトランザクションセクションに委ねます。トランザクションセクションでは、非決定性について詳しく説明します。
```

Non-determinism/deterministicは、非決定性/非決定的としたほうが一般的かと思います。
https://hyperledger-fabric.readthedocs.io/ja/release-2.2/whatis.html でもそう訳しています。

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +これで、ファブリック内で関連するピアとその他のコンポーネントのツアーは終了です。これまで見てきたように、ピアは多くの点で最も基本的な要素です。ピアは、ネットワークを形成し、チェーンコードおよび台帳をホストし、トランザクションの提案と応答を処理し、一貫してトランザクションの更新を適用することによって台帳を最新の状態に維持します。
```suggestion
これで、Fabric内で関連するピアとその他のコンポーネントのツアーは終了です。これまで見てきたように、ピアは多くの点で最も基本的な要素です。ピアは、ネットワークを形成し、チェーンコードおよび台帳をホストし、トランザクションの提案と応答を処理し、一貫してトランザクションの更新を適用することによって台帳を最新の状態に維持します。
```

2020-10-20 00:16 UTC, shimos commented on docs/locale/ja_JP/source/peers/peers.md
> +このトランザクションワークフロープロセス全体を*合意形成*と呼びます。これは、すべてのピアが、ordererによって仲介されるプロセスにおいて、トランザクションの順序と内容について合意に達しているためです。合意形成は複数ステップのプロセスであり、プロセスが完了したときにのみ、アプリケーションに台帳の更新が通知されます。これは、異なるピアわずかに異なる時間に発生する場合があります。
```suggestion
このトランザクションワークフロープロセス全体を*合意形成*と呼びます。これは、すべてのピアが、ordererによって仲介されるプロセスにおいて、トランザクションの順序と内容について合意に達しているためです。合意形成は複数ステップのプロセスであり、プロセスが完了したときにのみ、アプリケーションに台帳の更新が通知されます。これは、異なるピアではわずかに異なる時間に発生する場合があります。
```

2020-10-20 08:02 UTC, nekia commented on docs/locale/ja_JP/source/peers/peers.md
> +フェーズ1は、アプリケーションが十分な数のピアから署名された提案応答を受信すると終了します。我々は、異なるピアが、*同じトランザクション提案に対して*、異なる、すなわち、一貫性のないトランザクション応答をアプリケーションに返す可能性があることに留意が必要です。単に、異なる状態の台帳を持つ異なるピアで異なる時間に結果が生成され、その場合、アプリケーションは単純に、より最新の提案応答を要求できます。
👍

2020-10-21 08:12 UTC, nekia commented
@shimos レビューありがとうございました。類似箇所を確認し更新しました。確認よろしくお願いします。更新差分は以下です。
https://github.com/hyperledger/fabric-docs-i18n/pull/250/commits/9be964adae7cf98cb95bb7ced5c0694368b29a37

2020-10-21 15:51 UTC, shimos approved these changes
@nekia 修正ありがとうございました。LGTM

2020-10-21 15:51 UTC, merged