[ja_JP]Translate "orderer/ordering_service.md" into Japanese(#104)
hyperledger/fabric-docs-i18n pull request #255
Opened 2020-11-05 13:10 UTC by Skurimura

This patch translates orderer/ordering_service.md into Japanese

Signed-off-by: shogo kurimura <e35857@jp.ibm.com>

2020-11-09 22:02 UTC, shimos requested changes
@Skurimura 翻訳ありがとうございます。いくつかコメントを付け加えましたので、確認をお願いいたします。

2020-11-09 22:02 UTC, shimos commented on docs/locale/ja_JP/source/orderer/ordering_service.md
> +  v1.4.1の新しく提供されたRaftは、[`etcd`](https://coreos.com/etcd/)における[Raftプロトコル](https://raft.github.io/raft.pdf)の実装に基づくクラッシュフォールトトレラント(CFT)のオーダリングサービスです。Raftは「リーダーとフォロワー」モデルに従い、リーダーノードが(チャネルごとに)選出され、その決定がフォ
```suggestion
  v1.4.1で新しく提供されたRaftは、[`etcd`](https://coreos.com/etcd/)における[Raftプロトコル](https://raft.github.io/raft.pdf)の実装に基づくクラッシュ故障耐性(CFT)のオーダリングサービスです。Raftは「リーダーとフォロワー」モデルに従い、リーダーノードが(チャネルごとに)選出され、その決定がフォロワーによって複製されます。Raftのオーダリングサービスは、Kafkaベースのオーダリングサービスよりもセットアップと管理が容易であり、その設計により、さまざまな組織が分散オーダリングサービスにノードを提供できるようになりました。
```
Glossaryでは、CFTをクラッシュ故障耐性としているので、統一したほうがよいでしょう。

2020-11-09 22:02 UTC, shimos commented on docs/locale/ja_JP/source/orderer/ordering_service.md
> +本番ネットワーク向けの望ましいオーダリングサービスの選択肢として、確立されたRaftプロトコルのFabric実装は、チャネル内のオーダリングノード(このノードの集合は"consent set"として知られている)の中でリーダーが動的に選出され、リーダーがメッセージをフォロワーノードに複製する"leader and follower"モデルを使用します。オーダリングノードの大部分(「クォーラム」と
```suggestion
本番ネットワーク向けの望ましいオーダリングサービスの選択肢として、確立されたRaftプロトコルのFabric実装は、チャネル内のオーダリングノード(このノードの集合は"consent set"として知られている)の中でリーダーが動的に選出され、リーダーがメッセージをフォロワーノードに複製する"leader and follower"モデルを使用します。オーダリングノードの大部分(「クォーラム」として知られる)が残っている限り、システムは、リーダーノードを含むノードの損失に耐えることができるので、Raftは「クラッシュ故障耐性」(CFT)があると言われます。つまり、1つのチャネルに3つのノードがある場合、1つのノードの損失に耐えることができます(2つのノードが残ります)。チャネルに5つのノードがある場合、2つのノードの損失に耐えることが出来ます(残りの3つのノードで稼働します)。
```

2020-11-09 22:02 UTC, shimos commented on docs/locale/ja_JP/source/orderer/ordering_service.md
> +Fabricがサポートするもう1つのクラッシュフォールトトレラントのオーダリングサービスは、オーダリングノードのクラスタとして使用するためのKafka分散ストリーミングプラットフォームの適用です。[Apache Kafka Webサイト](https://kafka.apache.org/intro)でKafkaの詳細を読むことができますが、KafkaはRaftと同じ概念の「リーダーとフォロワー
```suggestion
Fabricがサポートするもう1つのクラッシュ故障耐性のあるオーダリングサービスは、オーダリングノードのクラスタとして使用するためのKafka分散ストリーミングプラットフォームの適用です。[Apache Kafka Webサイト](https://kafka.apache.org/intro)でKafkaの詳細を読むことができますが、KafkaはRaftと同じ概念の「リーダーとフォロワー」構成を使用しており、トランザクション(Kafkaは「メッセージ」と呼びます)はリーダーノードからフォロワーノードに複製されます。リーダーノードがダウンした場合、フォロワーの1つがリーダーになり、Raftと同様にフォールトトレランスを確保しながら順序付けを続けることができます。
```

2020-11-09 22:02 UTC, shimos commented on docs/locale/ja_JP/source/orderer/ordering_service.md
> +* Raftは、BFT(Byzantine Fault Tolerant)オーダリングサービスに向けた第一歩です。これから見ていくように、Raftの開発におけるいくつかの決定は、このような方向性により行われました。BFTに興味をお持ちであれば、Raftの使い方を学ぶことで移行が容易になるはずです。
```suggestion
* Raftは、BFT(ビザンチン故障耐性)オーダリングサービスに向けた第一歩です。これから見ていくように、Raftの開発におけるいくつかの決定は、このような方向性により行われました。BFTに興味をお持ちであれば、Raftの使い方を学ぶことで移行が容易になるはずです。
```
これもGlossaryにあわせたほうがよいでしょう。

2020-11-09 22:02 UTC, shimos commented on docs/locale/ja_JP/source/orderer/ordering_service.md
> +**ログエントリ**。Raftオーダリングサービスにおける作業の基本単位は「ログエントリ」であり、このようなエントリの完全なシーケンスは「ログ」として知られています。ここでは、メンバーの過半数(つまりクォーラム)がエントリとその順序を承認し、さまざまなodererにログが複製されている場合に、ログの整合性が保たれていると考えます。
```suggestion
**ログエントリ**。Raftオーダリングサービスにおける作業の基本単位は「ログエントリ」であり、このようなエントリの完全なシーケンスは「ログ」として知られています。ここでは、メンバーの過半数(つまりクォーラム)がエントリとその順序を承認し、さまざまなordererにログが複製されている場合に、ログの整合性が保たれていると考えます。
```

2020-11-09 22:02 UTC, shimos commented on docs/locale/ja_JP/source/orderer/ordering_service.md
> +**Finite-State Machine (FSM)**。RaftのすべてのオーダリングノードはFSMを持ち、それらは集合的に、様々なオーダリングノードのログのシーケンスが決定的であることを保証するために使われます(同じシーケンスで書かれます)。
```suggestion
**有限状態ステートマシン (FSM)**。RaftのすべてのオーダリングノードはFSMを持ち、それらは集合的に、様々なオーダリングノードのログのシーケンスが決定的であることを保証するために使われます(同じシーケンスで書かれます)。
```
もしくは「有限状態機械」などの日本語でよいと思います。

2020-11-09 22:02 UTC, shimos commented on docs/locale/ja_JP/source/orderer/ordering_service.md
> +Kafkaクラスタの管理(タスクの調整、クラスタメンバーシップ、アクセスkafkaクラスタの管理は、ZooKeeperアンサンブルとその関連APIによって処理されます。
```suggestion
Kafkaクラスタの管理(タスクの調整、クラスタメンバーシップ、アクセス制限、コントローラ選出など)は、ZooKeeperアンサンブルとその関連APIによって処理されます。
```

2021-03-02 02:31 UTC, shimos commented
@Skurimura こちらの修正の状況はいかがでしょうか。Rocket.Chatでもご案内の通り、FabricのAging Policyを適用することとしましたので、2週間以内にお知らせいただけますでしょうか。
もし、修正が難しいようでしたらReviewerのほうで対応することもできます。なお、2週間経過しても返答いただけない場合、このPRはcloseさせていただき、Reviewerやほかの方が引き継ぐこととなりますので、ご承知おきください。

2021-03-14 14:03 UTC, Skurimura commented
@shimos お世話になっております。こちら更新がかなり遅れてしまい大変申し訳ありません。修正いたしましたのでご確認お願いいたします。

2021-03-15 00:23 UTC, shimos approved these changes
修正ありがとうございました。LGTM

2021-03-15 00:23 UTC, merged