[ja_JP]Translate “channels.rst” into Japanese(#242)
hyperledger/fabric-docs-i18n pull request #256
Opened 2020-11-05 13:22 UTC by Skurimura

This patch translates channels.rst into Japanese

Signed-off-by: shogo kurimura <e35857@jp.ibm.com>

2020-11-10 02:59 UTC, satota2 requested changes, later dismissed
@Skurimura 
翻訳ありがとうございます。何点かコメントさせていただきましたので確認をお願いします。

2020-11-10 02:59 UTC, satota2 commented on docs/locale/ja_JP/source/channels.rst
> +チャネルに所属する各ピアにはメンバーシップサービスプロバイダー(MSP)によって付与される独自のIDを保持します。MSPは各ピアをチャネルのピアおよびサービスに対して認証します。
```suggestion
チャネルに所属する各ピアにはメンバーシップサービスプロバイダ(MSP)によって付与される独自のアイデンティティを保持します。MSPは各ピアをチャネルのピアおよびサービスに対して認証します。
```

Glossaryなど他の文書では上記の用語を使っているようなので統一したほうがよいかと思います。
4音以上の場合には語尾の「―」を省略しているようです。

2020-11-10 02:59 UTC, satota2 commented on docs/locale/ja_JP/source/channels.rst
> +この要求はチャネルポリシー、メンバー、およびアンカーピアに関する設定情報を保管するチャネル上の元帳の ``ジェネシスブロック`` を作成します。
```suggestion
この要求はチャネルポリシー、メンバー、およびアンカーピアに関する設定情報を保管するチャネル台帳の ``ジェネシスブロック`` を作成します。
```
他の文書では上記の用語を使っているようなので統一したほうがよいかと思います。

2020-11-10 02:59 UTC, satota2 commented on docs/locale/ja_JP/source/channels.rst
> +既存のチャネルに新しいメンバーを追加すると、ジェネシスブロック、もしくは該当する場合はより新しいコンフィギュレーションブロックが新しいメンバーに共有されます。
```suggestion
既存のチャネルに新しいメンバーを追加するときには、ジェネシスブロック、もしくは該当する場合はより新しいコンフィギュレーションブロックが新しいメンバーに共有されます。
```

(原文があまりよろしくない気がしますが・・、)
ブロックは新メンバーに自動的に共有されるわけではないと思うので、「追加すると」よりも「追加するときには」あるいは「追加する場合には」などの表現のほうがより自然かと思いました。

2020-11-10 02:59 UTC, satota2 commented on docs/locale/ja_JP/source/channels.rst
> +チャネル上の各メンバーに対する ``リーダーピア`` の選択は、どのピアがそのメンバーの代表としてオーダリングサービスと通信するかを決定することを意味します。
```suggestion
チャネル上の各メンバーに対する ``リーダーピア`` の選出は、どのピアがそのメンバーの代表としてオーダリングサービスと通信するかを決定することを意味します。
```
Glossaryなど他の文書では上記の用語を使っているようなので統一したほうがよいかと思います。

2020-11-10 02:59 UTC, satota2 commented on docs/locale/ja_JP/source/channels.rst
> +コンセンサスサービス（オーダリングサービス）はトランザクションを順序付けし、それをブロック単位で各リーダーピアに配布します。
```suggestion
合意形成サービス（オーダリングサービス）はトランザクションを順序付けし、それをブロック単位で各リーダーピアに配布します。
```
Glossaryなど他の文書では「Consensus」は「合意形成」と訳しているようなので、
こちらもそれを踏襲したほうがよいかもしれません。

2021-02-19 02:50 UTC, satota2 commented
@Skurimura しばらく更新がないようなのですがいかがでしょうか。
継続して本PR対応のご予定があるか否か教えて頂けると幸いです。もし本PRの対応継続が難しい場合には、レビューアが本ページの翻訳を引き継ぐことも可能です。

 (FabricのPRエイジングポリシーに従いまして、本リマインダー後、14日以内に特に返信などない場合には、自動的にPRはクローズされ、翻訳済みドキュメントを別PRにてreviewerが引き継ぐことになりますのでご承知おきください。)

2021-03-05 20:13 UTC, ryjones commented
@satota2  is this good enough to merge, and edit later? If so, I'd like to get it merged.

2021-03-10 00:20 UTC, satota2 commented
@ryjones Thank you for your comment.
Could you please merge the PR?
Then, I'm going to submit a new PR to update the doc based on my previous comments.

@Skurimura アナウンス通り、14日以上経過いたしましたので、本ページの翻訳を引き継がせていただきます。
やり方としては、一旦、本PRをマージしたあとで、新しいPRにて翻訳を更新させていただく予定です。
よろしくお願いします。

2021-03-10 19:12 UTC, ryjones approved these changes

2021-03-10 19:12 UTC, merged