[ja_JP]Translate “discovery-overview.rst” into Japanese(#243)
hyperledger/fabric-docs-i18n pull request #257
Opened 2020-11-05 13:36 UTC by Skurimura

This patch translates discovery-overview.rst into Japanese

Signed-off-by: shogo kurimura <e35857@jp.ibm.com>

2020-11-13 21:07 UTC, shimos requested changes
@Skurimura 翻訳ありがとうございます。いくつかコメントしましたので、ご確認ください。

2020-11-13 21:07 UTC, shimos commented on docs/locale/ja_JP/source/discovery-overview.rst
> +ピアでチェーンコードを実行し、トランザクションをordererに送信し、トランザクションのステータスを更新するために、
```suggestion
ピアでチェーンコードを実行し、トランザクションをordererに送信し、トランザクションのステータスについて通知を受けるために、
```
ここでは受け身なので、アプリケーションがステータスの変化について知らされる、の意味だと思います。上記は若干意訳気味ですが・・

2020-11-13 21:07 UTC, shimos commented on docs/locale/ja_JP/source/discovery-overview.rst
> +もしこのサービスを使わなければネットワークの残りのノードと通信する必要があるような情報です。
```suggestion
アプリケーションは構成クエリをディスカバリーサービスに発行し、ネットワークの他のノードと通信を行うのに、このサービスを使わなければ必要であった静的な情報すべてを取得します。
```
to communicate...は目的で、all the static informationは、neededの目的語に見えます。

また、他の部分・他のドキュメントにあわせて「クエリ」に統一したほうがよいかと思います。

2020-11-13 21:07 UTC, shimos commented on docs/locale/ja_JP/source/discovery-overview.rst
> +
"This information can be refreshed at any point by sending a subsequent query to the discovery service of a peer."の文の翻訳が抜けているようです。

2020-11-13 21:07 UTC, shimos commented on docs/locale/ja_JP/source/discovery-overview.rst
> +そして、エンドースできる組織(Org1とOrg2の両方にある ``peer0`` と ``peer1`` )の中で利用可能なピアの名前を提示します。
```suggestion
そして、エンドースできる組織の中で利用可能なピアの名前(Org1とOrg2の両方にある ``peer0`` と ``peer1`` )を提示します。
```
こちらのほうが修飾関係がわかりやすいかと思います。

2020-11-13 21:07 UTC, shimos commented on docs/locale/ja_JP/source/discovery-overview.rst
> +次に、SDKはリストからランダムレイアウトを選択します。上の例ではエンドースメントポリシーはOrg1 ``AND`` Org2です。
```suggestion
次に、SDKはリストからランダムにレイアウトを選択します。上の例ではエンドースメントポリシーはOrg1 ``AND`` Org2です。
```
原文通りではあるのですが、意味的には「ランダムに」のほうがわかりやすいかなと思いました。

2020-11-13 21:07 UTC, shimos commented on docs/locale/ja_JP/source/discovery-overview.rst
> +* **構成クエリ(Configuration query)**： チャネル内のすべての組織の ``MSPConfig`` と、
```suggestion
* **コンフィギュレーションクエリ(Configuration query)**： チャネル内のすべての組織の ``MSPConfig`` と、
```
Glossaryなどで単語は異なりますが、コンフィギュレーションブロックとしていますので、ここではカタカナのほうがよいかもしれません。

2021-03-02 02:31 UTC, shimos commented
@Skurimura こちらの修正の状況はいかがでしょうか。Rocket.Chatでもご案内の通り、FabricのAging Policyを適用することとしましたので、2週間以内にお知らせいただけますでしょうか。
もし、修正が難しいようでしたらReviewerのほうで対応することもできます。なお、2週間経過しても返答いただけない場合、このPRはcloseさせていただき、Reviewerやほかの方が引き継ぐこととなりますので、ご承知おきください。

2021-03-05 20:12 UTC, ryjones commented
@shimos is this good enough to merge, and edit later? If so, I'd like to get it merged.

2021-03-11 03:54 UTC, shimos commented
@ryjones Sorry for my late reply. Let us wait for the author's reponse for 5 more days as I wrote above. If we do not get any response by then, please merge this and I will submit another PR to edit this.

2021-03-14 14:07 UTC, Skurimura commented
@shimos お世話になっております。こちらも更新が遅れてしまい大変申し訳ありません。修正いたしましたのでご確認お願いいたします。

2021-03-15 00:05 UTC, shimos approved these changes
@Skurimura 修正ありがとうございました

2021-03-15 00:05 UTC, merged