[ja-JP]Translate write_first_app.rst into Japanese
hyperledger/fabric-docs-i18n pull request #267
Opened 2020-11-12 07:59 UTC by nishishita-satoshi

#200 translated write_first_app.rst for the first time.
Signed-off-by: nishishita-satoshi <nishishita.satoshi.jri@outlook.jp>

2020-11-17 17:46 UTC, shimos requested changes
@nishishita-satoshi PRありがとうございます。いくつかコメントをしましたのでご確認をお願いいたします。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +Fabricのアプリケーションとスマートコントラクトの詳細については、 :doc:`developapps/developing_applications` セクションまたは :doc:`Commercial Paper Tutorial<tutorial/commercial_paper>` を参照してください。
l.8の重複のようです。また、"This tutorial provides..."の文の翻訳が抜けているようです。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +スマートコントラクトAPIを使用して台帳の参照と更新が行われます。詳細については、 :doc:`Smart Contract Processing</developapps/smartcontract>` を参照してください。
```suggestion
スマートコントラクトAPIを使用して台帳のクエリと更新が行われます。詳細については、 :doc:`Smart Contract Processing</developapps/smartcontract>` を参照してください。
```
ledgerやstateの"query"については、クエリと訳しているドキュメントが多いので、それに統一するのはいかがでしょうか。
これ以降の文章でも複数個所出現していますが、省略します。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +また、サンプル・プログラムとデプロイされたCAを使用して、アプリケーションが許可されたブロックチェーンと接続するために必要なX.509証明書を生成します。
```suggestion
また、サンプル・プログラムとデプロイされたCAを使用して、アプリケーションが許可型のブロックチェーンと接続するために必要なX.509証明書を生成します。
```
どちらともとれる気がしますが、ブロックチェーンの分類の"permissioned"ではないかと思います。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +FabCarのサンプルでは、台帳に保存された ``Car`` を参照する方法と、台帳に新しい ``Car`` を追加する（更新する）方法を示します。
```suggestion
FabCarのサンプルでは、台帳に保存された ``Car`` （このサンプルでのビジネスデータ）をクエリする方法と、台帳を更新する（新しい ``Car`` を追加する）方法を示します。
```
非常に細かいですが、原文に従うとカッコの外と中は逆かなと思います。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +  2.スマートコントラクトは、台帳との相互接続を含むトランザクションを実装します。
```suggestion
  2.スマートコントラクトは、台帳とのやりとりを含むトランザクションを実装します。
```
ledgerとのinteractは、相互接続だとイメージがわきにくい気がするので、「やりとり」くらいのほうがわかりやすいのではないでしょうか。
これも以下の文章でいくつか出てきますが省略します。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +このチュートリアルでは、Fabricの :doc:`標準的なソフトウェア <prereqs>` に加えて、Hyperledger Fabric SDK for Node.jsを活用します。
"See the Node.js SDK `README <https://github.com/hyperledger/fabric-sdk-node#build-and-test>`__ for a up to date list of prerequisites."の訳が抜けているようです。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +既に :doc:`Using the Fabric test network<test_network>` を実行していて、ネットワークを起動して実行している場合、新しいネットワークを起動する前に、実行中のネットワークを停止します。
この訳だと読者に対する指示にも読めなくもないので、「このチュートリアルは(に従うと)」を明示するのはいかがでしょうか。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +ネットワークを作った時、管理者ユーザー（ ``admin`` と呼ばれる）が認証局（CA）の **Register** として作られました。
```suggestion
ネットワークを作った時、管理者ユーザー（ ``admin`` と呼ばれる）が認証局（CA）の **登録管理者(Registrar)** として作られました。
```
あまりよい訳語ではないかもしれませんが・・

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +アプリケーション・プログラムは、queryと呼ばれるスマートコントラクトの読取り専用プログラムを実行して、台帳から最新のデータを表示できます。
```suggestion
アプリケーション・プログラムは、クエリと呼ばれる、ピアで実行されているスマートコントラクトの読み取り専用の呼び出しによって、台帳から最新のデータを表示できます。
```
called a queryは、意味的にはread only invocationsにかかってるような気がします。
また、ここでは、query.jsのことではなく、クエリ一般についての話かと思います。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +以下に、queryの動作を簡略化して示します。
```suggestion
以下に、クエリの動作を簡略化して示します。
```
これもquery.jsでなくクエリ一般の動作概要に見えます。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +さらに、ステートデータベースとしてCouchDBを使用し、データをJSONでモデル化すると、複雑なクエリーを使用して台帳のデータを読み取ることができます。
```suggestion
さらに、ステートデータベースとしてCouchDBを使用し、データをJSONでモデル化すると、複雑なクエリを使用して台帳のデータを読み取ることができます。
```
表記ゆれのようです。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +  ここでは、自動車の照会、全ての自動車の照会、新しい自動車の作成など、アプリケーションとそのアプリケーションが作成するトランザクションのコードについて説明します。
```suggestion
  ここでは、ある自動車のクエリ、全ての自動車のクエリ、新しい自動車の作成など、アプリケーションのコードとそのアプリケーションが作成するトランザクションについて説明します。
```
transactionが、メッセージとしてのトランザクションと、スマートコントラクト内の関数の二つの文脈で使われているのでややこしいですが、ここでは、アプリケーションが作成すると言っているので、前者のほうではないでしょうか。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +まず、 ``query.js`` プログラムを実行して、台帳にあるすべての車のリストを取得します。このプログラムは、台帳にアクセスするために ``appUser`` を使用して台帳にアクセスします。
```suggestion
まず、 ``query.js`` プログラムを実行して、台帳にあるすべての車のリストを取得します。このプログラムは、台帳にアクセスするために二つ目のアイデンティティである ``appUser`` を使用して台帳にアクセスします。
```

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +接続プロファイルは ``fabric-samples/test-network`` ディレクトリ内からロードされ、JSON形式で記述されています。
```suggestion
コネクションプロファイルは ``fabric-samples/test-network`` ディレクトリ内からロードされ、JSON形式で記述されています。
```
今までの翻訳で出てきてはいないので決まった訳はないですが、Fabric独自の用語なので、固有名詞的にカタカナにするのはいかがでしょうか。
以下、何個か出現していますが省略します。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +単純に、接続プロファイルに定義されているPeerを選択してリクエストを送信し、そこで実行されます。
```suggestion
単純に、接続プロファイルに定義されているピアを選択してリクエストを送信し、リクエストはそこで実行されます。
```
他の文章と同様に「ピア」で統一したほうがよいでしょう。
これも以下の文章で複数ありますが、省略します。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +別の例として、もしあなたが ``startKey='CAR0',endKey='CAR999'`` を使用するなら、 ``getStateByRange`` は ``CAR0`` と ``CAR999`` の間のキーを持つ車を検索します。
inclusive, exclusive, in lexical orderの情報が抜けているので、これはあったほうがよいと思います。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +これで、いくつかのクエリーを実行し、少しコードを追加したので、台帳を更新する準備ができました。最初に **new** carを作成しましょう。
```suggestion
これで、いくつかのクエリーを実行し、少しコードを追加したので、台帳を更新する準備ができました。最初に **新しい** 自動車を作成しましょう。
```

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +これには **コンセンサス** のプロセスが含まれ、ブロックチェーンネットワークのさまざまなコンポーネントが連携して、提案された台帳の更新がすべて有効で、一貫した順序で実行されるようにします。
```suggestion
これには **合意形成** のプロセスが含まれ、ブロックチェーンネットワークのさまざまなコンポーネントが連携して、提案された台帳の更新がすべて有効で、一貫した順序で実行されるようにします。
```
Glossary等と訳語を統一したほうがよいでしょう。
これも、これ以降の文章でも出てきますが省略します。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +スマートコントラクト、API、そしてSDKが照会や更新で果たす役割の基本を見てきました。
"and you should have a feel for how different kinds of applications could be used to perform other business tasks and operations." の節の訳が抜けているようです。

2020-11-17 17:46 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +導入部で述べたように、私たちは次のセクション全体を持っています。 :doc:`Developing Application <developapps/developing_applications>` には、スマートコントラクト、プロセス、データ設計に関する詳細な情報、
```suggestion
導入部で述べたように、:doc:`Developing Application <developapps/developing_applications>` のセクション全体には、スマートコントラクト、プロセス、データ設計に関する詳細な情報、
```

2020-11-30 05:11 UTC, nishishita-satoshi commented
ご確認いただきありがとうございました。
ファイルを修正いたしました。こちらからご確認頂けますでしょうか。fd465c1

2020-12-01 17:41 UTC, shimos requested changes
@nishishita-satoshi 修正ありがとうございます。非常に細かい点なのですが、追加でコメントをしましたので、確認いただけますでしょうか。

また、commitは分割する必要はないと思いますので、修正をしたものもまとめて(squashして)、一つのcommitにしていただけますでしょうか。

2020-12-01 17:41 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +別の例として、もしあなたが ``startKey='CAR0',endKey='CAR999'`` を使用するなら、 ``getStateByRange`` は ``CAR0``　（包括的） と ``CAR999`` 　（排他的）の間のキーを持つ車を辞書順で検索します。
```suggestion
別の例として、もしあなたが ``startKey='CAR0',endKey='CAR999'`` を使用するなら、 ``getStateByRange`` は ``CAR0`` と ``CAR999`` の間のキー（ただし ``CAR0`` を含み ``CAR999`` は含まない）を持つ車を辞書順で検索します。
```
CAR0 <= key < CAR999であることを意図している表現だと思いますので、そのままだと訳しづらいのですが、たとえば上記のような訳はいかがでしょうか。

2020-12-01 17:41 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +コードの残りの部分はクエリーの結果を繰り返し処理し、サンプル・アプリケーションが使用するJSON形式でパッケージ化します。
```suggestion
コードの残りの部分はクエリの結果を繰り返し処理し、サンプル・アプリケーションが使用するJSON形式でパッケージ化します。
```

2020-12-01 17:41 UTC, shimos commented on docs/locale/ja_JP/source/write_first_app.rst
> +これで、いくつかのクエリーを実行し、少しコードを追加したので、台帳を更新する準備ができました。最初に **新しい** 自動車を作成しましょう。
```suggestion
これで、いくつかのクエリを実行し、少しコードを追加したので、台帳を更新する準備ができました。最初に **新しい** 自動車を作成しましょう。
```

2020-12-10 04:55 UTC, nishishita-satoshi commented on docs/locale/ja_JP/source/write_first_app.rst
> +これで、いくつかのクエリーを実行し、少しコードを追加したので、台帳を更新する準備ができました。最初に **新しい** 自動車を作成しましょう。
ご確認ありがとうございます。
時間があいてしまい、すみません。
お手数をおかけしますが、ご確認よろしくお願いします。
https://github.com/hyperledger/fabric-docs-i18n/commit/06e5efd66342929b826186e4bc125891c4aa5d8e

2020-12-10 18:01 UTC, shimos approved these changes
@nishishita-satoshi 修正ありがとうございました！

2020-12-10 18:02 UTC, merged