[ja_JP] Tutorials >> Deploying a smart contract
hyperledger/fabric-docs-i18n pull request #274
Opened 2020-11-17 10:09 UTC by nekia

Signed-off-by: Atsushi Neki <atsushin@fast.au.fujitsu.com>

Resolve #199

2020-11-17 10:12 UTC, nekia commented
レビューどうぞよろしくお願いします。

2020-11-19 01:06 UTC, shimos requested changes
@nekia 翻訳ありがとうございました。いくつかコメントをしましたので、ご確認ください。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +エンドユーザはスマートコントラクトを呼び出すことでブロックチェーン台帳と対話します。Hyperledger Fabricでは、スマートコントラクトはチェーンコードと呼ばれるパッケージに展開されます。トランザクションの検証や台帳のクエリを行う組織は、チェーンコードをピアにインストールする必要があります。チャネルに参加したピアにチェーンコードがインストールされると、チャネルメンバーはチェーンコードを
```suggestion
エンドユーザはスマートコントラクトを呼び出すことでブロックチェーン台帳と対話します。Hyperledger Fabricでは、スマートコントラクトはチェーンコードと呼ばれるパッケージでデプロイされます。トランザクションの検証や台帳のクエリを行う組織は、チェーンコードをピアにインストールする必要があります。チャネルに参加したピアにチェーンコードがインストールされると、チャネルメンバーはチェーンコードをチャネルに展開し、チェーンコードのスマートコントラクトを使用して、チャネル台帳のアセットを作成または更新できます。
```
以降では、deployをデプロイとしているようですし、ほかの翻訳でもデプロイが多いようなので、統一するのはいかがでしょうか。
この箇所以降の「展開」についても同様ですので、省略します。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +この手順は必須ではありませんが、チェーンコードのトラブルシューティングに非常に役立ちます。スマートコントラクトのログを監視するために,管理者は`logspout`[ツール](https://logdna.com/what-is-logspout/)を使用して,一連のDockerコンテナから集約された出力を表示することができます。このツールは、さまざまなDockerコンテナからの出力ストリームを1
```suggestion
この手順は必須ではありませんが、チェーンコードのトラブルシューティングに非常に役立ちます。スマートコントラクトのログを監視するために、管理者は`logspout`[ツール](https://logdna.com/what-is-logspout/)を使用して、一連のDockerコンテナから集約された出力を表示することができます。このツールは、さまざまなDockerコンテナからの出力ストリームを1つの場所に集め、1つのウィンドウで何が起きているかを簡単に見ることができます。これは、管理者がスマートコントラクトをインストールするときに問題をデバッグしたり、開発者がスマートコントラクトを呼び出すときに問題をデバッグしたりするのに役立ちます。一部のコンテナの中には、スマートコントラクトを開始するためだけに作成され、短時間しか存在しない場合もあるため、ネットワークからすべてのログを収集すると便利です。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +チェーンコードをパッケージ化する前に、チェーンコード依存性をインストールする必要があります。GoバージョンのFabcarチェーンコードが格納されているフォルダに移動します。
```suggestion
チェーンコードをパッケージ化する前に、チェーンコードの依存関係をインストールする必要があります。GoバージョンのFabcarチェーンコードが格納されているフォルダに移動します。
```
(原文が"dependencies"のtypoだと思いますが)次の文章で使われている「依存関係」に統一するのが良いと思います。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +`go.mod`ファイルは、Fabric Contract APIをスマートコントラクトパッケージにインポートします。`fabcar.go`をテキストエディタで開き、スマートコントラクトの開始時にコントラクトAPIを使用して`SmartContract`タイプを定義する方法を確認します:
```suggestion
`go.mod`ファイルは、Fabric コントラクトAPIをスマートコントラクトパッケージにインポートします。`fabcar.go`をテキストエディタで開き、スマートコントラクトの開始時にコントラクトAPIを使用して`SmartContract`タイプを定義する方法を確認します:
```
表記ゆれのようです。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +次に、``SmartContract``タイプを使用して、スマートコントラクト内で定義され、ブロックチェーン台帳にデータを読み書きするファンクションのトランザクションコンテキストを作成します。
```suggestion
次に、``SmartContract``タイプを使用して、スマートコントラクト内で定義され、ブロックチェーン台帳にデータを読み書きする関数のトランザクションコンテキストを作成します。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +これで依存関係ができたので、チェーンコードパッケージを作成することができます。`test-network`フォルダの作業ディレクトリに戻り、他のネットワーク成果物と一緒にチェーンコードをパッケージ化できるようにします。
```suggestion
これで依存関係ができたので、チェーンコードパッケージを作成することができます。`test-network`フォルダの作業ディレクトリに戻り、他のネットワークのアーティファクトと一緒にチェーンコードをパッケージ化できるようにします。
```
l.17でアーティファクトとしていますし、「成果物」は逆にわかりにくいのでカタカナに統一するのがよいのではないでしょうか。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +chaincodeをパッケージ化する前に、chaincode依存性をインストールする必要があります。JavaScriptバージョンのFabcarチェーンコードが格納されているフォルダに移動します。
```suggestion
チェーンコードをパッケージ化する前に、チェーンコードの依存関係をインストールする必要があります。JavaScriptバージョンのFabcarチェーンコードが格納されているフォルダに移動します。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +``FabCar``クラスは、ブロックチェーン台帳へデータを読み書きするスマートコントラクト内で定義されたファンクションのトランザクションコンテキストを提供します。
```suggestion
``FabCar``クラスは、ブロックチェーン台帳へデータを読み書きするスマートコントラクト内で定義された関数のトランザクションコンテキストを提供します。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +コマンドが正常に実行されると、JavaScriptパッケージは`npm_modules`フォルダー内にインストールされます。
```suggestion
コマンドが正常に実行されると、JavaScriptパッケージは`node_modules`フォルダ内にインストールされます。
```
原文のミスではありますが・・・

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +これで依存関係ができたので、chaincodeパッケージを作成することができます。`test-network`フォルダーの作業ディレクトリーに戻り、他のネットワーク成果物と一緒にチェーンコードをパッケージ化できるようにします。
```suggestion
これで依存関係ができたので、chaincodeパッケージを作成することができます。`test-network`フォルダーの作業ディレクトリーに戻り、他のネットワークのアーティファクトと一緒にチェーンコードをパッケージ化できるようにします。
```
l.128と同様です。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +チェーンコードをパッケージ化する前に、チェーンコードの依存性をインストールする必要があります。JavaバージョンのFabcarチェーンコードが格納されているフォルダに移動します。
```suggestion
チェーンコードをパッケージ化する前に、チェーンコードの依存関係をインストールする必要があります。JavaバージョンのFabcarチェーンコードが格納されているフォルダに移動します。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +`build.gradle`ファイルは、コントラクトクラスを含むスマートコントラクトパッケージにJavaチェーンコードシムをインポートします。Fabcarスマートコントラクトは`src`ディレクトリにあります。`FabCar.java`ファイルに移動してテキストエディタで開き、ブロックチェーン台帳にデータを読み書きするように定義されたファンクションのトランザクションコンテキストを作成するために、
```suggestion
`build.gradle`ファイルは、コントラクトクラスを含むスマートコントラクトパッケージにJavaチェーンコードのshimをインポートします。Fabcarスマートコントラクトは`src`ディレクトリにあります。`FabCar.java`ファイルに移動してテキストエディタで開き、ブロックチェーン台帳にデータを読み書きするように定義された関数のトランザクションコンテキストを作成するために、コントラクトクラスがどのように使用されるかを確認できます。
```
関数については、l.103と同様です。
シムは訳しづらいですが、クラス名などでそのまま出現するので、shimとアルファベット表記のほうがわかりやすいかもしれません。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +依存関係をインストールしてスマートコントラクトを構築したところで、チェーンコードパッケージを作成することができます。`test-network`フォルダーの作業ディレクトリに戻り、他のネットワーク成果物と一緒にチェーンコードをパッケージ化できるようにします。
```suggestion
依存関係をインストールしてスマートコントラクトを構築したところで、チェーンコードパッケージを作成することができます。`test-network`フォルダーの作業ディレクトリに戻り、他のネットワークのアーティファクトと一緒にチェーンコードをパッケージ化できるようにします。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +最初に、Org1ピアにチェーンコードをインストールしましょう。`peer` CLIをOrg1管理ユーザとして操作するには、次の環境変数を設定します。`CORE_PEER_ADDRESS`は、org1ピアである`peer0.org1.example.com`を指すように設定されます。
```suggestion
最初に、Org1ピアにチェーンコードをインストールしましょう。`peer` CLIをOrg1管理ユーザとして操作するには、次の環境変数を設定します。`CORE_PEER_ADDRESS`は、Org1ピアである`peer0.org1.example.com`を指すように設定されます。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +これで、Org2ピアにチェーンコードをインストールできます。次の環境変数を設定して、Org2管理者として動作し、Org2ピアである`peer0.Org2.example.com`をターゲットにします。
```suggestion
これで、Org2ピアにチェーンコードをインストールできます。次の環境変数を設定して、Org2管理者として動作し、Org2ピアである`peer0.org2.example.com`をターゲットにします。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +デプロイする前にチェーンコードを承認する必要があるチャネルメンバのセットは、`Applicaton/Channel/lifeycleEndorsement`ポリシーによって管理されます。デフォルトでは、このポリシーでは、チャネルで使用する前に、チャネルメンバーの過半数がチェーンコードを承認する必要があります。チャネルには組織が2つしかなく、2の過半数が2であるため、Org1およびOrg2がFab
```suggestion
デプロイする前にチェーンコードを承認する必要があるチャネルメンバのセットは、`Application/Channel/LifecycleEndorsement`ポリシーによって管理されます。デフォルトでは、このポリシーでは、チャネルで使用する前に、チャネルメンバーの過半数がチェーンコードを承認する必要があります。チャネルには組織が2つしかなく、2の過半数が2であるため、Org1およびOrg2がFabcarのチェーンコード定義を承認する必要があります。
```
これも原文のミスですが・・・

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +`approveformyorg`コマンドに``--signature-policy``または``--channel-config-policy``引数を指定して、チェーンコードエンドースメントポリシーを指定できます。エンドースメントポリシーは、異なるチャネルメンバに属するいくつのピアが、当該のチェーンコードに対してトランザクションを検証する必要があるかを指定します。我々はポリシーを設定しなかっ
```suggestion
`approveformyorg`コマンドに``--signature-policy``または``--channel-config-policy``引数を指定して、チェーンコードエンドースメントポリシーを指定できます。エンドースメントポリシーは、異なるチャネルメンバに属するいくつのピアが、当該のチェーンコードに対してトランザクションを検証する必要があるかを指定します。我々はポリシーを設定しなかったので、Fabcarの定義ではデフォルトのエンドースメントポリシーを使用します。このポリシーでは、トランザクションが提出されたときに、存在しているチャネルメンバーの過半数によってトランザクションがエンドースされることが要求されます。つまり、新しい組織がチャネルに追加されたり、チャネルから削除されたりすると、エンドースメントポリシーが自動的に更新され、より多くのエンドースメントが必要になったり、より少ないエンドースメントが必要になったりします。このチュートリアルでは、デフォルトポリシーは2つのうちの2つの過半数を必要とし、トランザクションはOrg1とOrg2のピアによって承認される必要があります。ユーザー設定のエンドースメントポリシーを指定する場合は、[エンドースメントポリシー](endorsement-policies.html)操作ガイドを使用して、ポリシー構文について学習できます。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +管理者ロールを持つアイデンティティでチェーンコード定義を承認する必要があります。その結果、`CORE_PEER_MSPCONFIGPATH`変数は、管理者アイデンティティを含むMSPフォルダをポイントする必要があります。チェーンコード定義は、クライアントユーザで承認することはできません。承認をorderingサービスに送信する必要があります。orderingサービスは管理者の署名を検証し、承認を
```suggestion
管理者ロールを持つアイデンティティでチェーンコード定義を承認する必要があります。その結果、`CORE_PEER_MSPCONFIGPATH`変数は、管理者アイデンティティを含むMSPフォルダをポイントする必要があります。チェーンコード定義は、クライアントユーザで承認することはできません。承認をオーダリングサービスに送信する必要があります。オーダリングサービスは管理者の署名を検証し、承認をピアに配布します。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +十分な数の組織がチェーンコード定義を承認すると、1つの組織がチェーンコード定義をチャネルにコミットできます。チャネルメンバの大多数が定義を承認した場合、コミットトランザクションは成功し、チェーンコード定義で合意されたパラメータがチャネルに実装されます。
```suggestion
十分な数の組織がチェーンコード定義を承認すると、1つの組織がチェーンコード定義をチャネルにコミットできます。チャネルメンバの過半数が定義を承認した場合、コミットトランザクションは成功し、チェーンコード定義で合意されたパラメータがチャネルに実装されます。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +上記のトランザクションは、`--peerAddresses`フラグを使用して、org1の`peer0.org1.example.com`とOrg2の`peer0.Org2.example.com`をターゲットにします。`commit` トランザクションは、チャネルに参加しているピアにサブミットされ、ピアを運用する組織によって承認されたチェーンコード定義を照会します。このコマンドは、チェーンコード
```suggestion
上記のトランザクションは、`--peerAddresses`フラグを使用して、Org1の`peer0.org1.example.com`とOrg2の`peer0.org2.example.com`をターゲットにします。`commit` トランザクションは、チャネルに参加しているピアにサブミットされ、ピアを運用する組織によって承認されたチェーンコード定義を照会します。このコマンドは、チェーンコードを展開するためのポリシーを満たすために、十分な数の組織からピアをターゲットにする必要があります。承認は各組織内に配布されるため、チャネルメンバーに属する任意のピアをターゲットにできます。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +チャネルメンバによるチェーンコード定義のエンドースメントは、ブロックに追加し、チャネルに配布するために、orderingサービスに提出されます。次に、チャネル上のピアは、十分な数の組織がチェーンコード定義を承認したかどうかを検証します。`peer lifecycle chaincode commit`コマンドは、応答を返す前に、ピアからの検証を待ちます。
```suggestion
チャネルメンバによるチェーンコード定義のエンドースメントは、ブロックに追加し、チャネルに配布するために、オーダリングサービスに提出されます。次に、チャネル上のピアは、十分な数の組織がチェーンコード定義を承認したかどうかを検証します。`peer lifecycle chaincode commit`コマンドは、応答を返す前に、ピアからの検証を待ちます。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +クエリに対する応答は、次の自動車のリストである必要があります:
```suggestion
クエリに対する応答は、次の自動車のリストになるはずです:
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +ここでは、Org1とOrg2が最初にFabcarチェーンコードのGOバージョンをインストールしたと想定しますが、JavaScriptで作成されたチェーンコードを使用する方が快適です。最初のステップは、FabcarチェーンコードのJavaScriptバージョンをパッケージ化することです。チュートリアルの実行時にJavaScriptの指示に従ってチェーンコードをパッケージ化した場合は、[Go](#g
```suggestion
ここでは、Org1とOrg2が最初にFabcarチェーンコードのGOバージョンをインストールしたのち、JavaScriptで作成されたチェーンコードを使用する方が快適になったと想定します。最初のステップは、FabcarチェーンコードのJavaScriptバージョンをパッケージ化することです。チュートリアルの実行時にJavaScriptの指示に従ってチェーンコードをパッケージ化した場合は、[Go](#go) または [Java](#java)で記述されたチェーンコードをパッケージ化する手順に従って、新しいチェーンコードバイナリをインストールできます。
```

後ろの節も含めて、assume that...の目的語(節)かと思います。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +次に、以下のコマンドを実行して、`test-network`ディレクトリーからJavaScriptチェーンコードをパッケージ化することができます。端末を閉じた場合に`peer` CLIを再度使用するために必要な環境変数を設定します。
```suggestion
次に、以下のコマンドを実行して、`test-network`ディレクトリからJavaScriptチェーンコードをパッケージ化することができます。端末を閉じた場合に`peer` CLIを再度使用するために必要な環境変数を設定します。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +次のコマンドを使用して、新しいchaincodeパッケージをOrg1ピアにインストールできます。
```suggestion
次のコマンドを使用して、新しいチェーンコードパッケージをOrg1ピアにインストールできます。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +新しいチェーンコードパッケージは、新しいパッケージIDを作成します。ピアにクエリすることで、新しいパッケージIDを見つけることができます。
```suggestion
新しいチェーンコードパッケージは、新しいパッケージIDを作成します。ピアに照会することで、新しいパッケージIDを見つけることができます。
```
ここまでパッケージID等のqueryについては、「照会」という言葉を使っているようですので、どちらかに統一した方がよいでしょう。

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +組織1は、新しいチェーンコード定義を承認できるようになりました:
```suggestion
Org1は、新しいチェーンコード定義を承認できるようになりました:
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +新しいチェーンコード定義では、JavaScriptチェーンコードパッケージのパッケージIDが使用され、チェーンコードバージョンが更新されます。シーケンスパラメータは、チェーンコードのアップグレードを追跡するためにファブリックチェーンコードライフサイクルで使用されるため、Org1でもシーケンス番号を1から2に増分する必要があります。[peer lifecycle chaincode queryco
```suggestion
新しいチェーンコード定義では、JavaScriptチェーンコードパッケージのパッケージIDが使用され、チェーンコードバージョンが更新されます。シーケンスパラメータは、チェーンコードのアップグレードを追跡するためにFabricチェーンコードライフサイクルで使用されるため、Org1でもシーケンス番号を1から2に増分する必要があります。[peer lifecycle chaincode querycommitted](commands/peerlifecycle.html#peer-lifecycle-chaincode-querycommitted)コマンドを使用すると、チャネルに最後にコミットされたチェーンコードのシーケンスを検索できます。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +`docker ps`コマンドを使うと,新しいチェーンコードがピア上で起動したことを確認できます:
```suggestion
`docker ps`コマンドを使うと、新しいチェーンコードがピア上で起動したことを確認できます:
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +台帳のすべての車を再度問い合せて、新規の車を表示できます:
```suggestion
台帳のすべての車を再度クエリして、新規の車を表示できます:
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +スマートコントラクトを作成してチャネルにデプロイしたら、Fabric SDKが提供するAPIを使用して、クライアントアプリケーションからスマートコントラクトを呼び出すことができます。これにより、エンドユーザはブロックチェーン台帳上の資産と対話することができます。Fabric SDKの使い始めるには、[Writing Your first application tutorial](write_f
```suggestion
スマートコントラクトを作成してチャネルにデプロイしたら、Fabric SDKが提供するAPIを使用して、クライアントアプリケーションからスマートコントラクトを呼び出すことができます。これにより、エンドユーザはブロックチェーン台帳上の資産と対話することができます。Fabric SDKを使い始めるには、[Writing Your first application tutorial](write_first_app.html)を参照してください。
```

2020-11-19 01:06 UTC, shimos commented on docs/locale/ja_JP/source/deploy_chaincode.md
> +**解決策:** チェーンコード定義を承認したときに、正しい`--package-id`を設定していない可能性があります。その結果、チャネルにコミットされたチェーンコード定義は、インストールしたチェーンコードパッケージに関連付けられず、チェーンコードはピア上で開始されませんでした。Dockerベースのネットワークを使っている場合は,`docker ps`コマンドを使って,チェインコードが動作して
```suggestion
**解決策:** チェーンコード定義を承認したときに、正しい`--package-id`を設定していない可能性があります。その結果、チャネルにコミットされたチェーンコード定義は、インストールしたチェーンコードパッケージに関連付けられず、チェーンコードはピア上で開始されませんでした。Dockerベースのネットワークを使っている場合は、`docker ps`コマンドを使って、チェーンコードが動作しているかどうかをチェックすることができます:
```

2020-11-20 13:44 UTC, nekia commented
レビューどうもありがとうございました。類似確認を実施し更新しました。類似確認による追加更新は https://github.com/hyperledger/fabric-docs-i18n/commit/0fab62fa91852ff079af9a88abd7365e50ad2f3f です。
確認のほどよろしくお願いします。 @shimos

2020-11-20 19:31 UTC, shimos approved these changes
@nekia 修正ありがとうございました！ LGTM

2020-11-20 19:31 UTC, merged