[ja-JP]Translated create_channel_overview.rst into Japanese
hyperledger/fabric-docs-i18n pull request #289
Opened 2020-12-11 01:29 UTC by nishishita-satoshi

#204 translated for the first time.

Signed-off-by: nishishita-satoshi <nishishita.satoshi.jri@outlook.jp>

2020-12-11 22:11 UTC, shimos requested changes
@nishishita-satoshi PRありがとうございます。非常に細かい点で申し訳ないですが、コメントを加えましたので確認いただけますでしょうか。

2020-12-11 22:11 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_overview.rst
> +チャネルの参加組織はチャネルにピアを加入し、Ordering Serviceから新しい取引ブロックを受け取れます。
```suggestion
チャネルの参加組織はチャネルにピアを加入し、オーダリングサービスから新しいトランザクションブロックを受け取れます。
```
他の翻訳では、「オーダリングサービス」と訳しているようですので統一したほうがよいでしょう。
transactionもここでは、ブロックに含まれているそれを指しているので、「トランザクション」としたほうがよいと思います。

2020-12-11 22:11 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_overview.rst
> +ピア、CA等のノードがネットワークの物理的なインフラストラクチャを形成する一方で、チャネルは組織が相互に接続してやりとりするプロセスです。
```suggestion
ピア、オーダリングノード、CAがネットワークの物理的なインフラストラクチャを形成する一方で、チャネルは組織が相互に接続してやりとりするプロセスです。
```
ここは原文の表現が悪いのですが、”nodes”はordering nodesを指しているかと思いますが、いかがでしょうか。

2020-12-14 01:37 UTC, nishishita-satoshi commented
ありがとうございます。
修正致しましたので、お手数をおかけしますが、ご確認よろしくお願いします。
https://github.com/hyperledger/fabric-docs-i18n/commit/14b80eb7921801692fa4e52f609473ca517ae0be

2020-12-14 18:02 UTC, shimos approved these changes
修正ありがとうございました。

2020-12-14 18:02 UTC, merged