Translate international_languages.md
hyperledger/fabric-docs-i18n pull request #334
Opened 2021-01-13 12:52 UTC by sc1000y

#312 
Signed-off-by: sc1000y <8299176+sc1000y@users.noreply.github.com>

2021-01-15 14:39 UTC, davidkhala commented on docs/locale/zh_CN/source/international_languages.md
> +**读者**: 任何想给非英语的Fabric文档做出贡献的人。
本章节面向的读者

2021-01-15 14:51 UTC, davidkhala commented on docs/locale/zh_CN/source/international_languages.md
> -website](https://hyperledger-fabric.readthedocs.io/en/latest/).
这一段感觉原文有语法错误

2021-01-15 14:51 UTC, davidkhala commented on docs/locale/zh_CN/source/international_languages.md
> -website](https://hyperledger-fabric.readthedocs.io/en/latest/).
错误发生在 `the files in this	
folder result contribute to the in the [documentation	
website]`

2021-01-15 14:55 UTC, davidkhala commented on docs/locale/zh_CN/source/international_languages.md
> +[Fabric主仓库](https://github.com/hyperledger/fabric)存放在GitHub的Hyperledger组织下。在它的`/docs/source`文件夹下包含英语版本的文档。当编译时，这个文件夹下的文件将在[文档网站](https://hyperledger-fabric.readthedocs.io/en/latest/)反应贡献。
反应贡献 -> 显示出来

2021-01-15 14:55 UTC, davidkhala requested changes
一些细微的改动

2021-01-16 14:26 UTC, sc1000y commented on docs/locale/zh_CN/source/international_languages.md
> -website](https://hyperledger-fabric.readthedocs.io/en/latest/).
我怀疑是上下这两段复制粘贴的，暂时捋了一下翻译并标注原文了。

2021-01-16 14:33 UTC, davidkhala approved these changes
LGTM

2021-01-16 14:33 UTC, merged