Update blockchain.rst
hyperledger/fabric-docs-i18n pull request #406
Opened 2021-03-28 00:22 UTC by renzhelou

为了更通畅的表达

2021-03-31 13:42 UTC, davidkhala commented on docs/locale/zh_CN/source/blockchain.rst
> +保持账本在整个网络中同步的过程称为 **共识** 。该过程确保所有账本仅在交易被相应参与者批准时更新，并且当账本更新时，所有账本都以相同的顺序更新相同的交易。
这里原文有提及“所有”这个单词么？

2021-03-31 13:45 UTC, davidkhala commented on docs/locale/zh_CN/source/blockchain.rst
> +即使可见性和信任的需求很明确，但在如今信息和流程共享的方法支离破碎，不可能构建一个跨业务网络的记录系统。
这里建议不改

2021-03-31 13:46 UTC, davidkhala commented on docs/locale/zh_CN/source/blockchain.rst
> +如果业务网络不是由像老鼠窝一样的（译者注：老鼠窝，指乱七八糟的系统），低效的“现代”交易系统构建，而是由一套标准方法构建，包括在网络上建立身份，执行交易和存储数据，那会怎么样？如果资产来源可以通过查看交易列表来确定，此列表一旦写入，无法更改，因此可信任，那会怎么样？
`标准方法`依然放定语从句后面更好

2021-04-05 05:32 UTC, davidkhala requested changes
新解释依然有不通顺的地方，建议将原文贴出来进行比对

2021-06-28 01:51 UTC, stone-ch approved these changes

2021-10-05 17:54 UTC, merged