[zh_CN]translate Docs Key Concepts Channel capabilities
hyperledger/fabric-docs-i18n pull request #419
Opened 2021-05-11 11:56 UTC by wuqiaomin

Signed-off-by: wuqiaomin <wuqiaomin2@huawei.com>
relate to issue #299

2021-05-28 02:29 UTC, davidkhala commented
@wuqiaomin 乔民这个怎么关了？

2021-05-28 02:30 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +*注意：这是一个超前的Fabric概念，
超前的 -> 进阶的，深度的

2021-05-28 02:33 UTC, wuqiaomin commented
> @wuqiaomin 乔民这个怎么关了？

哦哦sorry我这边操作失误了

2021-05-28 03:52 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +实际上，正因为其支持不同的版本级别
`级别` 应该可以不需要了

2021-05-28 03:57 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +为此，Fabric定义了所谓的“功能”级别。
“capabilities” 不翻译了，专用名词

2021-05-28 03:58 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +这些功能在每个通道的配置中定义，
同上

2021-05-28 04:03 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +# 通道功能
这个地方的 Capabilities是否应该翻译呢？我也有点疑惑

2021-05-28 07:05 UTC, wuqiaomin commented on docs/locale/zh_CN/source/capabilities_concept.md
> +# 通道功能
两个专有名词，level翻译为版本，或者不翻译，Capabilities一律不翻译吧

2021-05-29 03:02 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +# 通道功能
或者我们但凡出现version level的地方都只翻译成版本就好了

2021-05-29 03:07 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +  当一个peer节点加入一个通道时，它将顺序读取账本中的所有区块，从通道的创世块开始，持续经过交易区块和所有后续配置区块。如果节点(例如peer节点)试图读取一个包含其不理解的capabilities的更新的区块(例如，v1.4.x中peer节点试图读取包含v2.0应用程序capabilities的区块)，那么**peer节点将崩溃**。这种崩溃行为是故意的，因为v1.4.x的peer节点不应
`这种崩溃行为是故意的`
-> `这种崩溃现象是故意如此设计的`

2021-05-29 03:07 UTC, wuqiaomin commented on docs/locale/zh_CN/source/capabilities_concept.md
> +# 通道功能
是的，目前version level只翻版本，其他出现level的地方如果去掉之后不影响就去掉；不能去掉的保持原文

2021-05-29 03:12 UTC, davidkhala commented on docs/locale/zh_CN/source/capabilities_concept.md
> +* **在通道中，节点必须至少处于某些capability的level**。
在通道中，节点版本必须不能低于特定的capability版本

下面还有几处`至少`，也应该以类似的模式翻译

2021-05-29 03:26 UTC, davidkhala requested changes
review完了，只剩几个小问题

2021-05-29 10:03 UTC, davidkhala approved these changes

2021-05-29 10:03 UTC, merged