[pt_BR] translate prerequisites
hyperledger/fabric-docs-i18n pull request #477
Opened 2021-06-23 16:51 UTC by gth1ago

2021-06-26 14:18 UTC, pemtajo requested changes
Just smalls changes. Any problem contact me to help you

2021-06-26 14:18 UTC, pemtajo commented on docs/locale/pt_BR/source/prereqs.rst
> +.. note:: O seguinte se aplica a sistemas Linux executando o systemd.
Usando o contexto, acho que seria melhor mudar _O seguinte se aplica_ para _As seguintes instruções se aplicam_

2021-06-26 14:18 UTC, pemtajo commented on docs/locale/pt_BR/source/prereqs.rst
> +Adicionando um usuário para seu grupo docker.
Para manter a forma de linguagem do texto, altere _Adicionando_ para _Adicione_

2021-06-26 14:18 UTC, pemtajo commented on docs/locale/pt_BR/source/prereqs.rst
> +          intalará o Docker Compose. Se você já instalou o Docker, você
Typo: intalará -> instalará

2021-06-26 14:18 UTC, pemtajo commented on docs/locale/pt_BR/source/prereqs.rst
> +Em vez disso, é recomendado usar o ambiente MSYS2 e executar o make
_executar_ -> _execute_

2021-06-26 14:18 UTC, pemtajo commented on docs/locale/pt_BR/source/prereqs.rst
> +:doc:`getting_started`. Certifique=se de ter e usar uma versão mais recente,
Typo : _Certifique=se_ -> _Certifique-se_

2021-06-26 14:18 UTC, pemtajo commented on docs/locale/pt_BR/source/prereqs.rst
> +Para Node.js você também vai precisar necessáriamente da ferramente de compilação do Visual Studio C++,
Typo : _necessáriamente_ -> _necessariamente_

2021-06-26 14:18 UTC, pemtajo commented on docs/locale/pt_BR/source/prereqs.rst
> +Feito isso, você deve instalar o módulo NPM GRPC com o
Acho que fica mais acurado : _Feito isso, você deve instalar o módulo_ -> _Uma vez feito isso, você também deve instalar o módulo_

2021-07-05 00:34 UTC, gth1ago commented on docs/locale/pt_BR/source/prereqs.rst
> +Feito isso, você deve instalar o módulo NPM GRPC com o
Opa, obrigado pelas sugestões!
Tentei realizar um novo merge arrumando nesta PL e acho que me buguei em algo kk, acabou travando nos testes..
Qual seria o processo correto para realização das correções?

2021-07-05 00:55 UTC, gth1ago commented
Opa, obrigado pelas sugestões! Atualizei

2021-07-05 14:29 UTC, pemtajo requested changes
Veio arquivos de outras traduções, e o arquivo esta com tags de conflito de merge.

Cria um novo PR partindo da release-2.2 atualizada e só commita o arquivo que foi alterado. Se possível em 1 único commit.

2021-07-05 20:51 UTC, gth1ago commented
Verdade, vou fazer isso, valeu!

2021-07-05 20:51 UTC, closed without merging