[ja_JP] Translate "chaincode5ade.rst"
hyperledger/fabric-docs-i18n pull request #512
Opened 2021-07-17 23:01 UTC by satomicchy

This patch translates "Tutorials >> Chaincode for Developers" into Japanese.

Resolves #210

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2021-07-19 05:24 UTC, satota2 requested changes
@satomicchy 翻訳ありがとうございます。コメントにて修正案を記載いたしましたので、ご確認と取り込みの検討をよろしくお願いいたします。

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +チェーンコードは通常、ネットワークのメンバーが合意したビジネスロジックを処理するため、「スマートコントラクト」と見なします。チェーンコードは、提案トランザクションの台帳を更新またはクエリするためにに呼び出すことができます。適切な許可が与えられれば、チェーンコードは同じチャネルまたは別のチャネルにある別のチェーンコードを呼び出し、その状態にアクセスすることができます。ただし、もし呼ばれたチェーンコ
```suggestion
チェーンコードは通常、ネットワークのメンバーが合意したビジネスロジックを処理するため、「スマートコントラクト」と見なします。チェーンコードは、提案トランザクションで台帳を更新またはクエリするために呼び出すことができます。適切な許可が与えられれば、チェーンコードは同じチャネルまたは別のチャネルにある別のチェーンコードを呼び出し、そのステートにアクセスすることができます。ただし、もし呼ばれたチェーンコードが呼び出しをしているチェーンコードとは別のチャネルにある場合、読み込みクエリのみが許可されます。つまり、別のチャネルの呼ばれたチェーンコードは ``Query`` だけで、その後のコミット段階でステート検証チェックには参加しません。
```
文脈的に微妙な場面もあるのですが、stateは基本的にワールドステートのステートを示す場合が多いと思います。

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +以下のセクションでは、アプリケーション開発者の視点でチェーンコードを解説します。簡単なチェーンコードサンプルアプリケーションを提示し、Chaincode Shim APIにおける各方法の目的について確認していきます。もし、ネットワーク運用者の方で、実行中のネットワークへチェーンコードをデプロイしている場合は、 :doc:`deploy_chaincode` チュートリアルおよび :doc:`ch
```suggestion
以下のセクションでは、アプリケーション開発者の視点でチェーンコードを解説します。簡単なチェーンコードサンプルアプリケーションを提示し、Chaincode Shim APIにおける各メソッドの目的について確認していきます。もし、ネットワーク運用者の方で、実行中のネットワークへチェーンコードをデプロイしている場合は、 :doc:`deploy_chaincode` チュートリアルおよび :doc:`chaincode_lifecycle` コンセプトトピックを参照してください。
```

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +このチュートリアルでは、Fabric Chaincode Shim APIが提供する低レベルAPIの概要を説明します。また、Fabric Contract APIが提供する高位APIも使用できます。Fabric Contract APIを使ったスマートコントラクト開発の詳細については、 :doc:`developapps/smartcontract` トピックを参照してください。
```suggestion
このチュートリアルでは、Fabric Chaincode Shim APIが提供する低レベルAPIの概要を説明します。また、Fabric Contract APIが提供する高レベルAPIも使用できます。Fabric Contract APIを使ったスマートコントラクト開発の詳細については、 :doc:`developapps/smartcontract` トピックを参照してください。
```
低レベルAPIと用語を合わせると高レベルAPIのほうがよさそうです。

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +それぞれの言語で、 ``Invoke`` メソッドはトランザクション提案に送信するため、クライアントによって呼び出されます。この方法では、チャネル台帳でデータの読み込みおよび書き込みのためにチェーンコードを使用することが許可されます。
```suggestion
それぞれの言語で、 ``Invoke`` メソッドはトランザクション提案に送信するため、クライアントによって呼び出されます。このメソッドでは、チャネル台帳でデータの読み込みおよび書き込みのためにチェーンコードを使用することが許可されます。
```

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +また、初期化関数として機能するチェーンコードに ``Init`` メソッドを含める必要があります。この関数はチェーンコードインターフェイスによって要求されますが、必ずしもアプリケーションで呼び出す必要はありません。呼び出しの前に ``Init`` 関数を呼び出す必要があるかどうかを指定するために、Fabricチェーンコードライフサイクルプロセスを使用することができます。詳細は、Fabricチェー
```suggestion
また、チェーンコードには、初期化関数として機能する ``Init`` メソッドを含める必要があります。この関数はチェーンコードインターフェイスによって要求されますが、必ずしもアプリケーションで呼び出す必要はありません。``Invoke`` メソッド呼び出しの前に ``Init`` 関数を呼び出す必要があるかどうかを指定するために、Fabricチェーンコードライフサイクルプロセスを使用することができます。詳細は、Fabricチェーンコードライフサイクルドキュメントの `Approving a chaincode definition <chaincode_lifecycle.html#step-three-approve-a-chaincode-definition-for-your-organization>`__ の初期化パラメータを参照してください。
```
文章がより自然になるように修正・補足をしました。

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +Goでプログラミングを行っていない場合は、 `Go <https://golang.org>`_ がインストールされ、システムが正しく構成されていることを確認してください。モジュールに対応したバージョンを使用することを前提としています。
```suggestion
Goでプログラミングを行っていない場合は、 `Go <https://golang.org>`_ がインストールされ、システムが正しく設定されていることを確認してください。モジュールに対応したバージョンを使用することを前提としています。
```

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +まずはハウスキーピングから始めましょう。すべてのチェーンコードと同様に、 `Chaincode interface <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#Chaincode>`_ 、特に ``Init`` 関数と ``Invoke`` 関数のを実装します。そして、チェーンコードに必要な依存関係に対して
```suggestion
まずはハウスキーピングから始めましょう。すべてのチェーンコードと同様に、 `Chaincode interface <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#Chaincode>`_ 、特に ``Init`` 関数と ``Invoke`` 関数を実装します。そして、チェーンコードに必要な依存関係に対してGoインポート文を追加しましょう。Chaincode shimパッケージと `peer protobuf package <https://godoc.org/github.com/hyperledger/fabric-protos-go/peer>`_ (ピアプロトコルバッファーパッケージ)をインポートします。次に、 Chaincode shim関数のレシーバとして構造体SimpleAssetを追加しましょう。
```

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +.. note:: チェーンコードアップグレードはこの関数も呼ぶことに注意してください。既存のものをアップグレードするチェーンコードを作成する場合は、 ``Init`` 関数を適切に変更してください。特に、「マイグレーション」がない場合や、アップグレードするの一部として初期化されるものがない場合は、空の「Init」メソッドを提供してください。
```suggestion
.. note:: チェーンコードアップグレードはこの関数も呼ぶことに注意してください。既存のものをアップグレードするチェーンコードを作成する場合は、 ``Init`` 関数を適切に変更してください。特に、「マイグレーション」がない場合や、アップグレードする一部として初期化されるものがない場合は、空の「Init」メソッドを提供してください。
```

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +次に、呼び出しが正当であることを確認したので、初期状態を台帳に格納します。これを行うには、引数としてキーと値を伴った `ChaincodeStubInterface.PutState <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#ChaincodeStub.PutState>`_ を呼び出します。すべてがうま
```suggestion
次に、呼び出しが正当であることを確認したので、初期ステートを台帳に格納します。これを行うには、引数としてキーと値を伴った `ChaincodeStubInterface.PutState <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#ChaincodeStub.PutState>`_ を呼び出します。すべてがうまくいったと仮定して、初期化が成功したことを示すpeer.Responseオブジェクトを返します。
```

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +上記の ``Init`` 関数と同様に、 ``ChaincodeStubInterface`` からの引数を解凍するする必要があります。Invoke関数の引数は、Chaincode application関数を呼び出すための名前になります。この例では、アプリケーションには2つの関数があるだけです: ``set`` と ``get`` です。これらは、アセットの値を設定したり、現在の状態を取得した
```suggestion
上記の ``Init`` 関数と同様に、 ``ChaincodeStubInterface`` からの引数を解凍するする必要があります。Invoke関数の引数は、Chaincode application関数を呼び出すための名前になります。この例では、アプリケーションには2つの関数があるだけです: ``set`` と ``get`` です。これらは、アセットの値を設定したり、現在のステートを取得したりすることができます。最初に、Chaincode application関数に対して関数名とパラメータを展開するために、 `ChaincodeStubInterface.GetFunctionAndParameters <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#ChaincodeStub.GetFunctionAndParameters>`_ を呼び出します。
```

2021-07-19 05:24 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +すでに述べたように、私たちのチェーンコードアプリケーションは、 ``Invoke`` 関数経由で呼び出すことができる2つの機能を実装しています。ここでこれらの機能を実装しましょう。前述したように、台帳の状態にアクセスするには、Chaincode shim APIの `ChaincodeStubInterface.PutState <https://godoc.org/github.com/hyp
```suggestion
すでに述べたように、私たちのチェーンコードアプリケーションは、 ``Invoke`` 関数経由で呼び出すことができる2つの機能を実装しています。ここでこれらの機能を実装しましょう。前述したように、台帳のステートにアクセスするには、Chaincode shim APIの `ChaincodeStubInterface.PutState <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#ChaincodeStub.PutState>`_ 関数と `ChaincodeStubInterface.GetState <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#ChaincodeStub.GetState>`_ 関数を利用します。
```

2021-07-19 17:36 UTC, ryjones commented
The commit message says:

- [ja_JP] Translate "chaincode5ade.rst"

but the file changed is:

-  chaincode4ade.rst

2021-07-19 22:20 UTC, satomicchy commented
@satota2 レビューありがとうございます！修正しましたのでご確認お願いいたします。

2021-07-19 23:07 UTC, ryjones commented
thank you @satomicchy !

2021-07-20 01:02 UTC, satota2 requested changes
@satomicchy 修正ありがとうございます。すみません、軽微なものですが、一度目のレビューの見落としがありました。お手数ですが、再度修正案のご確認と取り込みの検討をお願いできますでしょうか。そのほかは特に問題ないと思います。

2021-07-20 01:02 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +上記の ``Init`` 関数と同様に、 ``ChaincodeStubInterface`` からの引数を解凍するする必要があります。Invoke関数の引数は、Chaincode application関数を呼び出すための名前になります。この例では、アプリケーションには2つの関数があるだけです: ``set`` と ``get`` です。これらは、アセットの値を設定したり、現在のステートを取得
```suggestion
上記の ``Init`` 関数と同様に、 ``ChaincodeStubInterface`` からの引数を解凍するする必要があります。Invoke関数の引数は、チェーンコードアプリケーション関数を呼び出すための名前になります。この例では、アプリケーションには2つの関数があるだけです: ``set`` と ``get`` です。これらは、アセットの値を設定したり、現在のステートを取得したりすることができます。最初に、チェーンコードアプリケーション関数に対して関数名とパラメータを展開するために、 `ChaincodeStubInterface.GetFunctionAndParameters <https://godoc.org/github.com/hyperledger/fabric-chaincode-go/shim#ChaincodeStub.GetFunctionAndParameters>`_ を呼び出します。
```

2021-07-20 01:02 UTC, satota2 commented on docs/locale/ja_JP/source/chaincode4ade.rst
> +チェーンコード・ディレクトリーで依存関係がベンダー化されると、 ``peer chaincode package`` と ``peer chaincode install`` のオペレーションは、依存関係に関連したコードをチェーンコードパッケージに組み込みます。
```suggestion
チェーンコードディレクトリで依存関係がベンダー化されると、 ``peer chaincode package`` と ``peer chaincode install`` のオペレーションは、依存関係に関連したコードをチェーンコードパッケージに組み込みます。
```

2021-07-20 20:53 UTC, satomicchy commented
@satota2 再度修正しました。ご確認お願いいたします。

2021-07-21 01:17 UTC, satota2 approved these changes
LGTM! 翻訳お疲れ様でした。

2021-07-21 01:18 UTC, merged