[ja_JP] Translate "create_channel/channel_policies.md"
hyperledger/fabric-docs-i18n pull request #520
Opened 2021-07-28 22:57 UTC by satomicchy

This patch translates "Tutorials >> Creating a channel >> Channel policies" into Japanese.

Resolves #207

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2021-07-28 22:58 UTC, satomicchy commented
ポリシー名をカタカナにするかアルファベットにするか迷って、元がキャメルケースのものだけアルファベットのままにしました。

2021-07-29 09:38 UTC, satota2 requested changes
@satomicchy 翻訳ありがとうございます。コメントにて修正案を記載いたしましたので、ご確認と取り込みの検討をよろしくお願いいたします。

> ポリシー名をカタカナにするかアルファベットにするか迷って、元がキャメルケースのものだけアルファベットのままにしました。

基本的にはその方針でよいかと思いました。

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +チャネルは、組織間のプライベートな通信方式です。そのため、チャネル設定に対するほとんどの変更は、チャネルの他のメンバーによって同意される必要があります。組織が他の組織の承認を取得することなく、台帳上のデータをチャネルおよび読み込みに参加するできる場合、チャネルは役に立ちません。どんなチャネル **structure** (構造)に対する変更も、チャネルポリシーを満たすことができる一連の組織によっ
```suggestion
チャネルは、組織間のプライベートな通信方式です。そのため、チャネル設定に対するほとんどの変更は、チャネルの他のメンバーによって同意される必要があります。組織が他の組織の承認を取得することなくチャネルに参加して台帳上のデータの読み込みをできる場合、チャネルは役に立ちません。チャネル **structure** (構造)に対するどんな変更も、チャネルポリシーを満たすことができる一連の組織によって承認される必要があります。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +また、ポリシーは、ユーザーがチャネルとやりとりする方法の **processes** (プロセス)も管理されます。たとえば、チャネルにデプロイされる前にチェーンコードを承認する必要がある一連の組織や、チャネル管理者が完了する必要があるアクションなどです。
```suggestion
また、ポリシーは、ユーザーがチャネルとやりとりする方法の **processes** (プロセス)も管理します。たとえば、チャネルにデプロイされる前にチェーンコードを承認する必要がある一連の組織や、チャネル管理者が完了する必要があるアクションなどです。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +チャネルポリシーは、独自のトピックで議論する必要があるほど重要です。チャネル設定の他の部分とは異なり、チャネルを管理するするポリシーは、 `configtx.yaml` ファイルのさまざまなセクションがどのように連携するかによって決定されます。チャネルポリシーは制約の少ないユースケースに対して設定することができますが、このトピックでは、Hyperledger Fabricによって提供されるデフォ
```suggestion
チャネルポリシーは、独自のトピックで議論する必要があるほど重要です。チャネル設定の他の部分とは異なり、チャネルを管理するポリシーは、 `configtx.yaml` ファイルのさまざまなセクションがどのように連携するかによって決定されます。チャネルポリシーはいくつかの制約のもとであらゆるユースケースに合わせて設定することができますが、このトピックでは、Hyperledger Fabricによって提供されるデフォルトポリシーの使用方法に重点を置きます。Fabricテストネットワークまたは [Fabric sample configuration](https://github.com/hyperledger/fabric/blob/{BRANCH}/sampleconfig/configtx.yaml) で使用されるデフォルトポリシーを使用する場合、作成する各チャネルはSignatureポリシー、ImplicitMetaポリシーおよびアクセス制御リストの組合せを使用して、組織がチャネルとやりとりする方法を決定し、チャネル構造の更新することに同意します。Hyperledger Fabricにおけるポリシーのロールについては、 [Policies concept topic](../policies.html) を参照すると、さらに詳しく知ることができます。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +デフォルトでは、各チャネルメンバーは組織を参照するSignatureポリシーのセットを定義します。提案がピアに提出されるか、トランザクションがオーダリングノードに提出されたとき、ノードはトランザクションに添付された署名を読み込みし、チャネル設定で定義されたSignatureポリシーに対してそれらを評価します。すべての署名ポリシーには、署名によってポリシーを満たすことができる組織とアイデンティティ
```suggestion
デフォルトでは、各チャネルメンバーは組織を参照するSignatureポリシーのセットを定義します。提案がピアに送信されるか、トランザクションがオーダリングノードに送信されたとき、ノードはトランザクションに添付された署名を読み込みし、チャネル設定で定義されたSignatureポリシーに対してそれらを評価します。すべてのSignatureポリシーには、署名によってポリシーを満たすことができる組織とアイデンティティのセットを指定するルールがあります。 `configtx.yaml` の **Organizations** セクションで、Org1によって定義されたSignatureポリシーは次のように表示されます。 :
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +上記のポリシーはすべて、Org1からの署名によって満たすことができます。ただし、各ポリシーは、ポリシーを満たすことができる組織内から異なるロールセットを記載します。 `Admins` ポリシーは、管理者ロールを持つアイデンティティによって送信されたトランザクションによってのみ満たされますが、ピアロールを持つアイデンティティのみが `Endorsement` ポリシーを満たすことができます。1つの
```suggestion
上記のポリシーはすべて、Org1からの署名によって満たすことができます。ただし、各ポリシーには、そのポリシーを満たすことができる組織内の様々なロール(のセット)が記載されています。 `Admins` ポリシーは、管理者ロールを持つアイデンティティによって送信されたトランザクションによってのみ満たされます。一方、 `Endorsement` ポリシーはピアロールを持つアイデンティティのみが満たすことができます。1つのトランザクションに付けられた署名セットは、複数のSignatureポリシーを満たすことができます。たとえば、トランザクションに添付されたエンドースメントがOrg1とOrg2の両方によって提供された場合、この署名セットはOrg1かつOrg2の `Endorsement` ポリシーを満たすことになります。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +チャネルがデフォルトポリシーを使用する場合、各組織のSignatureポリシーは、チャネル設定の上位レベルにあるImplicitMetaポリシーによって評価されます。チャネルに送信された署名を直接評価する代わりに、ImplicitMetaポリシーでは、ポリシーを満たすことができるチャネル設定内の他のポリシーのセットを指定するルールがあります。トランザクションは、ポリシーによって参照されるSign
```suggestion
チャネルがデフォルトポリシーを使用する場合、各組織のSignatureポリシーは、チャネル設定の上位レベルにあるImplicitMetaポリシーによって評価されます。ImplicitMetaポリシーはチャネルに送信された署名を直接評価するのではなく、ポリシーを満たすことができるチャネル設定内の他のポリシーのセットを指定するルールを持っています。トランザクションは、ポリシーによって参照される下位レイヤのSignatureポリシーセットを満たすことができれば、ImplicitMetaポリシーを満たすことができます。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +各ポリシーは、チャネル設定内のパスを参照します。 **Application** セクションにあるポリシーはアプリケーショングループにあり、チャネルグループの中に位置するため、 `Channel/Application` ポリシーと呼ばれます。Fabricドキュメンテーションのほとんどの箇所では、ポリシーはパスによって参照されるため、チュートリアルの残りの部分では、パスによるポリシー参照します。
```suggestion
各ポリシーは、チャネル設定内のパスを参照します。 **Application** セクションにあるポリシーはチャネルグループの中にあるアプリケーショングループに位置するため、 `Channel/Application` ポリシーとして参照されます。Fabricドキュメンテーションのほとんどの箇所では、ポリシーはパスによって参照されるため、チュートリアルの残りの部分では、パスによるポリシー参照をします。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +*Figure 2: チャネルに送信されたチャネル・アップデート・リクエストは、Org1、Org2およびOrg3からの署名が含まれており、各組織のSignatureポリシーを満たしています。その結果、リクエストはChannel/Application/Adminsポリシーを満たしています。署名は過半数に達する必要がなかったため、Org3チェックが明るい緑色で表示されています。*
```suggestion
*Figure 2: チャネルに送信されたチャネル更新リクエストは、Org1、Org2およびOrg3からの署名が含まれており、各組織のSignatureポリシーを満たしています。その結果、リクエストはChannel/Application/Adminsポリシーを満たしています。Org3の署名は過半数に達するために必要としなかったため、チェックマークが明るい緑色で表示されています。*
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +別の例をあげると、 `Channel/Application/Endorsement` ポリシーは、各組織のピアからの署名を必要とする組織の `Endorsement` ポリシーの過半数によって満たされることができます。このポリシーは、デフォルトチェーンコードエンドースメントポリシーとしてFabricチェーンコードライフサイクルに使用されます。異なるエンドースメントポリシーを持つチェーンコード定
```suggestion
別の例をあげると、 `Channel/Application/Endorsement` ポリシーは、各組織のピアからの署名を必要とする、過半数の組織の `Endorsement` ポリシーを満たすことができます。このポリシーは、デフォルトチェーンコードエンドースメントポリシーとしてFabricチェーンコードライフサイクルに使用されます。異なるエンドースメントポリシーを持つチェーンコード定義をコミットするする場合を除き、チェーンコードを呼び出すトランザクションはチャネルメンバーの過半数によって承認される必要があります。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +*Figure 3: クライアントアプリケーションからのトランザクションは、Org1およびOrg2のピアにあるチェーンコードを呼び出しました。チェーンコードの呼び出しは成功し、アプリケーションは両組織の仲間からエンドースメントを受け取りました。このトランザクションは Channel/Application/Endorsement ポリシーを満足するので、トランザクションはデフォルトエンドースメン
```suggestion
*Figure 3: クライアントアプリケーションからのトランザクションは、Org1およびOrg2のピアにあるチェーンコードを呼び出しました。チェーンコードの呼び出しは成功し、アプリケーションは両組織のピアからエンドースメントを受け取りました。このトランザクションは Channel/Application/Endorsement ポリシーを満足するので、トランザクションはデフォルトエンドースメントポリシーを満たし、チャネル台帳に加えることができます。*
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +その他のImplicitMetaポリシーの利点としては、組織がチャネルに追加または削除されたときに更新する必要がないことです。 *Figure 3* を例にすると、2つの新しい組織がチャネルに追加された場合、 `Channel/Application/Endorsement` では、トランザクションの検証するために3つの組織からのエンドースメントが必要になります。
```suggestion
その他のImplicitMetaポリシーの利点としては、組織がチャネルに追加または削除されたときにポリシーを更新する必要がないことです。 *Figure 3* を例にすると、2つの新しい組織がチャネルに追加された場合、 `Channel/Application/Endorsement` では、トランザクションの検証するために3つの組織からのエンドースメントが必要になります。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +ImplicitMetaポリシーの欠点は、チャネルのメンバーが使用するSignatureポリシーを明示的に読み込みしないことです(これが暗黙のポリシーと呼ばれる理由です)。その代わり、ユーザーはチャネルの設定を基準にした必須のSignatureポリシーを持っていること想定しています。 `Channel/Application/Endorsement` ポリシーの `rule` は、チャネル内のピ
```suggestion
ImplicitMetaポリシーの欠点は、チャネルのメンバーが使用するSignatureポリシーを明示的に読み込みしないことです(これが暗黙のポリシーと呼ばれる理由です)。代わりに、ユーザーはチャネル設定に基づいた必須のSignatureポリシーを持っていることを想定しています。 `Channel/Application/Endorsement` ポリシーの `rule` は、チャネル内のピア組織の数に基づいています。もし、 *Figure 3* の3つの組織のうち2つが `Endorsement` Signatureポリシーを所有していない場合、どのトランザクションも、 `Channel/Application/Endorsement` ImplicitMetaポリシーを満たすために必要な過半数を得ることはできないでしょう。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +各変更ポリシーは、ImplicitMetaポリシーまたは署名ポリシーを参照することができます。たとえば、デフォルトポリシーを使用する場合、各組織を定義する値は、その組織に関連付けられた `Admins` 署名ポリシーを参照します。その結果、組織はチャネルMSPを更新したり、他のチャネルメンバーからの承認がないアンカーピアを設定したりすることができます。チャネルメンバのセットを定義するアプリケーシ
```suggestion
各変更ポリシーは、ImplicitMetaポリシーまたはSignatureポリシーを参照することができます。たとえば、デフォルトポリシーを使用する場合、各組織を定義する設定値は、その組織に関連付けられた `Admins` Signatureポリシーを参照します。結果として、組織は他のチャネルメンバーからの承認なしに、チャネルMSPを更新したり、アンカーピアを設定したりすることができます。チャネルメンバーのセットを定義するアプリケーショングループの変更ポリシーは、 `Channel/Application/Admins` ImplicitMetaポリシーです。デフォルトポリシーでは、チャネルメンバーの追加または削除を組織の過半数が承認する必要があります。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +チャネル設定内のポリシーは、チャネルによって使用されるFabricリソースへのアクセスを制限するために使用されるアクセス制御リスト [Access Control Lists (ACLs)](../access_control.html) によっても参照されます。ACLは、チャネルのプロセス **processes** を管理するために、チャネル設定内のポリシーを拡張します。 [サンプルの co
```suggestion
チャネル設定内のポリシーは、チャネルによって使用されるFabricリソースへのアクセスを制限するために使用されるアクセス制御リスト [Access Control Lists (ACLs)](../access_control.html) によっても参照されます。ACLは、チャネルの  **processes** (プロセス)を管理するために、チャネル設定内のポリシーを拡張します。 [サンプルの configtx.yaml ファイル](http://github.com/hyperledger/fabric/blob/{BRANCH}/sampleconfig/configtx.yaml) でデフォルトACLを確認できます。各ACLは、パスを使用するチャネルポリシーを参照します。たとえば、次のACLでは、 `/Channel/Application/Writers` ポリシーに基づいてチェーンコードを呼び出すことができるユーザーを制限します。 :
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +*Figure 4: peer/Propose ACLは /Channel/Application/Writers ポリシーによって満たされています。このポリシーは、Writersの署名ポリシーとともに、どの組織からもクライアントアプリケーションが提出したトランザクションで満たすことができます。*
```suggestion
*Figure 4: peer/Propose ACLは /Channel/Application/Writers ポリシーによって満たされます。このポリシーは、Writers Signatureポリシーを用いて、任意の組織のクライアントアプリケーションが送信したトランザクションによって満たすことができます。*
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +デフォルトポリシーを使用する場合、orderer組織の過半数は、オーダリングノードの追加または削除の承認を要求されます。
```suggestion
デフォルトポリシーを使用する場合、orderer組織の過半数がオーダリングノードの追加または削除を承認する必要があります。
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +*Figure 6: チャネルからオーダリングノードを削除するために送信された要求には、ネットワーク内の3つのオーダリング組織からの署名が含まれており、 Channel/Orderer/Admins ポリシーを満たしています。署名は過半数に達する必要がなかったため、Org3チェックは明るい緑色で表示されます。*
```suggestion
*Figure 6: チャネルからオーダリングノードを削除するために送信された要求には、ネットワーク内の3つのオーダリング組織からの署名が含まれており、 Channel/Orderer/Admins ポリシーを満たしています。Org3の署名は過半数を達するために必要としなかったので、チェックマークは明るい緑色で表示されます。*
```

2021-07-29 09:38 UTC, satota2 commented on docs/locale/ja_JP/source/create_channel/channel_policies.md
> +`Channel/Orderer/BlockValidation` ポリシーは、チャネルに追加される新しいブロックがチャネル同意者セットの一部であるオーダリングノードによって生成されたこと、およびブロックが別のピア組織によって改ざんまたは作成されていないことを確認するためにピアによって使用されます。デフォルトでは、 `Writers` 署名ポリシーを持つどのオーダリング組織も、チャネルのためのブ
```suggestion
`Channel/Orderer/BlockValidation` ポリシーは、チャネルに追加される新しいブロックがチャネル同意者セットの一部であるオーダリングノードによって生成されたこと、およびブロックが別のピア組織によって改ざんまたは作成されていないことを確認するためにピアによって使用されます。デフォルトでは、 `Writers` Singnatureポリシーを持つ任意のオーダリング組織が、そのチャネルのためのブロックを作成、検証することができます。
```

2021-07-30 00:13 UTC, satomicchy commented
@satota2 レビューありがとうございます。修正しましたのでご確認お願いいたします。
見直したらすぐわかりそうなミスまで残っていて自分で笑ってしまいました。すみません。

2021-07-30 01:40 UTC, satota2 commented
@satomicchy 修正対応ありがとうございます。修正案を拝見しましたが、ある特定区間のいくつかの指摘が反映されていないようです。Conversation上だと、ソースコードに対するレビューコメントの数が多いと表示が省略されてしまうなので、お気づきにならなかったのかもしれません。反映されていないコメントはUnresolvedの状態で残しましたのでお手数ですがご確認ください。
ちなみにご存知かもしれませんが、Suggested changeはCommit suggestionをすることで取り込むことができます。取り込んだものをローカルにpullして、rebase -iでコミットをまとめる、というやり方のほうが楽かもしれません(ご参考です)。

2021-07-30 16:50 UTC, satomicchy commented
@satota2 ご確認ありがとうございます。反映漏れを追加しました。失礼しました。

Commit suggestionは使ったことありませんでした。ありがとうございます。長らくチーム開発しておらず、Githubに置いていかれてます。

2021-08-02 00:23 UTC, satota2 approved these changes
@satomicchy LGTM!翻訳お疲れ様でした。

2021-08-02 00:23 UTC, merged