[ja_JP] Translate "create_channel_config.md"
hyperledger/fabric-docs-i18n pull request #525
Opened 2021-07-31 22:17 UTC by satomicchy

This patch translates "Tutorials >> Creating a channel >> Using configtx.yaml" into Japanese.

Resolves #206

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2021-08-02 10:23 UTC, shimos requested changes
@satomicchy 翻訳ありがとうございました。細かいのですが、何点か気づいた点をコメントしましたので、ご確認ください。

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +チャネルは、チャネルの初期設定を指定するチャネル作成トランザクションアーティファクトを構築することによって作成されます。チャネル設定( **channel configuration** )は台帳に格納され、チャネルに追加されるすべての後続のブロックを管理します。チャネル設定は、どの組織がチャネルメンバーであるか、チャネルに新しいブロックを追加できるオーダリングノードであるか、チャネルの更新を管
```suggestion
チャネルは、チャネルの初期設定を指定するチャネル作成トランザクションアーティファクトをビルドすることによって作成されます。チャネル設定( **channel configuration** )は台帳に格納され、チャネルに追加されるすべての後続のブロックを管理します。チャネル設定は、どの組織がチャネルメンバーであるか、新しいブロックを追加できるオーダリングノード、チャネルの更新を管理するポリシーなどを指定します。ジェネシスブロックに格納されている初期チャネル設定は、チャネル設定の更新によって更新することができます。十分な数の組織がチャネル更新を承認すると、新しいチャネル設定ブロックはチャネルにコミットされた後に、チャネルを管理するようになります。
```
以降、「ビルド」としているので統一したほうが良いかと思いました。

3文目は、which organizations...がかかってるのは直後だけかと思います。

最後の文は少し自然になるようにしてみました。

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +チャネル作成トランザクションファイルを手動でビルドすることは可能ですが、 `configtx.yaml` ファイルと [configtxgen](../commands/configtxgen.html) ツールを使用してチャネルを作成する方が簡単です。 `configtx.yaml` ファイルには、チャネル設定をビルドするために必要とされる情報が、人間が簡単に読み込み編集できる形式で記述されて
```suggestion
チャネル作成トランザクションファイルを手動でビルドすることは可能ですが、 `configtx.yaml` ファイルと [configtxgen](../commands/configtxgen.html) ツールを使用してチャネルを作成する方が簡単です。 `configtx.yaml` ファイルには、チャネル設定をビルドするために必要とされる情報が、人間が簡単に読み込み編集できる形式で記述されています。 `configtxgen` ツールは、 `configtx.yaml` ファイル内の情報を読み取り、Fabricが読めるプロトコルバッファフォーマット [protobuf format](https://developers.google.com/protocol-buffers) に書き込みます。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +テストネットワークが使用する `configtx.yaml` ファイルは、 `configtx` フォルダにあります。ファイルをテキストエディタで開きます。チュートリアルで各セクションを通す際に、このファイルを参照することができます。Fabricサンプル設定 [Fabric sample configuration](https://github.com/hyperledger/fabric/b
```suggestion
テストネットワークが使用する `configtx.yaml` ファイルは、 `configtx` フォルダにあります。ファイルをテキストエディタで開きます。チュートリアルで各セクションを進む際に、このファイルを参照することができます。Fabricサンプル設定 [Fabric sample configuration](https://github.com/hyperledger/fabric/blob/{BRANCH}/sampleconfig/configtx.yaml) に詳細なバージョンの `configtx.yaml` ファイルがあります。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +テストネットワークによって使用される `configtx.yaml` ファイルには、3つの組織が含まれています。2つは、アプリケーションチャネルに追加することができるOrg1およびOrg2のピア組織です。あと1つは、OrdererOrgというオーダリングサービスの管理者の組織です。ピアノードとオーダリングノードをデプロイするのに別の認証局を使用することがベストプラクティスであるため、同じ企業が運
```suggestion
テストネットワークによって使用される `configtx.yaml` ファイルには、3つの組織が含まれています。2つは、アプリケーションチャネルに追加することができるOrg1およびOrg2のピア組織です。あと1つは、OrdererOrgというオーダリングサービスの管理者の組織です。ピアノードとオーダリングノードをデプロイするのに別の認証局を使用することがベストプラクティスであるため、実際には同じ企業が運用していても、組織はピア組織またはオーダリング組織として参照されます。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +    - Node OUが有効になっているでない場合、MSPには、組織管理者アイデンティティのsigning証明書を含むadmincertsフォルダを含める必要があります。
```suggestion
    - Node OUが有効になっていない場合、MSPには、組織管理者のアイデンティティの署名証明書を含むadmincertsフォルダを含める必要があります。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +`configtx.yaml` ファイルを調べると、次の3つのケーパビリティグループが表示されます。:
```suggestion
`configtx.yaml` ファイルを調べると、次の3つのケーパビリティグループがあります。:
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +- **Orderer** ケーパビリティは、Raft合意形成などのようなオーダリングノードで使用される機能を管理し、チャネ同意者セットに属するオーダリングノードで実行可能なFabricバイナリの最小バージョンを設定します。
```suggestion
- **Orderer** ケーパビリティは、Raft合意形成などのようなオーダリングノードで使用される機能を管理し、チャネル同意者セットに属するオーダリングノードで実行可能なFabricバイナリの最小バージョンを設定します。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +Fabricテストネットワークのピアとオーダリングノードの両方がバージョンv2.xを実行するため、すべてのケーパビリティグループは `v2_0` に設定されます。結果として、テストネットワークは、v2.0よりも低いFabricのバージョンを実行するノードによって連携させることはできません。詳細については、 [capabilities](./capabilities_concept.html) コ
```suggestion
Fabricテストネットワークのピアとオーダリングノードの両方がバージョンv2.xを実行するため、すべてのケーパビリティグループは `v2_0` に設定されます。結果として、テストネットワークは、v2.0よりも低いFabricのバージョンを実行するノードが参加することができません。詳細については、 [capabilities](./capabilities_concept.html) コンセプトトピックを参照してください。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +アプリケーションセクションでは、ピア組織がアプリケーションチャネルとどのようにやりとりすることができるかを管理するポリシーを定義しています。これらのポリシーは、チェーンコード定義を証明するのに必要なピア組織の数、またはチャネル設定の更新に必要な署名の数を管理します。これらのポリシーは、チャネル台帳への書き込みまたはクエリチャネルイベントへのアクセスのような、チャネルリソースへのアクセスを制限する
```suggestion
アプリケーションセクションでは、ピア組織がアプリケーションチャネルとどのようにやりとりすることができるかを管理するポリシーを定義しています。これらのポリシーは、チェーンコード定義を承認するのに必要なピア組織の数、またはチャネル設定の更新に署名する必要のあるピア組織の数を管理します。これらのポリシーは、チャネル台帳への書き込みまたはチャネルイベントのクエリのような、チャネルリソースへのアクセスを制限するためにも使用されます。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +テストネットワークはHyperledger Fabricが提供するデフォルトアプリケーションポリシーを利用しています。デフォルトポリシーを使用する場合、すべてのピア組織は読み込みと書き込みのデータを台帳に送信することができます。また、デフォルトポリシーでは、チャネルメンバーの過半数がチャネル設定の更新を署名し、チェーンコードがチャネルにデプロイされる前にチャネルメンバーの過半数がチェーンコード定
```suggestion
テストネットワークはHyperledger Fabricが提供するデフォルトアプリケーションポリシーを利用しています。デフォルトポリシーを使用する場合、すべてのピア組織は台帳のデータを読み書きすることができます。また、デフォルトポリシーでは、チャネルメンバーの過半数がチャネル設定の更新を署名し、チェーンコードがチャネルにデプロイされる前にチャネルメンバーの過半数がチェーンコード定義を承認することが必要です。このセクションの内容については、 [channel policies](channel_policies.html) チュートリアルで詳しく説明しています。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +各チャネル設定には、チャネル [同意者セット](../glossary.html#consenter-set) のオーダリングノードが含まれます。同意者セットは、新しいブロックを作成し、それをチャネルに結合されたピアへ分散する能力を持つオーダリングノードのグループです。同意者セットのメンバーである各オーダリングノードのエンドポイント情報は、チャネル設定に格納されます。
```suggestion
各チャネル設定には、チャネル [同意者セット](../glossary.html#consenter-set) のオーダリングノードが含まれます。同意者セットは、新しいブロックを作成し、それをチャネルに参加しているピアへ配布する能力を持つオーダリングノードのグループです。同意者セットのメンバーである各オーダリングノードのエンドポイント情報は、チャネル設定に格納されます。
```
用語集では「分散する」になっていますが、ブロックをdistributeするという文脈では、「配布する」でよいと思います。

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +  同意者リストの各オーダリングノードは、エンドポイントの住所とクライアントおよびサーバーのTLS証明書によって識別されます。マルチノードオーダリングサービスをデプロイする場合は、ホスト名、ポート、および各ノードで使用されるTLS証明書へのパスを指定する必要があります。また、各オーダリングノードのエンドポイントアドレスを `Addresses` のリストに追加する必要があります。
```suggestion
  同意者リストの各オーダリングノードは、エンドポイントのアドレスとクライアントおよびサーバーのTLS証明書によって識別されます。マルチノードオーダリングサービスをデプロイする場合は、ホスト名、ポート、および各ノードで使用されるTLS証明書へのパスを指定する必要があります。また、各オーダリングノードのエンドポイントアドレスを `Addresses` のリストに追加する必要があります。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +- `Policies` セクションは、チャネル同意者セットを管理するポリシーを作成します。テストネットワークは、Fabricによって提供されたデフォルトポリシーを使用します。このポリシーでは、orderer管理者の過半数が、オーダリングノードや組織の追加や削除、または削減パラメータブロックに対する更新について、承認する必要があります。
```suggestion
- `Policies` セクションは、チャネル同意者セットを管理するポリシーを作成します。テストネットワークは、Fabricによって提供されたデフォルトポリシーを使用します。このポリシーでは、orderer管理者の過半数が、オーダリングノードや組織の追加や削除、またはブロック作成パラメータに対する更新について、承認する必要があります。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +チャネルセクションでは、チャネル設定の最高レベルを管理するするポリシーを定義しています。アプリケーションチャネルの場合、これらのポリシーはハッシュ・アルゴリズム、新しいブロックの作成に使用されるデータ・ハッシュ構造、およびチャネルケイパビリティレベルを管理します。システム・チャネルでは、これらのポリシーはピア組織のコンソーシアムの作成または削除も管理します。
```suggestion
チャネルセクションでは、チャネル設定の最高レベルを管理するポリシーを定義しています。アプリケーションチャネルの場合、これらのポリシーはハッシュ・アルゴリズム、新しいブロックの作成に使用されるデータ・ハッシュ構造、およびチャネルケイパビリティレベルを管理します。システム・チャネルでは、これらのポリシーはピア組織のコンソーシアムの作成または削除も管理します。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +システムチャネルは、オーダリングサービスのノードと、オーダリングサービス管理者である組織のセットを定義します。システムチャネルには、ブロックチェーンコンソーシアム [consortium](../glossary.html#consortium) に属するのピア組織セットも含まれます。コンソーシアムの各メンバーのチャネルMSPはシステムチャネルに含まれているため、新しいアプリケーションチャネルを
```suggestion
システムチャネルは、オーダリングサービスのノードと、オーダリングサービス管理者である組織のセットを定義します。システムチャネルには、ブロックチェーンコンソーシアム [consortium](../glossary.html#consortium) に属するピア組織セットも含まれます。コンソーシアムの各メンバーのチャネルMSPはシステムチャネルに含まれているため、新しいアプリケーションチャネルを作成し、新しいチャネルにコンソーシアムメンバーを追加することができます。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +`TwoOrgsChannel` は、テストネットワークシステムチャネルが主催する `SampleConsortium` というコンソーシアムの名前を提供しています。その結果、 `TwoOrgsOrdererGenesis` プロファイルで定義されたオーダリングサービスはチャネル同意者セットとなります。 `Application` セクションでは、両方のコンソーシアムの組織(Org1とOrg2)
```suggestion
`TwoOrgsChannel` は、テストネットワークシステムチャネルがホストする `SampleConsortium` というコンソーシアムの名前を提供しています。その結果、 `TwoOrgsOrdererGenesis` プロファイルで定義されたオーダリングサービスはチャネル同意者セットとなります。 `Application` セクションでは、両方のコンソーシアムの組織(Org1とOrg2)がチャネルメンバーとして含まれます。チャネルは `V2_0` をアプリケーションケーパビリティとして使用し、ピア組織がチャネルとどのようにやりとりするかを管理するために、 **Application** セクションのデフォルトポリシーを使用します。また、アプリケーションチャネルは **Channel** セクションのデフォルトポリシーを使用し、チャネルケーパビリティレベルとして `V2_0` を有効にします。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +プロファイルは、 `configtx.yaml` ファイル内の2つのピア組織(Org1とOrg2)を含む `SampleConsortium` という名前のコンソーシアムを作成します。プロファイルの `Orderer` セクションは、ファイルの **Orderer:** セクションで定義された単一ノードRaftオーダリングサービスを使用します。 **Organizations:** セクションの
```suggestion
プロファイルは、 `configtx.yaml` ファイル内の2つのピア組織(Org1とOrg2)を含む `SampleConsortium` という名前のコンソーシアムを作成します。プロファイルの `Orderer` セクションは、ファイルの **Orderer:** セクションで定義された単一ノードRaftオーダリングサービスを使用します。 **Organizations:** セクションのOrdererOrgは、オーダリングサービスの唯一の管理者となります。唯一のオーダリングノードがFabric 2.xを運用しているため、ordererシステムチャネルケーパビリティを `V2_0` に設定することができます。システムチャネルは、 **Channel** セクションのデフォルトポリシーを使用し、チャネルケーパビリティレベルとして `V2_0` を有効にします。
```

2021-08-02 10:23 UTC, shimos commented on docs/locale/ja_JP/source/create_channel/create_channel_config.md
> +Fabricチャネルは、Hyperledger Fabricの異なるバージョンを実行しているordererとピアノードを追加させることができます。チャネルケイパビリティは、特定の機能のみを有効にすることによって、異なるFabricバイナリを実行している組織を同じチャネルに参加するのを許可します。たとえば、Fabric V1.4を実行している組織とFabric v2.xを実行している組織は、チャネ
```suggestion
Fabricチャネルは、Hyperledger Fabricの異なるバージョンを実行しているordererとピアノードを追加させることができます。チャネルケイパビリティは、特定の機能のみを有効にすることによって、異なるFabricバイナリを実行している組織を同じチャネルに参加するのを許可します。たとえば、Fabric v1.4を実行している組織とFabric v2.xを実行している組織は、チャネルケイパビリティレベルがV1_4_X以下に設定されている限り、同じチャネルに参加できます。どのチャネルメンバーもFabric v2.0で導入された機能は使用できません。
```

2021-08-02 22:15 UTC, satomicchy commented
@shimos レビューありがとうございます！よくわからずに翻訳している部分も実はありますので、細かく見ていただいて助かります。修正しましたので、ご確認よろしくお願いいたします。

2021-08-03 06:04 UTC, shimos approved these changes
@satomicchy 修正ありがとうございました。LGTM

2021-08-03 06:05 UTC, merged