[ja_JP] Translate source/config_update.md into Japanese
hyperledger/fabric-docs-i18n pull request #559
Opened 2021-10-06 11:49 UTC by satota2

This patch translates source/config_update.md into Japanese.

Resolves #209

2021-10-06 13:52 UTC, justin-themedium commented
ko_KR locale has been added so docs/readthedocs.org:fabric-docs-i18n-ko-kr — Read the Docs build failed.
Please rebase your working branch on the latest.

2021-10-08 07:04 UTC, shimos requested changes
@satota2 翻訳ありがとうございます。細かい点ですが、いくつかコメントしましたので、確認をお願いいたします。

2021-10-08 07:04 UTC, shimos commented on docs/locale/ja_JP/source/config_update.md
> +しかし、後述するように、この概念的な単純さは、やや複雑なプロセスに包まれています。そのため、ユーザーによっては、設定更新を取得、翻訳、スコープに収めるというプロセスをスクリプト化することを選ぶかもしれません。
```suggestion
しかし、後述するように、この概念的な単純さは、やや複雑なプロセスに包まれています。そのため、ユーザーによっては、設定更新を取得、変換、スコープに収めるというプロセスをスクリプト化することを選ぶかもしれません。
```
上には「変換」となっていましたし、意味的にも統一したほうがいいと思います。

2021-10-08 07:04 UTC, shimos commented on docs/locale/ja_JP/source/config_update.md
> +現在、Fabricのコマンドラインはデフォルトで「それを渡す (pass it along)」システムになっています。つまり、設定更新を提案する組織の管理者は、署名が必要な他の人 (通常は別の管理者) にその更新を送ります。
```suggestion
現在、Fabricのコマンドラインはデフォルトで「順番に渡していく」システムになっています。つまり、設定更新を提案する組織の管理者は、署名が必要な他の人 (通常は別の管理者) にその更新を送ります。
```
以降で説明されているように、物などを順番に回していく、回覧みたいなイメージがpass (sth) alongだと思いますので、そこがわかるように訳したほうがいいかなと思いました。自分でもあまりいい表現が思いつかなかったので、上記は参考です。

参考: https://dictionary.cambridge.org/dictionary/english/pass-sth-on-along-to-sb

2021-10-08 07:04 UTC, shimos commented on docs/locale/ja_JP/source/config_update.md
> +これにより、設定更新を作成した管理者の作業が少し難しくなりますが (署名者ごとにファイルを処理するように強制する)、Fabric管理アプリケーションを開発しているユーザーに推奨されるワークフローです。
```suggestion
これにより、設定更新を作成した管理者の作業が少し難しくなりますが (署名者ごとにファイルを処理しなければならない)、Fabric管理アプリケーションを開発しているユーザーに推奨されるワークフローです。
```
forceですが、もう少し弱く表現したほうが自然かなと思いました。

2021-10-08 07:04 UTC, shimos commented on docs/locale/ja_JP/source/config_update.md
> +設定更新トランザクションは、の設定と修正された設定の差分を表しますが、オーダリングサービスはこれを完全なチャンネル設定に変換します。
```suggestion
設定更新トランザクションは、元の設定と修正された設定の差分を表しますが、オーダリングサービスはこれを完全なチャネル設定に変換します。
```

2021-10-08 07:04 UTC, shimos commented on docs/locale/ja_JP/source/config_update.md
> +アプリケーションチャンネルの設定ファイルが取得・スコープされた後にどのようになるかを確認するには、以下の **ここをクリックして設定を確認してください** をクリックしてください。
```suggestion
アプリケーションチャネルの設定ファイルが取得・スコープされた後にどのようになるかを確認するには、以下の **ここをクリックして設定を確認してください** をクリックしてください。
```
以下でも、いくつか「チャンネル」表記があるようですので、統一したほうがよいと思います。

2021-10-08 07:19 UTC, satota2 commented on docs/locale/ja_JP/source/config_update.md
> +現在、Fabricのコマンドラインはデフォルトで「それを渡す (pass it along)」システムになっています。つまり、設定更新を提案する組織の管理者は、署名が必要な他の人 (通常は別の管理者) にその更新を送ります。
ありがとうございます。よい表現が思いつかず悩ましかったのでアドバイス助かります。

2021-10-08 07:36 UTC, satota2 commented
@shimos コメントをベースに修正しましたので確認お願いいたします。

2021-10-08 08:07 UTC, shimos approved these changes
@satota2 Thank you. LGTM!

2021-10-08 08:07 UTC, merged