finished create a channel translation
hyperledger/fabric-docs-i18n pull request #61
Opened 2020-08-02 06:32 UTC by sc1000y

#58

2020-08-02 07:27 UTC, davidkhala commented on docs/locale/zh_CN/source/CONTRIBUTING.rst
> +- 展示PR审查记录（审查的质量和数量）
Demonstrated 这里不是作为动词使用的，而是类似于proven, obvious
表示有说服力的意思

2020-08-02 07:27 UTC, davidkhala commented on docs/locale/zh_CN/source/CONTRIBUTING.rst
>  作为一个作者或者信息开发者：
信息开发者怎么回事？这个也机翻了

2020-08-02 07:31 UTC, davidkhala commented on docs/locale/zh_CN/source/CONTRIBUTING.rst
> +- 运用你在Fabric的经验更新文档，提升已存在的话题，创建新的话题。修改文档是开始成为贡献者，
“改进已存在的话题”
“修改文档是开始成为贡献者的捷径”

2020-08-02 07:32 UTC, davidkhala commented on docs/locale/zh_CN/source/CONTRIBUTING.rst
> +- 能够指导项目工作和贡献者
这三条都是一样的问题

2020-08-02 07:38 UTC, davidkhala commented on docs/locale/zh_CN/source/create_channel/create_channel_overview.rst
> +证书颁发机构构成物理基础网络中，通道是组织间和组织内部交流的过程。
CA 可以先不翻译，避免多次翻译产生的歧义
或者将这个翻译标注为专有名词，比如用 _斜体_

2020-08-02 07:39 UTC, davidkhala requested changes
有几个问题看一下

2020-08-02 08:46 UTC, davidkhala commented
LGTM, only conflicts remain.

2020-08-04 13:07 UTC, davidkhala submitted a review, later dismissed

2020-08-04 13:09 UTC, davidkhala commented on docs/locale/zh_CN/source/create_channel/create_channel_overview.rst
> +CA构成物理基础网络中，通道是组织间和组织内部交流的过程。
构成的

2020-08-05 06:15 UTC, sc1000y commented
![image](https://user-images.githubusercontent.com/8299176/89378267-09b7f000-d726-11ea-90e3-7ace9316f527.png)
你那是不是有squash and merge?

2020-08-05 08:18 UTC, closed without merging