[ja_JP] update index.rst
hyperledger/fabric-docs-i18n pull request #63
Opened 2020-08-04 04:50 UTC by satomicchy

#42 translated index.rsg for the first time

Signed-off-by: satomicchy <satomi.t.sora@gmail.com>

2020-08-04 20:52 UTC, nhoriguchi requested changes
I left one terminology-related comment, could you fix it?

2020-08-04 20:52 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/index.rst
> +幅広い業界ユースケースに対してモジュール性と汎用性を提供する、エンタープライズクラスの許可された分散型元帳プラットフォームです。
"permissioned distributed ledger" は「許可型の分散台帳」あたりの訳語が妥当だと思います。

2020-08-08 09:25 UTC, satomicchy commented
@Naoya-Horiguchi レビューありがとうございます。修正しました。
確認せずgit commit --amend からの -f でpushしてしまいましたが、よかったでしょうか？
もしガイドに沿わないなどありましたらご教授お願いいたします。

2020-08-09 16:45 UTC, nhoriguchi approved these changes
ありがとうございました。

> 確認せずgit commit --amend からの -f でpushしてしまいましたが、よかったでしょうか？

はい、その方法が良いと思います。

2020-08-09 16:46 UTC, merged