【zh_CN】Docs » MSP Identity Validity Rules && 【zh_CN】Docs » 术语表
hyperledger/fabric-docs-i18n pull request #631
Opened 2021-12-17 07:32 UTC by cloud1230

solve issue #439 and #440
Signed-off-by: zhangziyi <cloud1230@hotmail.com>

2021-12-20 01:10 UTC, cloud1230 commented
@davidkhala Thank you for reviewing.

2021-12-20 01:28 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +新的Fabric链码生命周期作为Fabirc v2.0的一部分被引入，
不通顺，建议重新组织语序

2021-12-20 01:30 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +掌管何时一个条目被认为已提交。这不是一种特殊的排序节点**类型**。
排序节点的“特殊类型”

2021-12-20 01:31 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +掌管何时一个条目被认为已提交。这不是一种特殊的排序节点**类型**。
“掌管何时一个条目被认为已提交” 不通顺

2021-12-20 01:33 UTC, davidkhala commented
@cloud1230 不通顺和机翻痕迹很明显，并且比较多，在此不一一列举了，建议先自检一下

2021-12-20 01:52 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +新的Fabric链码生命周期作为Fabirc v2.0的一部分被引入，
是否可以改为：
当前用于启动通道上链码的流程中，
引入了新的Fabric链码生命周期作为Fabirc v2.0的一部分新特性，

2021-12-20 01:55 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +掌管何时一个条目被认为已提交。这不是一种特殊的排序节点**类型**。
考虑改为：管理一个条目被认为已提交的具体时间。这不是排序节点的一种**特殊类型**。

2021-12-20 02:02 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +新的Fabric链码生命周期作为Fabirc v2.0的一部分被引入，
Typo: Fabirc -> Fabric
建议改成类似“在Fabric 2.0中，引入了新的Fabric链码生命周期，更新了通道内链码启动的步骤，详情参考...”

2021-12-20 02:35 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +新的Fabric链码生命周期作为Fabirc v2.0的一部分被引入，
明白。已按照要求修正。

2021-12-20 02:35 UTC, cloud1230 commented
> @cloud1230 不通顺和机翻痕迹很明显，并且比较多，在此不一一列举了，建议先自检一下

好的，已经重新自检并修正。

2021-12-21 11:37 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +其他排序节点没有，这是由当时情况决定的。
语句不通

2021-12-21 11:39 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +排序节点leader到followers间是分布式的。
语句不通

2021-12-21 11:49 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +包含绑定到每个 Member_ 的加密身份资料。
不通顺

2021-12-21 11:49 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +集群中所需要确认交易提案的最小成员数。
不通顺

2021-12-21 11:51 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +的 `etcd数据库 <https://coreos.com/etcd/>`_ 的
虽然本质上也有一些nosql的功能，但是文本翻译成数据库有歧义

2021-12-21 11:53 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +其决策被followers复制。
不通顺

2021-12-21 11:53 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +并且它们的设计允许组织提供作为分布式排序服务一部分的节点。
不通顺

2021-12-21 11:57 UTC, davidkhala commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +那么MSP的配置必须不能包括CRL中也包括的任何iCA，否则MSP将设置失败。
语句不通

2021-12-21 11:58 UTC, davidkhala commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +默认的MPS实现接受由合适的权威机构签署的有效身份X.509证书。
MPS，原文打错了，应该是MSP

2021-12-22 02:01 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +其他排序节点没有，这是由当时情况决定的。
修改为：它是由特定情况下决定的，有且仅有一个排序节点在特定时刻可能拥有的特定角色。

2021-12-22 02:07 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +排序节点leader到followers间是分布式的。
修改为：日志条目作为Raft排序服务中的主要工作单元，它以分布式的方式存在于
排序节点的leader和followers。

2021-12-22 02:16 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +的 `etcd数据库 <https://coreos.com/etcd/>`_ 的
是否应该翻译为 etcd分布型数据库

2021-12-22 02:18 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +其决策被followers复制。
修改为：Raft遵循“leader和follower”模型，
该模型在每个通道都选出一个leader节点，followers复制leader节点的决策。

2021-12-22 02:22 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +并且它们的设计允许组织提供作为分布式排序服务一部分的节点。
修改为：Raft排序服务比基于kafka的排序服务应该更容易设置和管理，
它们的设计允许组织里的节点作为分布式排序服务一部分。

2021-12-22 02:38 UTC, cloud1230 commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +那么MSP的配置必须不能包括CRL中也包括的任何iCA，否则MSP将设置失败。
修改为：**一个正确** 的MSP的rCAs或iCAs必须为一个MSP的iCA证书签名。
一个MSP配置可能包含一个证书撤销列表，又名CRL。
如果在CRL中列出了任何MSP的根证书颁发机构，
那么MSP配置必定不能包括CRL中的任何iCA，否则MSP将设置失败。

2021-12-22 05:10 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +排序节点leader到followers间是分布式的。
@cloud1230 这里我忘了写我想表达的意思，原文中的distributed我理解不是分布式，而是`被分发`的意思

2021-12-22 05:11 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +的 `etcd数据库 <https://coreos.com/etcd/>`_ 的
etcd库，就行

2021-12-22 05:13 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +并且它们的设计允许组织提供作为分布式排序服务一部分的节点。
它的设计允许各组织贡献出节点来组成分布式排序服务。

2021-12-22 06:45 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +排序节点leader到followers间是分布式的。
好的，那修改为：日志条目是Raft排序服务中的主要工作单元，排序节点的leader将它分发给其他followers。这样？

2021-12-22 06:53 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +包含绑定到每个 Member_ 的加密身份资料。
它的设计目的并不仅是作为Kafka和Raft的变形，更是为了支持可插拔的实现。
它是一种对整个网络的普遍联系;它包含绑定到每个 Member_ 的加密身份资料。

2021-12-22 07:56 UTC, cloud1230 commented on docs/locale/zh_CN/source/glossary.rst
> +集群中所需要确认交易提案的最小成员数。
修改为：它指定了集群中需要确认交易提案以对交易进行排序的最小成员数。

2021-12-24 07:29 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +管理具体何时认为一个条目已被提交。这不是排序节点的一种**特殊类型**。
管理具体何时认为一个条目已被提交 -> 管理消息提交的时机

2021-12-24 07:33 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +完整的这些条目序列被认为是“日志”。
一个完整的。。。，我们称之为“日志”

2021-12-24 07:35 UTC, davidkhala commented on docs/locale/zh_CN/source/glossary.rst
> +它的设计目的并不仅是作为Kafka和Raft的变形，更是为了支持可插拔的实现。
“的变形” 语句不通

2021-12-31 04:05 UTC, davidkhala commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +**一个正确** 的MSP的rCAs或iCAs必须为一个MSP的iCA证书签名。
这里不是一个正确，而是`有且仅有一个`的意思

2021-12-31 04:23 UTC, davidkhala commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +如果证书C是由在MSP配置中已经为其指定了组织单元的iCA或rCA签名的，
如果证书C是由iCA或rCA签名的，而后者的OU已经指定于MSP配置中

2022-01-23 03:42 UTC, davidkhala commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +MSP 身份有效性规则
身份校验规则

2022-01-23 03:45 UTC, davidkhala commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +MSP 身份有效性规则
或者不改也行

2022-01-23 03:47 UTC, davidkhala commented on docs/locale/zh_CN/source/msp-identity-validity-rules.rst
> +在MSP配置中，一个组织单元被细化为一对值(parent-cert, ou-string)，
对值(parent-cert, ou-string) --> `对值，比如说(parent-cert, ou-string)`

2022-01-23 03:49 UTC, davidkhala requested changes
基本OK了，还差一点

2022-04-09 17:38 UTC, closed without merging