[ja_JP] translate gateway.md into Japanese · hyperledger/fabric-docs-i18n
hyperledger/fabric-docs-i18n pull request #635
Opened 2022-01-05 09:50 UTC by dnakashima

Signed-off-by: Daiki Nakashima Nakashima.Daiki@df.MitsubishiElectric.co.jp

Resolve #227

2022-01-05 10:54 UTC, shimos requested changes
@dnakashima 翻訳ありがとうございました！
細かい点になってしまいますが、いくつかコメントをしましたのでご確認いただけますでしょうか。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +最後に、アプリケーションは、同じもしくは異なるネットワークで複数のゲートウェイを定義出来ます。さらに、アプリケーションは名目上、静的且つ動的なゲートウェイを使用出来ます。
```suggestion
最後に、アプリケーションは、同じもしくは異なるネットワークで複数のゲートウェイを定義出来ます。さらに、アプリケーションは同じゲートウェイを静的にも動的にも使用出来ます。
```
原文の意味が通じてない気がするのですが、文脈的には"applications can use the **same** gateway both statically and dynamically"のtypoだと思われますので、それを踏まえると上記のような形でいかがでしょうか。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +もし[サービスディスカバリ](../discovery-overview.html)がアプリケーションで選択されている場合、ゲートウェイファイルで定義されるトポロジは、サービスディスカバリによって拡張されていきます。サービスディスカバリはゲートウェイ定義から始まり、[ゴシッププロトコル]](../gossip.html)を用いて、MagnetoCorp組織内にある全てのピアとordererを見つ
```suggestion
もし[サービスディスカバリ](../discovery-overview.html)がアプリケーションで選択されている場合、ゲートウェイファイルで定義されるトポロジは、サービスディスカバリによって拡張されていきます。サービスディスカバリはゲートウェイ定義から始まり、[ゴシッププロトコル](../gossip.html)を用いて、MagnetoCorp組織内にある全てのピアとordererを見つけ出します。もし[アンカーピア](../glossary.html#anchor-peer)がチャネル内で設定されている場合、サービスディスカバリは接続している他組織のコンポーネントを見つけ出すために、組織を越えてゴシッププロトコルを用います。この処理は、チャネルレベルで定義されピアにインストールされているスマートコントラクトとそれらに紐づくエンドースメントポリシーも見つけ出します。静的ゲートウェイと同様に、見つけ出したネットワークは、コマーシャルペーパートランザクションがエンドースされ分散されるのに十分である必要があります。
```

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +ゲートウェイは、ビジネスロジック開発に注力するために、アプリケーションの代理としてネットワークやりとりを管理するものです。アプリケーションはゲートウェイに接続し、それに続く全てのネットワークやりとりはゲートウェイの構成により管理されます。
```suggestion
ゲートウェイは、ビジネスロジック開発に注力するために、アプリケーションの代理としてネットワークでのやりとりを管理するものです。アプリケーションはゲートウェイに接続し、それに続く全てのネットワークやりとりはゲートウェイの構成により管理されます。
```
何か助詞があったほうが自然な気がします。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +Hyperledger Fabricネットワークのチャネルは継続的に変更が可能です。ネットワーク内の異なる組織に存在するピア、ordererとCAは、絶えず入れ替わります。それは、ビジネス需要の変化や計画済みもしくは計画されていないシステム停止に柔軟に対応するためです。その様なビジネス課題を解決することに専念するために、ゲートウェイはアプリケーション開発の負担を減らします。
```suggestion
Hyperledger Fabricネットワークのチャネルは常に変化することがあります。ネットワーク内の異なる組織に存在するピア、ordererとCAは、絶えず入れ替わります。それは、ビジネス需要の変化や計画済みもしくは計画されていないシステム停止に柔軟に対応するためです。ビジネス課題を解決することに専念するために、ゲートウェイはアプリケーション開発の負担を減らします。
```
最初の文は「できる」というよりも「することがある」の意味かなと思いますので、上記のような形ではいかがでしょうか。また、「その様な」は原文にないですし、直接訳文でも指しているものが表れていないので、ないほうが混乱しないかなと思ったのですがいかがでしょうか。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +  SDKは、トランザクション送信と通知プロセスを管理するために、ゲートウェイ[コネクションオプション](./connectionoptions)を用いる接続において、この静的トポロジを使用します。コネクションプロファイルは、ゲートウェイがネットワークチャネル、組織、orderer、ピアやそれらのロールの代わりにアプリケーションとのやり取りを実施するために、ネットワークトポロジを含む必要がありま
```suggestion
  SDKは、トランザクション送信と通知プロセスを管理するために、ゲートウェイ[コネクションオプション](./connectionoptions.html)とともに、この静的トポロジを使用します。コネクションプロファイルは、ゲートウェイがアプリケーションの代わりにネットワークとのやり取りを実施するために十分なネットワークトポロジ、つまり、ネットワークチャネル、組織、orderer、ピアやそれらのロールなどを含む必要があります。
```
一部係り受けがおかしな場所がありましたので、原文に沿う形に入れ替えましたがいかがでしょうか。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +  SDKは、トランザクション送信と通知プロセスを管理するために、ゲートウェイコネクションオプションを用いる接続において、静的で既知の全てのトポロジ情報を使用します。その中で、インテリジェントに既知のトポロジを使用します。例えば、スマートコントラクトのエンドースメントポリシーを実行する際に必要な最少のエンド―シングピアを*算出* します。
```suggestion
  SDKは、トランザクション送信と通知プロセスを管理するために、ゲートウェイコネクションオプションとともに、静的及び見つかった全てのトポロジ情報を使用します。その中で、インテリジェントに見つかったトポロジを使用します。例えば、スマートコントラクトのエンドースメントポリシーを実行する際に必要な最少のエンド―シングピアを*算出* します。
```
discoveredは、サービスディスカバリによって、新たに見つかったというイメージだと思いますので、「既知」よりは「新たに見つかった」「発見した」のような感じのほうがわかりやすいと思うのですがいかがでしょうか。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +どちらの形式のゲートウェイもアプリケーションに対して透明性をもたらします。アプリケーションのプログラム設計は、静的・動的ゲートウェイのどちらを使用したとしても変わりません。これは、アプリケーションはサービスディスカバリを使用する場合もあれば使用しない場合もあることを意味します。一般的に、SDKにより動的ディスカバリを使用することで定義量を少なく出来、インテリジェントに動作出来ます。これがデフォル
```suggestion
どちらの形式のゲートウェイもアプリケーションに対しては透過的です。アプリケーションのプログラム設計は、静的・動的ゲートウェイのどちらを使用したとしても変わりません。これは、アプリケーションはサービスディスカバリを使用する場合もあれば使用しない場合もあることを意味します。一般的に、SDKにより動的ディスカバリを使用することで定義量を少なく出来、インテリジェントに動作出来ます。これがデフォルトです。
```
意識する必要がないという意味でのtransparentは、透過のほうが一般的かなと思います。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +* **コネクションプロファイル**: `コネクションプロファイル`は、SDKによるトランザクション処理で使用されるゲートウェイの設定です。具体的には、静的もしくは動的かを設定します。YAMLもしくはJSONの形式で記載し、ゲートウェイに渡す際はJSONオブジェクトに変換する必要があります。:
```suggestion
* **コネクションプロファイル**: `コネクションプロファイル`は、静的か動的かに関わらず、SDKによるトランザクション処理で使用されるゲートウェイの設定です。YAMLもしくはJSONの形式で記載し、ゲートウェイに渡す際はJSONオブジェクトに変換する必要があります。:
```
サービスディスカバリを使うかどうかを決めるのはコネクションオプションのほうなので、このwhetherは「どちらにせよ」の意味と思われます。

2022-01-05 10:54 UTC, shimos commented on docs/locale/ja_JP/source/developapps/gateway.md
> +静的なゲートウェイは、固定のネットワークビューを定義します。MagnetoCorp [scenario](#scenario)において、ゲートウェイはMagnetoCorpの1つのピア、DigiBankの1つのピアとMagentoCorpのordererを識別します。もう1つの方法として、ゲートウェイは、MagnetoCorpとDigiBankの*全ての* ピアとordererを定義します。どち
```suggestion
静的なゲートウェイは、固定のネットワークビューを定義します。MagnetoCorp [scenario](#scenario)において、ゲートウェイはMagnetoCorpの1つのピア、DigiBankの1つのピアとMagentoCorpのordererを識別します。もう1つの方法として、ゲートウェイは、MagnetoCorpとDigiBankの*全ての* ピアとordererを定義します。どちらの方法でも、コマーシャルペーパートランザクションがエンドースされ分散されるのに十分なネットワークビューをゲートウェイは定義しなければなりません。
```

2022-01-12 03:02 UTC, dnakashima reviewed
Signed-off-by: Daiki Nakashima <Nakashima.Daiki@df.MitsubishiElectric.co.jp>

2022-01-12 07:47 UTC, shimos approved these changes
@dnakashima 修正ありがとうございました！ LGTM

2022-01-12 07:48 UTC, merged