[ja_JP] Architecture Reference » Peer channel-based event services
hyperledger/fabric-docs-i18n pull request #656
Opened 2022-04-13 08:15 UTC by dnakashima

https://github.com/hyperledger/fabric-docs-i18n/issues/567

#567

2022-04-14 08:46 UTC, shimos requested changes
@dnakashima 翻訳ありがとうございます。気になった点をいくつかコメントしましたので、ご確認ください。よろしくお願いいたします。

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +.. 注釈:: もし相互TLSがピアで有効になっていた場合、TLS証明書のハッシュ値をエンベロープのチャネルヘッダーに設定しなければなりません。
```suggestion

.. note:: もし相互TLSがピアで有効になっていた場合、TLS証明書のハッシュ値をエンベロープのチャネルヘッダーに設定しなければなりません。
```
noteの部分は訳してしまうと、正常にhtmlが出力されないようです。

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +.. 注釈:: チェーンコードイベントのペイロードはフィルタードブロックに含まれません。
```suggestion

.. note:: チェーンコードイベントのペイロードはフィルタードブロックに含まれません。
```
l.31と同様です。

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +Fabricの過去バージョンにおいて、ピアイベントサービスはイベントハブとして知られていました。このサービスは、チャネルに関わらず新しいブロックがピアの台帳に追加された際にイベントを送信し、イベンティングピアを稼働させている組織（i.e., イベントを受信する組織）のメンバのみがアクセスすることが出来ます。
```suggestion
Fabricの過去バージョンにおいて、ピアイベントサービスはイベントハブとして知られていました。このサービスは、チャネルに関わらず新しいブロックがピアの台帳に追加された際にイベントを送信し、イベンティングピア（すなわちイベントのために接続されているピア）を稼働させている組織のメンバのみがアクセスすることが出来ます。
```

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +v1.1から、イベントを提供する新しいサービスがあります。これらのサービスは、各チャネルをベースにしたイベント提供とは全く異なる設計となっています。これは、ピアのデータへのきめ細かい制御を実現するために、ピアではなくチャネルのレベルでイベントの登録が実施されます。イベントを受信するリクエストは、（チャネル設定で定義された）ピアの組織外のアイデンティティを元に受け付けられます。これはより良い信頼性
```suggestion
v1.1から、イベントを提供する新しいサービスがあります。これらのサービスは全く異なる設計となっており、各チャネルをベースにしたイベント提供を行います。これは、ピアのデータへのきめ細かい制御を実現するために、ピアではなくチャネルのレベルでイベントの登録が実施されます。イベントを受信するリクエストは、そのピアの組織とは関係なく、（チャネル設定で定義される通り）アイデンティティを元に受け付けられます。これはより良い信頼性と（接続上の問題や、ピアが既に動いているネットワークに参加するかに関係なく）届かなかったイベントを受信する方法も提供します。
```

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +このサービスは、 ``Deliver`` サービスと同じデータを送信し、アクセス可能なことをクライアントの組織で認証したコレクションのプライベートデータを追加で含めることが出来ます。
```suggestion
このサービスは、 ``Deliver`` サービスと同じデータに加えて、クライアントの組織がアクセスを許可されたコレクションのプライベートデータを含めて送信します。
```

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +このサービスは、台帳にコミットされたブロックに関する情報の最小セットである "フィルターされた" ブロックを送信します。ピアの所有者が外部のクライアントから受信したトランザクションやトランザクションの状態に関する情報をネットワークで使用することを目的としています。もしチェーンコードによって設定されたイベントであれば、フィルタードブロックの ``FilteredChaincodeAction``
```suggestion
このサービスは、台帳にコミットされたブロックに関する情報の最小セットである "フィルターされた" ブロックを送信します。外部のクライアントがそのクライアントのトランザクションやトランザクションの状態に関する情報を主に使いたい、とピアの所有者が望むようなネットワークで使用することを目的としています。もしチェーンコードによって設定されたイベントであれば、フィルタードブロックの ``FilteredChaincodeAction`` に格納されます。
```

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +イベントの登録は、スタートとストップの位置、依頼の挙動（レディでなければレディもしくはフェイルになるブロック）を含むピアへの配信依頼情報メッセージを含むエンベロープを送信することで完了します。ヘルパー変数として ``SeekOldest`` と ``SeekNewest`` があり、台帳の一番古い（i.e. 最初の）ブロックもしくは最新の（i.e. 最後の）ブロックを示します。無制限にサービスを
```suggestion
イベントの登録は、スタートとストップの位置、シークの挙動（利用可能になるまでブロックするか、利用できなければ失敗するか）を含むピアへの配信シーク情報メッセージを含むエンベロープを送信することで完了します。ヘルパー変数として ``SeekOldest`` と ``SeekNewest`` があり、台帳の一番古い（すなわち最初の）ブロックもしくは最新の（すなわち最後の）ブロックを示します。サービスに無制限に送信させるには、 ``SeekInfo`` メッセージのストップ位置を ``MAXINT64`` にする必要があります。
```
i.e.は、すなわちと訳したほうが一般にわかりやすいかなと思います。

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +デフォルトでイベントサービスは、イベントをリクエストするクライアントを認証するかどうかを決めるためにチャネルリーダポリシーを使用します。
```suggestion
デフォルトでイベントサービスは、イベントをリクエストするクライアントを許可するかどうかを決めるために、チャネルのReadersポリシーを使用します。
```

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> + * ステータス -- HTTPステータスコード。 各サービスは、エラーが発生した場合、適切なエラーコードを返します。一方で、 ``SeekInfo`` メッセージによってリクエストされた全情報の送信をサービスが完了すると一度だけ ``200 - SUCCESS`` を返します。
```suggestion
 * ステータス -- HTTPステータスコード。 各サービスは、エラーが発生した場合、適切なエラーコードを返します。そうでない場合、 ``SeekInfo`` メッセージによってリクエストされた全情報の送信をサービスが完了すると``200 - SUCCESS`` を返します。
```

2022-04-14 08:46 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +        * 記載されたペイロードとトランザクションに対するチェーンコードイベント
```suggestion
        * トランザクションに対するチェーンコードイベント (ただしペイロードは消去)
```

2022-04-21 03:12 UTC, dnakashima reviewed
[ja_JP] translate peer_event_services.rst into Japanese

#567

Signed-off-by: Daiki Nakashima Nakashima.Daiki@df.MitsubishiElectric.co.jp

2022-04-21 03:13 UTC, dnakashima reviewed
[ja_JP] translate peer_event_services.rst into Japanese

#656 

Signed-off-by: Daiki Nakashima Nakashima.Daiki@df.MitsubishiElectric.co.jp

2022-04-21 03:17 UTC, dnakashima reviewed
[ja_JP] translate peer_event_services.rst into Japanese

https://github.com/hyperledger/fabric-docs-i18n/issues/567

Signed-off-by: Daiki Nakashima [Nakashima.Daiki@df.MitsubishiElectric.co.jp](mailto:Nakashima.Daiki@df.MitsubishiElectric.co.jp)

2022-04-21 03:18 UTC, dnakashima reviewed
[ja_JP] translate peer_event_services.rst into Japanese

https://github.com/hyperledger/fabric-docs-i18n/issues/567

Signed-off-by: Daiki Nakashima [Nakashima.Daiki@df.MitsubishiElectric.co.jp](mailto:Nakashima.Daiki@df.MitsubishiElectric.co.jp)

2022-04-21 03:19 UTC, dnakashima reviewed
[ja_JP] translate peer_event_services.rst into Japanese

https://github.com/hyperledger/fabric-docs-i18n/issues/567

Signed-off-by: Daiki Nakashima [Nakashima.Daiki@df.MitsubishiElectric.co.jp](mailto:Nakashima.Daiki@df.MitsubishiElectric.co.jp)

2022-04-21 03:20 UTC, dnakashima reviewed
[ja_JP] translate peer_event_services.rst into Japanese

https://github.com/hyperledger/fabric-docs-i18n/issues/567

Signed-off-by: Daiki Nakashima [Nakashima.Daiki@df.MitsubishiElectric.co.jp](mailto:Nakashima.Daiki@df.MitsubishiElectric.co.jp)

2022-04-21 05:25 UTC, dnakashima reviewed
[ja_JP] translate peer_event_services.rst into Japanese

#567

Signed-off-by: Daiki Nakashima Nakashima.Daiki@df.MitsubishiElectric.co.jp

2022-04-21 05:31 UTC, dnakashima commented
@shimos 
コメント頂きありがとうございました。修正を反映したので再度ご確認をお願い致します。
（DCOの反映で色々手間取ってしまったので不要なコメントが付いています。それらは無視でお願い致します。）

2022-04-25 00:36 UTC, shimos requested changes
@dnakashima 修正ありがとうございます。該当箇所にコメントしましたが、マージ時についたゴミが残っているようですので、お手数ですがこちらの削除もお願いします。

2022-04-25 00:36 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +>>>>>>> Update docs/locale/ja_JP/source/peer_event_services.rst
gitのconflict解消時についてしまったものがそのまま残っているようです。(`<<<<<<< HEAD`など)

修正した部分である

> イベントの登録は、スタートとストップの位置、シークの挙動（利用可能になるまでブロックするか、利用できなければ失敗するか）を含むピアへの配信シーク情報メッセージを含むエンベロープを送信することで完了します。ヘルパー変数として ``SeekOldest`` と ``SeekNewest`` があり、台帳の一番古い（すなわち最初の）ブロックもしくは最新の（すなわち最後の）ブロックを示します。サービスに無制限に送信させるには、 ``SeekInfo`` メッセージのストップ位置を ``MAXINT64`` にする必要があります。

ここだけ残すようにお願いいたします。

2022-04-25 03:14 UTC, dnakashima commented on docs/locale/ja_JP/source/peer_event_services.rst
> +>>>>>>> Update docs/locale/ja_JP/source/peer_event_services.rst
再度ご確認頂きありがとうございます。該当箇所の修正をpushしたので、ご確認の程よろしくお願い致します。お手間かけさせていまい、大変申し訳ございません。

2022-04-25 04:26 UTC, shimos requested changes
@dnakashima 修正ありがとうございます。たびたび申し訳ないですが、コンパイルすると表示が崩れる部分がありますので、こちらの修正をお願いいたします。

2022-04-25 04:26 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +.. note:: チェーンコードイベントのペイロードはフィルタードブロックに含まれません。
```suggestion

.. note:: チェーンコードイベントのペイロードはフィルタードブロックに含まれません。
```

`.. note::` とのその前の段落に改行が必要です

2022-04-25 04:26 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +.. note:: もし相互TLSがピアで有効になっていた場合、TLS証明書のハッシュ値をエンベロープのチャネルヘッダーに設定しなければなりません。
```suggestion

.. note:: もし相互TLSがピアで有効になっていた場合、TLS証明書のハッシュ値をエンベロープのチャネルヘッダーに設定しなければなりません。
```

2022-04-25 04:26 UTC, shimos commented on docs/locale/ja_JP/source/peer_event_services.rst
> +イベントサービスに関しての詳細は、 `SDK documentation. <https://hyperledger.github.io/fabric-sdk-node/{BRANCH}/tutorial-channel-events.html>`_ を参照して下さい。
```suggestion
イベントサービスに関しての詳細は、 `SDK documentation <https://hyperledger.github.io/fabric-sdk-node/{BRANCH}/tutorial-channel-events.html>`_ を参照して下さい。
```

2022-04-25 06:38 UTC, dnakashima commented
> @dnakashima 修正ありがとうございます。たびたび申し訳ないですが、コンパイルすると表示が崩れる部分がありますので、こちらの修正をお願いいたします。

再度ご確認頂きありがとうございます。ご指摘頂きました箇所を修正したので、ご確認の程よろしくお願い致します。何度も申し訳ございません。

2022-04-25 09:31 UTC, shimos approved these changes
@dnakashima ありがとうございました! LGTM

2022-04-25 09:32 UTC, merged