[ja_JP] Translate "readwrite.rst" into Japanese
hyperledger/fabric-docs-i18n pull request #663
Opened 2022-04-20 05:57 UTC by yukiknd

This patch translates source/readwrite.rst into Japanese.

Resolves #569

Signed-off-by: Yuki Kondo <yuki.kondo.ob@hitachi.com>

2022-04-20 10:47 UTC, satota2 requested changes
@yukiknd 翻訳お疲れ様です。細かいですがいくつか改善の余地があるポイントを見つけたのでご確認ください。

2022-04-20 10:47 UTC, satota2 commented on docs/locale/ja_JP/source/readwrite.rst
> +トランザクションが妥当性チェックに合格すると、コミッタは書き込みセットを使用してワールドステートを更新します。
```suggestion
トランザクションが有効性チェックに合格すると、コミッタは書き込みセットを使用してワールドステートを更新します。
```

同一ページ内では用語は統一したほうが良いかと思います。

2022-04-20 10:47 UTC, satota2 commented on docs/locale/ja_JP/source/readwrite.rst
> +次に、 ``T1, T2, T3, T4, and T5`` の5つのトランザクションのセットを考えます。
```suggestion
次に、 ``T1, T2, T3, T4, T5`` の5つのトランザクションのセットを考えます。
```

2022-04-20 10:47 UTC, satota2 commented on docs/locale/ja_JP/source/readwrite.rst
> +つまり、Read-your-writesセマンティクスはサポートされていません。
```suggestion
つまり、Read-your-writes(自分が書いた新しい値を自分で読める)セマンティクスはサポートされていません。
```
前の文で説明はあるのですが、念のためRead-your-writesの意味を補足してあげるとよいと思いました。

2022-04-21 01:37 UTC, yukiknd commented
@satota2 レビューありがとうございます。コメントをベースに修正したので、ご確認ください。

2022-04-21 06:06 UTC, satota2 approved these changes
LGTM!
翻訳ありがとうございました。

2022-04-21 06:06 UTC, merged