[ja_JP] Translate style_guide.md into Japanese (#51)
hyperledger/fabric-docs-i18n pull request #67
Opened 2020-08-06 00:00 UTC by satota2

This PR translates `style_guide.md` into Japanese.

Resolves #51 

Signed-off-by: Tatsuya Sato <Tatsuya.Sato@hal.hitachi.com>

2020-08-06 20:29 UTC, nhoriguchi requested changes
翻訳作業ありがとうございました。何点かコメントさせていただきました。

2020-08-06 20:29 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +どちらのファイルフォーマットも、これらが順不同で行われることを好みません。例えば、`##` タイトルの後に最初に `####` が欲しいかもしれません。しかし、Markdownはそれを許可しません。
```suggestion
どちらのファイルフォーマットも、これらが順不同で行われることを好みません。例えば、`#` タイトルの後に最初に `####` が欲しいかもしれません。しかし、Markdownはそれを許可しません。
```

2020-08-06 20:29 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +  RSTの場合、推奨される構文は次のとおりです。
```suggestion
  Markdownの場合、推奨される構文は次のとおりです。
```

2020-08-06 20:29 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +**Github上でファイルを編集しないでください。** もし、ファイルに変更を加えたい場合には、リポジトリをクローンし、そして [Contributing](./CONTRIBUTING.html) のプルリクエストの作成方法に従ってください。
```suggestion
**GitHub上でファイルを編集しないでください。** もし、ファイルに変更を加えたい場合には、リポジトリをクローンし、そして [Contributing](./CONTRIBUTING.html) のプルリクエストの作成方法に従ってください。
```

2020-08-06 20:29 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +フォーマットの方法を確認したいだけなら、ページ右上隅の `Edit on Github` リンクをクリックしてFabricリポジトリに移動し、次に `Raw` タブをクリックします。これにより、ドキュメントのフォーマットが表示されます。
```suggestion
フォーマットの方法を確認したいだけなら、ページ右上隅の `Edit on GitHub` リンクをクリックしてFabricリポジトリに移動し、次に `Raw` タブをクリックします。これにより、ドキュメントのフォーマットが表示されます。
```
(悪いのは原文ですが) せっかくなので固有名詞を正しく記述しておくのがよいでしょう。

2020-08-06 20:29 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +  githubへのリンク例:
```suggestion
  GitHubへのリンク例:
```

2020-08-06 20:29 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +  github上でRSTファイルをブラウジングする場合、残念ながら相対リンクは機能しません。
```suggestion
  GitHub上でRSTファイルをブラウジングする場合、残念ながら相対リンクは機能しません。
```

2020-08-06 20:29 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +**見出し (Captions)**
これは図や表に添える説明文のことを意味しているのではないでしょうか。図表のキャプションは、ソースコード内で明示的に指定しなくても Sphinx が自動的にイタリック体にしてくれるようで、書き手が意識する必要はないようです。
```suggestion
**図表のキャプション (Captions)**
```

2020-08-10 18:05 UTC, satota2 commented
@Naoya-Horiguchi レビューありがとうございます。
ご指摘いただいた点を取り込んだパッチを再投稿いたしましたので、ご確認よろしくお願いします。

2020-08-10 22:22 UTC, nhoriguchi requested changes
ビルドして見栄えを確認してみたところ細かい問題を見つけましたので共有します。すみませんが、また修正をお願いいたします。

2020-08-10 22:22 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +==============================
```suggestion
===============================
```
タイトルの幅と下線の幅があっていないと Sphinx ビルド時に warning が出ます。

2020-08-10 22:22 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +--------------------------------
```suggestion
---------------------------------
```

2020-08-10 22:22 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2020-08-10 22:22 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/style_guide.md
> +--------------------------------
```suggestion
---------------------------------
```

2020-08-11 00:46 UTC, satota2 commented
@Naoya-Horiguchi 細部まで丁寧にチェック頂きありがとうございます。
反映版を再投稿いたしましたのでご確認よろしくお願いします。

2020-08-11 02:26 UTC, nhoriguchi approved these changes
どうもありがとうございました。

2020-08-11 04:31 UTC, merged