[ja_JP] Translate "secured_private_asset_transfer_tutorial.md"
hyperledger/fabric-docs-i18n pull request #675
Opened 2022-04-25 14:36 UTC by satomicchy

This patch translates "secured_private_asset_transfer_tutorial.md" into Japanese.

Resolves #564

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2022-04-26 01:38 UTC, satota2 requested changes
@satomicchy 翻訳お疲れ様です。レビューコメントを付けましたのでご確認をお願いします。
全体的に同じ単語の表記(和訳)揺れがあったのでその観点で見直していただけるとよいと思います。
読み手は原文を参照しない可能性もあるので、極力同一ページ内では訳語の表記は統一したほうが、彼らの理解の助けになると思います。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +このチュートリアルでは、プライベートデータを使用してアセットとトランザクションの詳細を維持しながら、Hyperledger Fabricブロックチェーンチャネル内の組織間でどのようにアセットが表され、取引できるかを実際にやってみます。チェーン上の各アセットは、ユニークな所有者とともに、特定のイミュータブルなメタデータプロパティ(サイズや色など)を持つ、特有のアセットを表している非代替トークン(N
```suggestion
このチュートリアルでは、プライベートデータを使用してアセットとトランザクションの詳細を維持しながら、Hyperledger Fabricブロックチェーンチャネル内の組織間でどのようにアセットが表され、取引できるかを実際にやってみます。チェーン上の各アセットは、ユニークな所有者とともに、特定のイミュータブルなメタデータプロパティ(サイズや色など)を持つ、特有のアセットを表している非代替トークン(NFT)です。所有者がアセットを売却したい場合は、アセットが譲渡される前に両当事者が同じ価格で合意する必要があります。プライベートなアセット転送スマートコントラクトは、アセットの所有者のみがアセットを転送できるように実行します。このチュートリアルでは、ステートベースのエンドースメントやプライベートデータ、アクセス制御などのFabric機能がどのように連携して、お互いにプライベートで検証可能な安全なトランザクションを実現するかを学びます。
```

移転は、他のところと同様に「転送」もしくは「譲渡」に統一したほうが良いと思います。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +このチュートリアルは [secured asset transfer sample](https://github.com/hyperledger/fabric-samples/tree/master/asset-transfer-secured-agreement/chaincode-go) をデプロイし、データを公に共有することなく2つの組織間でプライベートなアセットを転送する方法を実演しま
```suggestion
このチュートリアルは [secured asset transfer sample](https://github.com/hyperledger/fabric-samples/tree/master/asset-transfer-secured-agreement/chaincode-go) をデプロイし、データをパブリックに共有することなく2つの組織間でプライベートなアセットを転送する方法を実演します。こちらのタスク [Install Samples, Binaries, and Docker Images](../install.html#install-samples-binaries-and-docker-images) は終わっているものとします。
```
private, public関連のワードはプライベート、パブリックで統一したほうがより理解しやすいと思いました。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 所有は組織レベルで管理されます(Fabric許可スキームでは、組織内の個々のアイデンティティレベルでの所有権も同様にサポートします)。
```suggestion
- 所有権は組織レベルで管理されます(Fabricの許可スキームでは、組織内の個々のアイデンティティレベルでの所有権も同様にサポートします)。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- アセットは、最初の所有者の組織によって発行される可能性があります(現実の世界では、発行は資産の財産を認証する何らかの機関に限定される可能性があります)。
```suggestion
- アセットは、最初の所有者の組織によって発行される可能性があります(現実の世界では、発行はアセットのプロパティを認証する何らかの機関に限定される可能性があります)。
```
- assetは、同じページ中ではアセットか資産のどちらかに統一したほうが良いと思います。
- propertiesは無理に和訳せず他のところと同様にプロパティでもよい気がしました。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +関心のある買い手は、アセットの出どころ、特にアセットの起源と管理されているチェーンを確認したいと思うでしょう。彼らはまた、アセットが発行以来変更されていないこと、および以前のすべての転送が合法的であったことを確認したいと思うでしょう。
```suggestion
関心のある買い手は、アセットの来歴、特にアセットの起源と管理されているチェーンを確認したいと思うでしょう。彼らはまた、アセットが発行以来変更されていないこと、および以前のすべての転送が合法的であったことを確認したいと思うでしょう。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +スマートコントラクトは、アセットのプロパティがプライベートなのままであることを確保するために、以下の技術を使用します。
```suggestion
スマートコントラクトは、アセットのプロパティがプライベートなままであることを確保するために、以下の技術を使用します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 実際のプライベートなアセット転送は、正当なアセットが移転されていることを確認し、価格が合意されていることを確認しなければなりません。買い手と売り手の両方が転送をエンドースしなければなりません。
```suggestion
- 実際のプライベートなアセット転送は、正当なアセットが転送されていることを確認し、価格が合意されていることを確認しなければなりません。買い手と売り手の両方が転送をエンドースしなければなりません。
```
用語統一。他の部分と同様に「転送」もしくは「譲渡」のどちらかを使うのが良いかと思います。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- アセットメタデータのプロパティは、現在所有している組織のピアの暗黙的なプライベートデータコレクションにのみ格納されます。Fabricチャネルの各組織には、それぞれの組織が利用できるプライベートデータコレクションがあります。このコレクションは、チェーンコードで明示的に定義する必要がないため、 *絶対的* です。
```suggestion
- アセットメタデータのプロパティは、現在所有している組織のピアの暗黙的なプライベートデータコレクションにのみ格納されます。Fabricチャネルの各組織には、それぞれの組織が利用できるプライベートデータコレクションがあります。このコレクションは、チェーンコードで明示的に定義する必要がないため、 *暗黙的* です。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- プライベートなプロパティのハッシュ値は、すべてのチャネルメンバが見ることができるようにチェーンに自動的に格納されますが、プライベートなプロパティにはランダムなソルトが含まれているため、他のチャネルメンバはディクショナリ攻撃によってプライベートデータの前イメージを推測できません。
```suggestion
- プライベートなプロパティのハッシュ値は、すべてのチャネルメンバーが見ることができるようにチェーンに自動的に格納されますが、プライベートなプロパティにはランダムなソルトが含まれているため、他のチャネルメンバーは辞書攻撃によってプライベートデータの原像を推測できません。
```
- dictionary attackは辞書攻撃かすべてカタカナを使うほうが多い印象です。
- pre-image: 暗号化前の原像をさすものと思われます。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +プライベートアセットの転送スマートコントラクトは、どのチャネルメンバからもエンドースメントを必要とするエンドースメントポリシーとともにデプロイされます。これにより、どの組織も、他のチャネルメンバーからのエンドースメントを必要としない自身のアセットを作成することができます。アセットの生成は、チェーンコードレベルのエンドースメントポリシーを使用する唯一のトランザクションです。トランザクションの更新ま
```suggestion
プライベートなアセット転送スマートコントラクトは、どのチャネルメンバーからもエンドースメントを必要とするエンドースメントポリシーとともにデプロイされます。これにより、どの組織も、他のチャネルメンバーからのエンドースメントを必要としない自身のアセットを作成することができます。アセットの生成は、チェーンコードレベルのエンドースメントポリシーを使用する唯一のトランザクションです。トランザクションの更新または既存アセットの転送は、ステートベースエンドースメントポリシーまたはプライベートデータコレクションのエンドースメントポリシーによって管理されます。他のシナリオでは、発行機関が作成トランザクションをエンドースすることを希望するかもしれないことに注意してください。
```

state based endorsement policyは機能なのでそのままステートベースエンドースメントポリシーでよいかと思います。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +アセットを売るためには、買い手と売り手の両方がアセット価格について合意しなければなりません。各当事者は、合意した価格をそれぞれのプライベートデータコレクションに保管します。プライベートなアセット移転スマートコントラクトでは、アセットを移転する前に両当事者が同じ価格に合意する必要があることを強制します。
```suggestion
アセットを売るためには、買い手と売り手の両方がアセット価格について合意しなければなりません。各当事者は、合意した価格をそれぞれのプライベートデータコレクションに保管します。プライベートなアセット転送スマートコントラクトでは、アセットを転送する前に両当事者が同じ価格に合意する必要があることを強制します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +プライベートアセットの転送スマートコントラクトの使用を開始する前に、トランザクションフローの概要と、ブロックチェーンで作成されたアセットを保護するためにFabricの機能がどのように使用されるかについて説明します。
```suggestion
プライベートなアセット転送スマートコントラクトの使用を開始する前に、トランザクションフローの概要と、ブロックチェーンで作成されたアセットを保護するためにFabricの機能がどのように使用されるかについて説明します。
```
private asset transfer smart contractの用語統一(同件の確認もお願いします・・)。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +プライベートアセットの転送スマートコントラクトは、どのチャネルメンバからもエンドースメントを必要とするエンドースメントポリシーとともにデプロイされます。これにより、どの組織も、他のチャネルメンバーからのエンドースメントを必要としない自身のアセットを作成することができます。アセットの生成は、チェーンコードレベルのエンドースメントポリシーを使用する唯一のトランザクションです。トランザクションの更新ま
```suggestion
プライベートなアセット転送スマートコントラクトは、どのチャネルメンバーからもエンドースメントを必要とするエンドースメントポリシーとともにデプロイされます。これにより、どの組織も、他のチャネルメンバーからのエンドースメントを必要としない自身のアセットを作成することができます。アセットの生成は、チェーンコードレベルのエンドースメントポリシーを使用する唯一のトランザクションです。トランザクションの更新または既存アセットの転送は、ステートベースエンドースメントポリシーまたはプライベートデータコレクションのエンドースメントポリシーによって管理されます。他のシナリオでは、発行機関が作成トランザクションをエンドースすることを希望するかもしれないことに注意してください。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- アセットが作成されると、スマートコントラクトは、要求を提出した組織のMSP IDを取得し、そのMSP IDを所有者としてパブリックチェーンコードワールドステートのアセットキー/値に格納します。更新するスマートコントラクトの要求またはアセットの転送は、アクセス制御ロジックを使用して、要求元のクライアントが同じ組織からのものであることを確認します。他のシナリオでは、オーナーシップは、組織自体では
```suggestion
- アセットが作成されると、スマートコントラクトは、要求を提出した組織のMSP IDを取得し、そのMSP IDを所有者としてパブリックチェーンコードのワールドステートのアセットキー/値に格納します。更新するスマートコントラクトの要求またはアセットの転送は、アクセス制御ロジックを使用して、要求元のクライアントが同じ組織からのものであることを確認します。他のシナリオでは、所有権は、組織自体ではなく、組織内の特定のクライアントアイデンティティに基づく可能性があることに注意してください。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- また、アセットが作成されると、スマートコントラクトはアセットキーのエンドースメントポリシーを元にした状態を設定します。状態をベースとするポリシーは、アセットを所有する組織からのピアが、その後の要求を更新するためにエンドースするか、アセットを転送しなければならないと規定しています。これにより、他の組織が自身のピアで悪意を持って変更されたスマートコントラクトを使用して、アセットを更新したり転送し
```suggestion
- また、アセットが作成されると、スマートコントラクトはアセットキーのステートベースエンドースメントポリシーを設定します。ステートベースポリシーは、アセットを所有する組織からのピアが、その後の要求を更新するためにエンドースするか、アセットを転送しなければならないと規定しています。これにより、他の組織が自身のピアで悪意を持って変更されたスマートコントラクトを使用して、アセットを更新したり転送したりすることを防止することができます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- アセットの所有者は、パブリック所有レコードの記述を変更することができます。たとえば、アセットが売りに出されていることを宣伝することができます。スマートコントラクトアクセス制御では、アセット所有者組織のメンバーがこの変更を提出する必要があることを強制します。状態ベースのエンドースメントポリシーにより、所有者の組織のピアがこの記述の変更を承認しなければならないことを強制します。
```suggestion
- アセットの所有者は、パブリックな所有権レコードの記述を変更することができます。たとえば、アセットが売りに出されていることを宣伝することができます。スマートコントラクトのアクセス制御では、アセット所有者組織のメンバーがこの変更を送信する必要があることを強制します。ステートベースエンドースメントポリシーにより、所有者の組織のピアがこの記述の変更を承認しなければならないことを強制します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +アセットの所有者とアセットの買い手は、特定の価格で資産を譲渡することに合意します。
```suggestion
アセットの所有者とアセットの買い手は、特定の価格でアセットを譲渡することに合意します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- プライベートデータコレクションは、合意された価格をチャネルの他のメンバーには秘密にします。プライベートデータコレクションのエンドースメントポリシーは、それぞれの組織のピアが価格合意を承認したことを保証し、スマートコントラクトアクセス制御論理は、価格合意が関連する組織のクライアントによって提出されたことを保証します。
```suggestion
- プライベートデータコレクションは、合意された価格をチャネルの他のメンバーには秘密にします。プライベートデータコレクションのエンドースメントポリシーは、それぞれの組織のピアが価格合意を承認したことを保証し、スマートコントラクトのアクセス制御ロジックは、価格合意が関連する組織のクライアントによって送信されたことを保証します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 各価格合意のハッシュ値は、台帳に保管されます。2つのハッシュは、2つの組織が同じ価格で合意した場合にのみ一致します。これにより、組織は、移転が行われる前に、移転の詳細について合意に達したことを検証することができます。ランダムな取引IDが価格合意に追加され、それは*salt*として機能し、他のチャネルメンバーが台帳のハッシュ値を使って価格を推測することができないようにします。
```suggestion
- 各価格合意のハッシュ値は、台帳に保管されます。2つのハッシュは、2つの組織が同じ価格で合意した場合にのみ一致します。これにより、組織は、転送が行われる前に、転送の詳細について合意に達したことを検証することができます。ランダムな取引IDが価格合意に追加され、それは*salt*として機能し、他のチャネルメンバーが台帳のハッシュ値を使って価格を推測することができないようにします。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +2つの組織が同じ価格に合意した後、アセット所有者は転送関数を使用してアセットを購入者に転送することができます。
```suggestion
2つの組織が同じ価格に合意した後、アセット所有者は転送関数を使用してアセットを買い手に転送することができます。
```
buyerの用語統一。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- スマートコントラクトアクセス制御により、アセットを所有する組織のメンバーが転送を開始しなければならないことが保証されます。
```suggestion
- スマートコントラクトのアクセス制御により、アセットを所有する組織のメンバーが転送を開始しなければならないことが保証されます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 転送関数は、転送関数に渡されたアセットのプライベートなイミュータブルなのプロパティが、プライベートなコレクション内のアセットデータのチェーンハッシュ値と一致することを確認し、アセット所有者は所有しているアセットと同じ*selling*であることを確認します。
```suggestion
- 転送関数は、転送関数に渡されたアセットのプライベートかつイミュータブルなプロパティが、プライベートなコレクション内のアセットデータのチェーンハッシュ値と一致することを確認し、アセット所有者は所有しているアセットと同じ*selling*であることを確認します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 転送条件が満たされると、転送関数は、アセットを買い手の暗黙のプライベートデータコレクションに追加し、アセットを売り手のコレクションから削除します。この転送では、パブリックオーナーシップレコードの所有者も更新されます。
```suggestion
- 転送条件が満たされると、転送関数は、アセットを買い手の暗黙的なプライベートデータコレクションに追加し、アセットを売り手のコレクションから削除します。この転送では、パブリックな所有権レコード中の所有者も更新されます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 販売者と購入者の暗黙的なデータ収集のエンドースメントポリシー、および状態ベースのパブリックレコードのエンドースメントポリシー(販売者にをエンドースを要求する)のために、移転は購入者と販売者の両方からのピアによって承認される必要があります。
```suggestion
- 売り手と買い手の暗黙的なデータコレクションのエンドースメントポリシー、およびパブリックレコードのステートベースエンドースメントポリシー(売り手にエンドースを要求する)のために、転送は売り手と買い手の両方からのピアによって承認される必要があります。
```
用語統一。

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 状態ベースのパブリックアセットレコードのエンドースメントポリシーは、アセットの新しい所有者のピアのみがかれらの新しいアセットを更新または販売できるように更新されます。
```suggestion
- パブリックアセットレコードのステートベースエンドースメントポリシーは、アセットの新しい所有者のピアのみがそれらの新しいアセットを更新または販売できるように更新されます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +- 価格合意は、販売者と購入者の両方の暗黙のプライベートデータコレクションからも削除され、各プライベートデータコレクションで契約書が作成されます。
```suggestion
- 価格合意は、売り手と買い手の両方の暗黙的なプライベートデータコレクションからも削除され、各プライベートデータコレクションで領収書が作成されます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +Fabricテストネットワークを使って、プライベートなアセット転送スマートコントラクトを実行することができます。テストネットワークには、Org1とOrg2の2つのピア組織があり、それぞれ1つのピアを運営しています。このチュートリアルでは、両葬式が参加したテストネットワークのチャネルにスマートコントラクトをデプロイします。最初に、Org1が所有するアセットを作成します。2つの組織が価格について合意
```suggestion
Fabricテストネットワークを使って、プライベートなアセット転送スマートコントラクトを実行することができます。テストネットワークには、Org1とOrg2の2つのピア組織があり、それぞれ1つのピアを運営しています。このチュートリアルでは、両組織が参加したテストネットワークのチャネルにスマートコントラクトをデプロイします。最初に、Org1が所有するアセットを作成します。2つの組織が価格について合意した後、アセットをOrg1からOrg2に転送します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +保護されたアセットトランスファー スマートコントラクトを、チャネルへデプロイするためのテストネットワークスクリプトを利用することができます。スマートコントラクトを `mychanne` へデプロイするために、次のコマンドを実行します。
```suggestion
安全なアセット転送スマートコントラクトを、チャネルへデプロイするためのテストネットワークスクリプトを利用することができます。スマートコントラクトを `mychannel` へデプロイするために、次のコマンドを実行します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +このサンプルの実行中に、ネットワークをOrg1とOrg2の両方の立場でやりとりするする必要があります。チュートリアルを使いやすくするために、組織ごとに別々のターミナルを使用します。新しいターミナルを開いて、`test-network` ディレクトリから操作していることを確認してください。`peer` CLIをOrg1管理者として操作するには、次の環境変数を設定します。
```suggestion
このサンプルの実行中に、ネットワークをOrg1とOrg2の両方の立場でやりとりする必要があります。チュートリアルを使いやすくするために、組織ごとに別々のターミナルを使用します。新しいターミナルを開いて、`test-network` ディレクトリから操作していることを確認してください。`peer` CLIをOrg1管理者として操作するには、次の環境変数を設定します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +Org1として操作できるターミナルが1つできたので、Org2用の新しいターミナルを開きます。また、この端末も `test-network` ディレクトリから操作していることを確認してください。Org1管理者として操作するために、次の環境変数を設定します。
```suggestion
Org1として操作できるターミナルが1つできたので、Org2用の新しいターミナルを開きます。また、このターミナルも `test-network` ディレクトリから操作していることを確認してください。Org1管理者として操作するために、次の環境変数を設定します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +どのチャネルメンバも、スマートコントラクトを使用して、その組織が所有するアセットを作成できます。アセットの詳細は、プライベートデータコレクションに保存され、アセットを所有する組織だけがアクセスできます。アセットのパブリックレコード、所有者およびパブリックな記述は、チャネル台帳に格納されます。すべてのチャネルメンバは、パブリック所有者レコードにアクセスして、誰がアセットを所有しているかを確認し、記
```suggestion
どのチャネルメンバーも、スマートコントラクトを使用して、その組織が所有するアセットを作成できます。アセットの詳細は、プライベートデータコレクションに保存され、アセットを所有する組織だけがアクセスできます。アセットのパブリックレコード、所有者およびパブリックな記述は、チャネル台帳に格納されます。すべてのチャネルメンバーは、パブリックな所有者レコードにアクセスして、誰がアセットを所有しているかを確認し、記述を読み込みし、アセットが売りに出されているかを確認できます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +アセットを作成する前に、アセットの詳細を指定する必要があります。次のコマンドを発行して、アセットを記述するJSONを作成します。`"salt"` パラメータは、アセットが台帳のハッシュ値を使用してチャネルの別のメンバーを推測するのを防ぐランダムな文字列です。もしsaltがなかったら、ユーザーは、推測のハッシュ値と台帳のハッシュ値が一致するまで理論的にアセットパラメータを推測できます(これはディク
```suggestion
アセットを作成する前に、アセットの詳細を指定する必要があります。次のコマンドを発行して、アセットを記述するJSONを作成します。`"salt"` パラメータは、アセットが台帳のハッシュ値を使用してチャネルの別のメンバーを推測するのを防ぐランダムな文字列です。もしsaltがなかったら、ユーザーは、推測のハッシュ値と台帳のハッシュ値が一致するまで理論的にアセットパラメータを推測できます(これは辞書攻撃と呼ばれます)。この文字列は、一時データとして作成トランザクションに渡すことができるように、Base64形式でエンコードされます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +Org1の暗黙的なデータコレクションをクエリするすると、作成されたアセットを確認できます。
```suggestion
Org1の暗黙的なデータコレクションをクエリすると、作成されたアセットを確認できます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +また、台帳をクエリして、パブリック所有レコードを表示することもできます。
```suggestion
また、台帳をクエリして、パブリックな所有権レコードを表示することもできます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +Org1が所有するアセットのパブリックな説明を変更する場合は、Org1によって承認される必要があります。エンドースメントポリシーは、チェーンコード内のアクセス制御ポリシーによって補強されており、更新するは、アセットを所有する組織によって提出される必要があります。Org2がパブリックの説明をいたずらで変更しようとした場合にどうなるか見てみましょう。
```suggestion
Org1が所有するアセットのパブリックな説明を変更する場合は、Org1によって承認される必要があります。エンドースメントポリシーは、チェーンコード内のアクセス制御ポリシーによって補強されており、更新するにはアセットを所有する組織によって送信される必要があります。Org2がパブリックの説明をいたずらで変更しようとした場合にどうなるか見てみましょう。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +Org1のターミナルから操作します。Org1はアセット価格を110ドルに設定することに同意します。 `trade_id` は、購入者でも販売者でもないチャネル・メンバーが価格を推測できないようにするためのソルトとして使用されます。この値は、購入者と販売者の間で電子メールまたはその他の通信を通じて、帯域外で渡される必要があります。購入者と販売者はまた、アセットキーにソルトを加えて、チャネルの他のメ
```suggestion
Org1のターミナルから操作します。Org1はアセット価格を110ドルに設定することに同意します。 `trade_id` は、購入者でも販売者でもないチャネル・メンバーが価格を推測できないようにするためのソルトとして使用されます。この値は、売り手と買い手の間で電子メールまたはその他の通信を通じて、ブロックチェーンネットワーク外で渡される必要があります。売り手と買い手はまた、アセットキーにソルトを加えて、チャネルの他のメンバーがどのアセットが売りに出されているかを推測することを防止することができます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +Org2のターミナルから操作します。購入に同意する前に、次のコマンドを実行してアセットのプロパティを確認します。資産のプロパティとソルト、電子メールやその他の通信を通じて、販売者と購入者の間で帯域外に渡されます。
```suggestion
Org2のターミナルから操作します。購入に同意する前に、次のコマンドを実行してアセットのプロパティを確認します。アセットのプロパティとソルト、電子メールやその他の通信を通じて、販売者と購入者の間で帯域外に渡されます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +*図 2: Org1とOrg2がアセットの移転に合意した後、各組織が合意した価格はそれぞれのプライベートデータコレクションに保管されます。購入者と販売者のコンポジットキーは、アセット詳細とアセット所有記録との衝突を防ぐために使用されます。合意された価格は、各組織のピアにのみ保存されます。ただし、両合意のハッシュ値は、チャネルに加盟しているすべてのピアで、チャネルワールドステートに保管されます。*
```suggestion
*図 2: Org1とOrg2がアセットの転送に合意した後、各組織が合意した価格はそれぞれのプライベートデータコレクションに保管されます。売り手と買い手のコンポジットキーは、アセット詳細とアセット所有権レコードとの衝突を防ぐために使用されます。合意された価格は、各組織のピアにのみ保存されます。ただし、両合意のハッシュ値は、チャネルに参加しているすべてのピアで、チャネルのワールドステートに保管されます。*  
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +次のコマンドを実行して、asset1を100ドルで購入することに同意します。現時点では、Org2はOrg2の意図とは異なる価格に同意します。ご心配なく、2つの組織は将来同じ価格で合意するでしょう。しかし、この一時的な不一致は、購入者と販売者が異なる価格に合意した場合に何が起こるかのテストとして使用できます。Org2はOrg1と同じ `trade_id` を使用する必要があります。
```suggestion
次のコマンドを実行して、asset1を100ドルで購入することに同意します。現時点では、Org2はOrg2の意図とは異なる価格に同意します。ご心配なく、2つの組織は将来同じ価格で合意するでしょう。しかし、この一時的な不一致は、売り手と買い手が異なる価格に合意した場合に何が起こるかのテストとして使用できます。Org2はOrg1と同じ `trade_id` を使用する必要があります。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +両方の組織が価格に合意した後、Org1はアセットをOrg2に移転しようとします。スマートコントラクトのプライベートなアセット移転関数は、台帳のハッシュ値を利用して、両組織が同じ価格で合意していることを確認します。関数はまた、プライベートなアセットの詳細のハッシュ値を使用して、移転されるアセットがOrg1が所有するアセットと同じであることを確認します。
```suggestion
両方の組織が価格に合意した後、Org1はアセットをOrg2に転送しようとします。スマートコントラクトのプライベートなアセット転送関数は、台帳のハッシュ値を利用して、両組織が同じ価格で合意していることを確認します。関数はまた、プライベートなアセットの詳細のハッシュ値を使用して、転送されるアセットがOrg1が所有するアセットと同じであることを確認します。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +Org1のターミナルから操作します。アセットの所有者が移転を開始する必要があります。以下のコマンドでは、 `--peerAddresses` フラグを使用して、Org1とOrg2の両方のピアをターゲットにしていることに注意してください。両方の組織は移転をエンドースする必要があります。_また、アセットのプロパティと価格は、一時的なプロパティとして転送要求に渡されることにも注意してください。これらは
```suggestion
Org1のターミナルから操作します。アセットの所有者が転送を開始する必要があります。以下のコマンドでは、 `--peerAddresses` フラグを使用して、Org1とOrg2の両方のピアをターゲットにしていることに注意してください。両方の組織は転送をエンドースする必要があります。_また、アセットのプロパティと価格は、一時的なプロパティとして転送要求に渡されることにも注意してください。これらは、現在の所有者が正しいアセットが正しい価格で確実に転送するために渡されます。これらのプロパティは、両方のエンドーサーによってチェーンハッシュと照合されます。_
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +2つの組織が同じ価格で合意していないため、移転を完了できません。
```suggestion
2つの組織が同じ価格で合意していないため、転送を完了できません。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +購入者と販売者が同じ価格に合意したので、Org1はアセットをOrg2に移転できます。
```suggestion
売り手と買い手が同じ価格に合意したので、Org1はアセットをOrg2に転送できます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +アセット所有者レコードをクエリすると、移転が正常に行われたことを確認できます。
```suggestion
アセット所有者レコードをクエリすると、転送が正常に行われたことを確認できます。
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +*図 3: アセットが移転された後、アセットの詳細はOrg2の暗黙データコレクションに配置され、Org1の暗黙データコレクションから削除されます。その結果、アセットの詳細はOrg2ピアにのみ保存されます。アセットがOrg2によって所有されていることを反映するために、台帳の資産所有レコードが更新されます。*
```suggestion
*図 3: アセットが転送された後、アセットの詳細はOrg2の暗黙的データコレクションに配置され、Org1の暗黙的データコレクションから削除されます。その結果、アセットの詳細はOrg2ピアにのみ保存されます。アセットがOrg2によって所有されていることを反映するために、台帳のアセット所有レコードが更新されます。*
```

2022-04-26 01:38 UTC, satota2 commented on docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
> +アセットの移動が終わったら、テストネットワークを停止することができます。コマンドによってテストネットワークのすべてのノードが削除され、作成した台帳データもすべて削除されます。
```suggestion
アセットの転送が終わったら、テストネットワークを停止することができます。コマンドによってテストネットワークのすべてのノードが削除され、作成した台帳データもすべて削除されます。
```

2022-05-01 06:48 UTC, satomicchy commented
@satota2 レビューありがとうございます！修正しましたので、ご確認をお願いいたします。

2022-05-09 03:11 UTC, satota2 approved these changes
@satomicchy LGTM! 翻訳&コメント反映ありがとうございました。

2022-05-09 03:11 UTC, merged