[ja_JP] Translate "Creating a new translation"
hyperledger/fabric-docs-i18n pull request #68
Opened 2020-08-06 01:00 UTC by shimos

This patch translates the topic "Creating a new translation" into Japanese.

Resolves #50

2020-08-06 22:18 UTC, nhoriguchi requested changes
Thanks for your effort. I found one trivial typo. Otherwise, the PR looks good to me.

2020-08-06 22:18 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/international_languages.md
> +  研究者、学生などなど向けに、Fabricのコンセプトを包括的に説明しています。
```suggestion
  研究者、学生など向けに、Fabricのコンセプトを包括的に説明しています。
```

2020-08-07 17:05 UTC, shimos commented on docs/locale/ja_JP/source/international_languages.md
> +  研究者、学生などなど向けに、Fabricのコンセプトを包括的に説明しています。
Thanks. Fixed.

2020-08-07 23:05 UTC, nhoriguchi approved these changes

2020-08-07 23:12 UTC, merged