[ja_JP] Translate "access_control.md" into Japanese
hyperledger/fabric-docs-i18n pull request #706
Opened 2022-05-17 07:34 UTC by yukiknd

This patch translates source/access_control.md into Japanese.

Resolves #585

Signed-off-by: Yuki Kondo <yuki.kondo.ob@hitachi.com>

2022-05-17 09:54 UTC, shimos requested changes
@yukiknd 翻訳ありがとうございます。いくつか細かい点についてコメントしましたので、確認をお願いいたします。

2022-05-17 09:54 UTC, shimos commented on docs/locale/ja_JP/source/access_control.md
> +Signatureポリシーは、 `AND` 、 `OR` 、 `NOutOf` の任意の組み合わせをサポートしており、"An admin of org A and two another admins or 11 of 20 org admins"のように非常に強力なルールを記述することもできます。
```suggestion
Signatureポリシーは、 `AND` 、 `OR` 、 `NOutOf` の任意の組み合わせをサポートしており、"組織Aの管理者とそれ以外の2組織の管理者、もしくは、20組織のうち11組織の管理者"のように非常に強力なルールを記述することもできます。
```
Policyとして有効な文ではないので説明と解釈して、他と同様に中身を訳したほうがよいでしょう。

2022-05-17 09:54 UTC, shimos commented on docs/locale/ja_JP/source/access_control.md
> +このポリシー構造体は次のように解釈できます。*`MyPolicy` という名前のポリシーは、"Org1のpeer"または"Org2のpeer"の役割を持つアイデンティティの署名によってのみ満たされます*。
```suggestion
このポリシー構造体は次のように解釈できます。*`MyPolicy` という名前のポリシーは、"Org1のピア"または"Org2のピア"の役割を持つアイデンティティの署名によってのみ満たされます*。
```
クォートの中身は説明だと思いますので、用語集に従ってピアとしたほうがよいと思います。

2022-05-17 09:54 UTC, shimos commented on docs/locale/ja_JP/source/access_control.md
> +ACLは、リソース関数名の後にストリングが続くキーバリューペアで記述されます。
```suggestion
ACLは、リソース関数名の後に文字列が続くキーバリューペアで記述されます。
```
用語集にはないですが、カタカナはあまり一般的ではないかと思います。

2022-05-18 01:12 UTC, yukiknd commented
@shimos レビューありがとうございます。指摘事項を修正しました。再レビューをお願いします。

2022-05-18 04:02 UTC, shimos approved these changes
@yukiknd 修正ありがとうございます。LGTM

2022-05-18 04:03 UTC, merged