[ja_JP]Translate "advice_for_writers.md" into japanese (#48)
hyperledger/fabric-docs-i18n pull request #72
Opened 2020-08-07 05:56 UTC by Skurimura

This patch translates advice_for_writers.md into japanese.

issue #48

2020-08-08 01:47 UTC, nhoriguchi requested changes
翻訳作業ありがとうございます。内容的にコミットを3つに分割する必要は無いようですので、一つにまとめていただくのが良いと思いました。

2020-08-08 01:47 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/advice_for_writers.md
> +wiki](https://wiki.hyperledger.org/display/fabric/Documentation+Working+Group)へ。
```suggestion
wiki](https://wiki.hyperledger.org/display/fabric/Documentation+Working+Group)をご覧ください。
```
L63 と同じ表現にするのが良いと思いました。

2020-08-24 23:03 UTC, Naoya-Horiguchi commented
@Skurimura さん、GitHub のウェブ画面から変更修正をコミットした場合、そのコミットには Author の "Signed-off-by" が入らないため DCO のチェックで引っかかってしまいます。マージの前提条件を満たすためには 4 つのコミットを一つにまとめて (squash して) いただくか、新たに追加したコミット 9a3f82d6 に Signed-off-by 行を追加していただく必要があります。

お手数ですが、ブランチの更新をよろしくお願いいたします。

(蛇足ですが) コミットをまとめる場合、作業の流れ的には下記のようになると思います。
~~~
# GitHub 上のご自身のリポジトリが更新されているので差分情報を取得
$ git fetch <YOUR_REPOSITORY>

# ローカルにチェックアウトする
$ git checkout -b tmp <YOUR_REPOSITORY>/release-2.2_adviceforwriters

# ブランチの先頭の 4 コミットをまとめる
$ git rebase -i HEAD~4

# コミットログを適宜修正
$ git commit --amend

# 変更を再度 GitHub 上に push する
$ git push <YOUR_REPOSITORY> +HEAD:release-2.2_adviceforwriters
~~~

2020-09-03 03:16 UTC, Skurimura commented
@Naoya-Horiguchi さん、アドバイスありがとうございます。ブランチを更新して過去のコミットをまとめました。このやり方で問題有りませんでしょうか。お手数ですがご確認お願いいたします。

2020-09-03 04:33 UTC, Naoya-Horiguchi approved these changes
ご対応いただき、ありがとうございました。

2020-09-03 04:34 UTC, merged