[ja_JP] Translate "deployment_guide_overview.rst" into Japanese
hyperledger/fabric-docs-i18n pull request #747
Opened 2022-07-18 13:53 UTC by satomicchy

This patch translates deployment_guide_overview.rst into Japanese.

Resolves #596

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2022-07-18 15:41 UTC, shimos requested changes
@satomicchy 翻訳ありがとうございます。いくつかコメントしましたので確認をお願いいたします。

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +* **組織単位を使うかどうか?**
```suggestion
* **組織単位 (OU)を使うかどうか?**
```
Node OUの記述が出てくるので、組織単位 = OUであることを注釈的にも付け加えたほうがわかりやすいかと思います。

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +  ネットワーク内のチャネルによっては、すべてのデータを  :doc:`couchdb_as_state_database` が理解できる方法でモデル化する必要があるかもしれません。一方で、速度を優先する他のネットワークは、すべてのピアがLevelDBを使用することを決定する可能性があります。チャネルは、CouchDBとLevelDBの両方を使用するピアを持つべきではないことに注意してください。
```suggestion
  ネットワーク内のチャネルによっては、すべてのデータを  :doc:`couchdb_as_state_database` が理解できる方法でモデル化する必要があるかもしれません。一方で、速度を優先する他のネットワークは、すべてのピアがLevelDBを使用することを決定する可能性があります。チャネルは、CouchDBとLevelDBの両方を使用するピアを持つべきではないことに注意してください。なぜなら、CouchDBはキーと値にいくつかのデータ制限を課しているからです。LevelDBの正当なキーや値は、CouchDBでは正当ではないかもしれません。
```
Key-valueのkeyはキーで統一したほうがよいでしょう。

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +  ユーザーは、組み込みのビルドを使用してサポートを実行するか、カスタマイズされたビルドと :doc:`cc_launcher` を使用して実行するか、または :doc:`cc_service` を使用して、チェーンコードをデプロイすることができます。
```suggestion
  ユーザーは、組み込みのビルドと実行のサポートを利用するか、カスタマイズされたビルドと :doc:`cc_launcher` を使用して実行するか、または :doc:`cc_service` を使用して、チェーンコードをデプロイすることができます。
```

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +ただし、コンポーネントのデプロイするを選択する場合は、コンポーネントを効果的に実行するために十分なリソースがあることを確認する必要があります。必要なサイズは、ユースケースによって大きく異なります。1つのピアから複数の大量のピアにジョインすると、1つのチャネルに参加する場合よりもはるかに多くのCPUとメモリが必要になります。大まかな見積もりとして、1つのオーダリングノードに割り当てる場合と同様に、
```suggestion
どこにどのようにコンポーネントをデプロイすることを選択するにしても、コンポーネントを効果的に実行するために十分なリソースがあることを確認する必要があります。必要なサイズは、ユースケースによって大きく異なります。1つのピアからいくつかの流量の多いチャネルにジョインすると、1つのチャネルに参加する場合よりもはるかに多くのCPUとメモリが必要になります。大まかな見積もりとして、1つのオーダリングノードに割り当てる計画のリソースの3倍を1つのピアに割り当てるように計画します(以下で説明するように、1つのオーダリングサービスに少なくとも3つ、最適には5つのノードを割り当てることをお勧めします)。同様にCAの場合は、ピアの場合の約10分の1のリソースが必要です。また、クラスタにストレージを追加する必要があります(一部のクラウドプロバイダーは、ストレージを提供している場合があります)。これは、ストレージが最初にクラウドプロバイダーとセットアップされていないと、Persistent Volume(永続ボリューム)とPersistent Volume Claimの設定ができないためです。永続ストレージを使用することで、MSP、台帳、インストールされたチェーンコードなどのデータがコンテナファイルシステムに保存されないようにし、コンテナが破壊されてもそれらが破壊されないようにします。
```
high volume channelsは、たぶん「流量が多いチャネル」という意味かと思うのですがいかがでしょうか。

Persistent VolumeとPersistent Volume ClaimはKubernetesの用語なので、訳さなくてもよいかなと思います。

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +* 1つのCA(中間CAを使用している場合はそれ以上)は、(「enrollment」と呼ばれるプロセスを介して)組織の管理者、その組織のMSP、およびその組織が所有するノードの証明書を生成するために使用されます。このCAは、追加のユーザーの証明書も生成します。「エンローリング」アイデンティティのロールのために、このCAは「エンロールメントCA」または「ECert CA」と呼ばれることがあります。
```suggestion
* 1つのCA(中間CAを使用している場合はそれ以上)は、(「エンロールメント」と呼ばれるプロセスを介して)組織の管理者、その組織のMSP、およびその組織が所有するノードの証明書を生成するために使用されます。このCAは、追加のユーザーの証明書も生成します。「エンローリング」アイデンティティのロールのために、このCAは「エンロールメントCA」または「ECert CA」と呼ばれることがあります。
```
エンロール（と派生）に関しては、カタカナで統一したほうがよいでしょう。

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +組織に関連付けられたすべての非TLS証明書は、単一の「ルート」CA(つまり、自身の信頼のルートのCA)によって作成できますが、追加のセキュリティ組織は、ルートCA(または最終的にルートCAにつながる別の中間CA)によって証明書が作成される「中間」CAを使用することを決定できます。ルートCAでの侵害は、その信頼ドメイン全体(管理者、ノード、および証明書を生成したCAの証明書)の崩壊につながるため、
```suggestion
組織に関連付けられたすべての非TLS証明書は、単一の「ルート」CA(つまり、自身の信頼のルートのCA)によって作成できますが、セキュリティを高めるため、組織はルートCA(または最終的にルートCAにつながる別の中間CA)によって証明書が作成される「中間」CAを使用することを決定できます。ルートCAでの侵害は、その信頼ドメイン全体(管理者、ノード、および証明書を生成したCAの証明書)の崩壊につながるため、中間CAはルートCAの公開を制限する有用な方法です。中間CAの利用を選択するかどうかは、ユースケースのニーズによって異なります。必須ではありません。すでにこの実装を持っていて、既存のインフラストラクチャにアイデンティティ管理のレイヤを追加したくないエンタープライズのために、Lightweight Directory Access Protocol(LDAP)を設定して、Fabricネットワーク上のアイデンティティを管理することも可能です。LDAPは、効果的にディレクトリのすべてのメンバーを事前登録し、与えられた基準に基づいてエンロールを許可します。
```

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +必要な証明書とMSPをすべて収集したら、ノードを作成する準備はほぼ官僚です。前述したように、ノードをデプロイする有効な方法はいくつかあります。
```suggestion
必要な証明書とMSPをすべて収集したら、ノードを作成する準備はほぼ完了です。前述したように、ノードをデプロイする有効な方法はいくつかあります。
```

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +もし :doc:`peers/peers` のキーのコンセプトのトピックを読み終えた方なら、ピアがネットワークで果たす役割と、他のネットワークコンポーネントとの相互作用の性質について良い考えを持つことができるはずです。ピアは、チャネルのメンバーである組織によって所有されます(このため、これらの組織は「ピア組織」と呼ばれることがあります)。彼らはオーダリングサービスや他のピアに接続し、スマートコン
```suggestion
もし :doc:`peers/peers` のキーのコンセプトのトピックを読み終えた方なら、ピアがネットワークで果たす役割と、他のネットワークコンポーネントとのやりとりの性質について良い考えを持つことができるはずです。ピアは、チャネルのメンバーである組織によって所有されます(このため、これらの組織は「ピア組織」と呼ばれることがあります)。ピアはオーダリングサービスや他のピアに接続し、スマートコントラクトがインストールされて、台帳が保存されています。
```

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +* **Addresses and paths**: ピアはそれ自体のエンティティではなく、他のピアやコンポーネントとやりとりするため、設定で一連のアドレスを指定する必要があります。これらには、他のコンポーネントがピア自体を検出するためのアドレスや、チェーンコード(外部チェーンコードを使用している場合)などを検出するアドレスが含まれます。同様に、台帳の場所(およびステートデータベースのタイプ)と
```suggestion
* **Addresses and paths**: ピアはそれ自体で独立して動くのではなく、他のピアやコンポーネントとやりとりするため、設定で一連のアドレスを指定する必要があります。これらには、他のコンポーネントがピア自体を検出するためのアドレスや、チェーンコード(外部チェーンコードを使用している場合)などを検出するアドレスが含まれます。同様に、台帳の場所(およびステートデータベースのタイプ)と外部ビルダーへのパスを指定する必要があります(外部チェーンコードを使用する場合も同様)。これらには **Operations and metrics** が含まれます。これにより、エンドポイントの設定を通じて、ピアの健全性とパフォーマンスを監視するための方法を設定できます。
```
意訳ですがこのほうがわかりやすいかと思います

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +もし :doc:`orderer/ordering_service` のキーコンセプトトピックを読み終えた方なら、オーダリングサービスがネットワークで果たす役割と、他のネットワークコンポーネントとの相互作用の性質について良い考えを持つことができるはずです。オーダリングサービスは、文字通り、ブロックで承認されたトランザクションを「順序付けする」責任があり、それによってピアは検証し台帳にコミットしま
```suggestion
もし :doc:`orderer/ordering_service` のキーコンセプトトピックを読み終えた方なら、オーダリングサービスがネットワークで果たす役割と、他のネットワークコンポーネントとのやりとりの性質について良い考えを持つことができるはずです。オーダリングサービスは、文字通り、ブロックで承認されたトランザクションを「順序付けする」責任があり、それによってピアは検証し台帳にコミットします。
```

2022-07-18 15:41 UTC, shimos commented on docs/locale/ja_JP/source/deployment_guide_overview.rst
> +オーダリングノードの ``orderer.yaml`` ファイルないの設定値は、カスタマイズするか環境変数で上書きする必要があります。デフォルトの ``orderer.yaml`` 設定ファイルは、 `Hyperledger Fabricのsampleconfigディレクトリ <https://github.com/hyperledger/fabric/blob/master/samplecon
```suggestion
オーダリングノードの ``orderer.yaml`` ファイル内の設定値は、カスタマイズするか環境変数で上書きする必要があります。デフォルトの ``orderer.yaml`` 設定ファイルは、 `Hyperledger Fabricのsampleconfigディレクトリ <https://github.com/hyperledger/fabric/blob/master/sampleconfig/orderer.yaml>`_ にあります。
```

2022-07-18 23:36 UTC, satomicchy commented
@shimos レビューありがとうございます！修正しましたので、ご確認よろしくお願いいたします。

2022-07-19 14:42 UTC, shimos approved these changes
修正ありがとうございました。LGTM

2022-07-19 14:42 UTC, merged