[ja_JP] Translate "tutorials.rst" into Japanese
hyperledger/fabric-docs-i18n pull request #748
Opened 2022-07-18 14:27 UTC by satomicchy

This patch translates source/tutorials.rst into Japanese.

Resolves #739

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2022-07-18 15:44 UTC, shimos requested changes
@satomicchy 翻訳ありがとうございます。細かいですが、一点修正をお願いいたします。

2022-07-18 15:44 UTC, shimos commented on docs/locale/ja_JP/source/tutorials.rst
> +最後に、基本的なスマートコントラクトを書き込みする方法 :doc:`chaincode4ade` を紹介します。
```suggestion
最後に、基本的なスマートコントラクトを書く方法 :doc:`chaincode4ade` を紹介します。
```

2022-07-18 23:24 UTC, satomicchy commented
@shimos レビューありがとうございます！修正しましたのでご確認よろしくお願いいたします。

2022-07-19 14:43 UTC, shimos approved these changes
LGTM!

2022-07-19 14:43 UTC, merged