[ja_JP] Translate docs_guide into Japanese
hyperledger/fabric-docs-i18n pull request #75
Opened 2020-08-08 03:07 UTC by nekia

This PR translates `docs_guide.md` into Japanese.

Resolves #49

2020-08-11 01:23 UTC, shimos reviewed
Thank you for the translation. I have added some minor suggestions.

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
>  * [International language folder structure](#international-folders)
本文中ではリンクのテキストも訳しているようですし、セクションのタイトルとは別なので、ここのリンクのテキストも翻訳した方がよいと思います。

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
>    * [Version 1.4 of US English](https://hyperledger-fabric.readthedocs.io/en/release-1.4/)
上と同様で、ここのリンクのテキストも翻訳した方がよいと思います。

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +歴史的な理由から、英語ドキュメントのソース・ファイルはメインの[Fabricリポジトリ](https://github.com/hyperledger/fabric/)で管理されますが、国際言語向けドキュメントのソース・ファイルはすべて1つの[Fabric i18nリポジトリ](https://github.com/hyperledger/fabric-docs-i18n)で管理されます。ドキュ
一部、US English -> 英語(US)と訳している部分がありますので、どちらかに統一した方がよい気がします。
くどくはなりますが、原文がほぼ一貫して”US English”を使っているので、英語(US)で通すのがよいでしょうか？

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +歴史的な理由から、英語ドキュメントのソース・ファイルはメインの[Fabricリポジトリ](https://github.com/hyperledger/fabric/)で管理されますが、国際言語向けドキュメントのソース・ファイルはすべて1つの[Fabric i18nリポジトリ](https://github.com/hyperledger/fabric-docs-i18n)で管理されます。ドキュ
```suggestion
歴史的な理由から、英語ドキュメントのソース・ファイルはメインの[Fabricリポジトリ](https://github.com/hyperledger/fabric/)で管理されますが、国際言語向けドキュメントのソース・ファイルはすべて1つの[Fabric i18nリポジトリ](https://github.com/hyperledger/fabric-docs-i18n)で管理されます。ドキュメントの異なるバージョンは、適切なGitHubリリースブランチに保持されています。
```

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +最も重要なフォルダは、ソースとなる言語ファイルが格納されているする `source/` フォルダです。ドキュメントのビルドプロセスでは、`make`コマンドを使用して、このソースファイルをHTMLに変換し、動的に作成される`build/html/`フォルダに格納します:
```suggestion
最も重要なフォルダは、ソースとなる言語ファイルが格納されている `source/` フォルダです。ドキュメントのビルドプロセスでは、`make`コマンドを使用して、このソースファイルをHTMLに変換し、動的に作成される`build/html/`フォルダに格納します:
```

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +* これらの変更をフォークしたあなたのGitHubリポジトリにプッシュして,あなた個人の[ReadTheDocs](https://readthedocs.org/)Webサイトに反映することで共同作業者がレビューできるようになります。
```suggestion
* これらの変更をフォークしたあなたのGitHubリポジトリにプッシュして、あなた個人の[ReadTheDocs](https://readthedocs.org/)Webサイトに反映することで共同作業者がレビューできるようになります。
```

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +どちらの言語リポジトリにもGitHubのwebhookが定義されているので、いったん承認されると、`docs/`フォルダに新しくマージされたコンテンツが自動的にビルドされ、更新されたドキュメントが発行される。
```suggestion
どちらの言語リポジトリにもGitHubのwebhookが定義されているので、いったん承認されると、`docs/`フォルダに新しくマージされたコンテンツが自動的にビルドされ、更新されたドキュメントが発行されます。
```

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +[コマンドリファレンス](https://hyperledger-fabric.readthedocs.io/en/latest/command_ref.html)トピックの内容を更新するには、追加の手順が必要です。コマンドリファレンストピックの情報は生成されたコンテンツであるため、関連するマークダウンファイルを単純に更新することはできません。
```suggestion
[コマンドリファレンス](https://hyperledger-fabric.readthedocs.io/en/latest/command_ref.html)トピックの内容を更新するには、追加の手順が必要です。コマンドリファレンストピックの情報は生成されたコンテンツであるため、関連するMarkdownファイルを単純に更新することはできません。
```
表記の統一です。

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +GitHubに変更をプッシュするときは、生成されたmarkdownファイルと同様に、変更された`_preamble.md`、`_postscript.md`、`_.go`ファイルを含める必要があることに注意してください。
```suggestion
GitHubに変更をプッシュするときは、生成されたMarkdownファイルと同様に、変更された`_preamble.md`、`_postscript.md`、`_.go`ファイルを含める必要があることに注意してください。
```
原文がmarkdownですが、オフィシャルな表記はMarkdownのようなので、こちらに統一したほうがいいと思います。

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +- 次に`fabric`フォルダ内で`make help-docs`コマンドを実行し、`docs/source/commands`の下に更新されたマークダウンファイルを生成します。
```suggestion
- 次に`fabric`フォルダ内で`make help-docs`コマンドを実行し、`docs/source/commands`の下に更新されたMarkdownファイルを生成します。
```

2020-08-11 01:23 UTC, shimos commented on docs/locale/ja_JP/source/docs_guide.md
> +- `make help-docs`を実行してマークダウンコンテンツを生成し、変更されたすべてのファイルをGitHubにプッシュする。
```suggestion
- `make help-docs`を実行してMarkdownコンテンツを生成し、変更されたすべてのファイルをGitHubにプッシュする。
```

2020-08-11 07:22 UTC, nekia commented
@shimos どうもありがとうございます。頂いたフィードバックに基づいて 2c0a4fe3320c0bec561349a719c3caad7dd7b96e の通り更新しました。恐れ入りますがご確認のほどよろしくお願いします。

2020-08-11 16:34 UTC, shimos requested changes
@nekia Thank you very much for your changes. The translation looks good to me, but lastly could you squash the commits into one?

2020-08-11 23:48 UTC, nekia commented
Thanks @shimos and I did squash these commits.

2020-08-12 00:10 UTC, shimos approved these changes
Thank you.

2020-08-12 00:11 UTC, merged