[ja_JP] Translate "cc_launcher.md" into Japanese
hyperledger/fabric-docs-i18n pull request #750
Opened 2022-07-19 06:37 UTC by yukiknd

This patch translates source/cc_launcher.md into Japanese.

Resolves #588

Signed-off-by: Yuki Kondo <yuki.kondo.ob@hitachi.com>

2022-07-19 20:53 UTC, shimos requested changes
@yukiknd 翻訳ありがとうございます。typoと表記ゆれについてコメントしましたので、確認をお願いいたします。

2022-07-19 20:53 UTC, shimos commented on docs/locale/ja_JP/source/cc_launcher.md
> +buildpackの実装は、アプリケーションアーティファクトを実行可能なものに変換するプログラムまたはスクリプトを集めたものです。
```suggestion
ビルドパックの実装は、アプリケーションアーティファクトを実行可能なものに変換するプログラムまたはスクリプトを集めたものです。
```
ビルドパックの表記に揺れがありますので、カタカナに統一するのがよいでしょう。

2022-07-19 20:53 UTC, shimos commented on docs/locale/ja_JP/source/cc_launcher.md
> +Buildpackモデルは、チェーンコードパッケージに適用され、チェーンコードの実行とディスカバリをサポートするように拡張されました。
```suggestion
ビルドパックモデルは、チェーンコードパッケージに適用され、チェーンコードの実行とディスカバリをサポートするように拡張されました。
```

2022-07-19 20:53 UTC, shimos commented on docs/locale/ja_JP/source/cc_launcher.md
> +`release` が呼び出された時、`BUILD_OUTPUT_DIR` は `build` プログラムによって生成されたアーティファクト含んでおり、読み込み専用として扱う必要があります。
```suggestion
`release` が呼び出された時、`BUILD_OUTPUT_DIR` は `build` プログラムによって生成されたアーティファクトを含んでおり、読み込み専用として扱う必要があります。
```

2022-07-21 00:24 UTC, yukiknd commented
@shimos レビューありがとうございました。修正したので、再レビューをお願いします。

2022-07-21 23:23 UTC, shimos approved these changes
@yukiknd 修正ありがとうございました。LGTM

2022-07-21 23:23 UTC, merged