[ja_JP] Translate "deploypeer/peerplan.md" into Japanese
hyperledger/fabric-docs-i18n pull request #752
Opened 2022-07-25 13:34 UTC by satomicchy

This patch translates "Deploying a production network >> Planning for a production peer" into Japanese.

Resolves #597

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2022-07-25 15:12 UTC, shimos requested changes
@satomicchy 翻訳ありがとうございます。コメントをいくつか加えましたので、ご確認をお願いいたします。

2022-07-25 15:12 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +このトピックに進む前に、組織の [Deploying a Certificate Authority (CA)](https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/deployguide/ca-deploy-topology.html) のプロセスを確認して、組織の管理者とピアのアイデンティティとMSPを生成する必要があります
以下も同様ですが、これらのリンク先は相対パスにして、release-2.2の日本語ドキュメントを対象としたほうがよいかと思います。

2022-07-25 15:12 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +各ピアは、台帳に記載されているすべての資産(「キー」とも呼ばれる)の現在価値を追跡するステートデータベースを維持しています。サポートされているステートデータベースには、外部CouchDB(データベースのJSONクエリを可能にする)と組み込みGoleveldb(これはそうでない)の2種類があります。データベースの選択は、CouchDBのJSONクエリサポートが必要かどうかによって大きく異なります。
```suggestion
各ピアは、台帳に記載されているすべての資産(「キー」とも呼ばれる)の現在の値を追跡するステートデータベースを維持しています。サポートされているステートデータベースには、外部CouchDB(データベースのJSONクエリを可能にする)と組み込みGoleveldb(JSONクエリが可能ではない)の2種類があります。データベースの選択は、CouchDBのJSONクエリサポートが必要かどうかによって大きく異なります。JSONクエリが必要ない場合、Goleveldbはピアプロセスに埋め込まれているため、パフォーマンスが向上し、管理が少なくて済みます。チャネル上のすべてのピアは同じステートデータベースを使用する必要があるため、データベースの選択はすでに参加を希望するチャネルによって決定されている可能性があります。
```
assetsと若干限定しているので難しいですが、ここは一般的な話をしているので値のほうがよさそうです。

()内は具体的に書いたほうがわかりやすいかなと思いました。

2022-07-25 15:12 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +CouchDBを使用しているときにJSONクエリを実行する機能を超えて、データベースの選択はスマートコントラクトには見えません。
```suggestion
CouchDBを使用しているときにJSONクエリを実行する機能以外は、データベースの選択はスマートコントラクトには見えません。
```

2022-07-25 15:12 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +「man in the middle」攻撃を防ぎ、通信を安全にするために、TLSを使用することはすべての実稼動ネットワークの要件です。そのため、組織CAでピアアイデンティティを登録するだけでなく、組織のTLS CAでもピアイデンティティを登録する必要があります。これらのTLS証明書は、ネットワークと通信するときにピアによって使用されます。
```suggestion
「man in the middle」攻撃を防ぎ、通信を安全にするために、TLSを使用することはすべての本番ネットワークの要件です。そのため、組織CAでピアアイデンティティを登録するだけでなく、組織のTLS CAでもピアイデンティティを登録する必要があります。これらのTLS証明書は、ネットワークと通信するときにピアによって使用されます。
```
production (network)の訳を統一したほうがよいでしょう

2022-07-25 15:12 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +ピアを設定するするときは、 `ledger.state.stateDatabase` パラメータを設定して、ステートデータベースをCouchDBとLevelDB(デフォルト)のどちらに保存するかを決定する必要があります。
```suggestion
ピアを設定するときは、 `ledger.state.stateDatabase` パラメータを設定して、ステートデータベースをCouchDBとLevelDB(デフォルト)のどちらに保存するかを決定する必要があります。
```

2022-07-25 15:12 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +すべてのブロックチェーンノードは注意深く監視する必要がありますが、ピアとオーダリングノードを監視することは非常に重要です。イミュータブルであるため、台帳は必然的に成長します。そのため、ストレージを監視し、必要に応じて拡張しなければいけません。ピアのストレージが枯渇した場合は、より大きなストレージ割り当てで新しいピアをデプロイし、台帳を同期させる選択もあります。本番環境では、広く利用可能なツールを
```suggestion
すべてのブロックチェーンノードは注意深く監視する必要がありますが、ピアとオーダリングノードを監視することは非常に重要です。イミュータブルであるため、台帳は必然的に成長します。そのため、ストレージを監視し、必要に応じて拡張しなければいけません。ピアのストレージが枯渇した場合は、より大きなストレージ割り当てで新しいピアをデプロイし、台帳を同期させる選択もあります。本番環境では、広く利用可能なツールを使用して、ピアに割り当てられたCPUとメモリも監視する必要があります。トランザクションの負荷に対応するとき、あるいは、比較的単純なタスク(台帳をクエリするなど)を実行するときに、ピアが苦闘しているのが分かったら、リソース割り当てを増やす必要があるかもしれないサインです。
```

2022-07-25 15:12 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +ネットワークトラフィックを減らすために、Fabric v2.2では、デフォルトのcore.yamlは、ピア間でゴシップの配布をするのではなく、オーダリングサービスからブロックを主録するように設定されています(プライベートデータは例外で、ゴシップを使用しているピアからピアに送信されます)。ordererからすべてのブロックを取得するには、 `core.yaml` ファイルで次のパラメータを使用する
```suggestion
ネットワークトラフィックを減らすために、Fabric v2.2では、デフォルトのcore.yamlは、ピア間でゴシップの配布をするのではなく、オーダリングサービスからブロックを取得するように設定されています(プライベートデータは例外で、ゴシップを使用しているピアからピアに送信されます)。ordererからすべてのブロックを取得するには、 `core.yaml` ファイルで次のパラメータを使用する必要があります。
```

2022-07-27 09:23 UTC, satomicchy commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +このトピックに進む前に、組織の [Deploying a Certificate Authority (CA)](https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/deployguide/ca-deploy-topology.html) のプロセスを確認して、組織の管理者とピアのアイデンティティとMSPを生成する必要があります
@shimos fabric-caプロジェクトのドキュメントのようですが、日本語版がどこにあるかわかりませんでした。トップページでいいのリンクを貼っていただけないでしょうか？

2022-07-27 14:19 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerplan.md
> +このトピックに進む前に、組織の [Deploying a Certificate Authority (CA)](https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/deployguide/ca-deploy-topology.html) のプロセスを確認して、組織の管理者とピアのアイデンティティとMSPを生成する必要があります
@satomicchy Fabric CAのドキュメントへのリンクであることを見落としていました。申し訳ありません。CAは日本語版がありませんし、1.4系が最新版ですので、元のままで問題ありません。

2022-07-27 14:36 UTC, satomicchy commented
@shimos レビューありがとうございました！修正しましたのでご確認よろしくお願いいたします。

2022-07-27 15:05 UTC, shimos approved these changes
修正ありがとうございました。LGTM

2022-07-27 15:05 UTC, merged