[ja_JP] Translate "cc_service.md" into Japanese
hyperledger/fabric-docs-i18n pull request #754
Opened 2022-08-02 05:35 UTC by yukiknd

This patch translates source/cc_service.md into Japanese.

Resolves #589

Signed-off-by: Yuki Kondo <yuki.kondo.ob@hitachi.com>

2022-08-03 15:42 UTC, shimos requested changes
@yukiknd 翻訳ありがとうございます。一点用語が統一されていないところがありましたので、修正をお願いいたします。

2022-08-03 15:42 UTC, shimos commented on docs/locale/ja_JP/source/cc_service.md
> +その代わりにチェーンコードのエンドポイントをピアにデプロイして、チェーンコードが動作していると、チェーンコードの定義をチャンネルにコミットしてチェーンコードを呼び出すという通常のプロセスを続けることができます。
```suggestion
その代わりにチェーンコードのエンドポイントをピアにデプロイして、チェーンコードが動作していると、チェーンコードの定義をチャネルにコミットしてチェーンコードを呼び出すという通常のプロセスを続けることができます。
```

2022-08-03 15:42 UTC, shimos commented on docs/locale/ja_JP/source/cc_service.md
> +新しい外部ビルダーとランチャーの機能は、ユーザーがオプションでビルドプロセスをカスタマイズすることができるようになりました。
```suggestion
新しい外部ビルダーとランチャーの機能によって、ユーザーがオプションでビルドプロセスをカスタマイズすることができるようになりました。
```

2022-08-04 00:32 UTC, yukiknd commented
@shimos レビューありがとうございます。指摘を反映したので、再レビューをお願いします。

2022-08-04 16:53 UTC, shimos approved these changes
@yukiknd 修正ありがとうございました。LGTM

2022-08-04 16:53 UTC, merged