[ja_JP] Translate "peerchecklist.md" into Japanese
hyperledger/fabric-docs-i18n pull request #755
Opened 2022-08-03 14:24 UTC by satomicchy

This patch translates "Deploying a production network >> Checklist for a production peer" into Japanese.

Resolves #598

Signed-off-by: Satomi Tsujita <satomi.t.sora@gmail.com>

2022-08-03 16:44 UTC, shimos requested changes
@satomicchy 翻訳ありがとうございました。いくつか文意を明確にするためにコメントしましたので、ご確認ください。

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +- **`chaincodeListenAddress`**: (デフォルト値を上書きする必要があります。) このパラメータのコメントアウトを外し、このピアがチェーンコード要求をリッスンするアドレスを指定します。`peer.listenAddress` とは異なる必要があります。例えば、 `0.0.0.0:7052` です。
```suggestion
- **`chaincodeListenAddress`**: (デフォルト値を上書きする必要があります。) このパラメータのコメントアウトを外し、このピアがチェーンコード要求をlistenするアドレスを指定します。`peer.listenAddress` とは異なる必要があります。例えば、 `0.0.0.0:7052` です。
```
listenについて前と表記ゆれがあるので、どちらかに統一したほうがよいでしょう。

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +- **`mspConfigPath`**: (デフォルト値を上書きする必要があります。) これはピアのローカルMSPへのパスであり、ピアをデプロイする前に作成する必要があります。パスは、 `FABRIC_CFG_PATH` に対する絶対パスでも相対パスでもかまいません(デフォルトでは、ピアイメージにある `/etc/hyperledger/fabric` です)。「msp」以外の名前が付けられ
```suggestion
- **`mspConfigPath`**: (デフォルト値を上書きする必要があります。) これはピアのローカルMSPへのパスであり、ピアをデプロイする前に作成する必要があります。パスは、絶対パスでも `FABRIC_CFG_PATH` に対する相対パスでもかまいません(デフォルトでは、ピアイメージにある `/etc/hyperledger/fabric` です)。「msp」以外の名前が付けられたフォルダへの絶対パスが指定されていない限り、ピアはデフォルトでそのパス(つまり `FABRIC_CFG_PATH/msp` )で「msp」という名前のフォルダを探し、ピアイメージを使用する場合は `/etc/hyperledger/fabric/msp` になります。[Registering and enrolling identities with a CA](https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/deployguide/use_CA.html) トピックで説明されている推奨フォルダ構造を使用している場合、FABRIC_CFG_PATHに対する相対パスは次のようになります。
```

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +  - **`pvtData.implicitCollectionDisseminationPolicy.requiredPeerCount`:** (プライベートデータの暗黙的コレクションを使用する場合は、この値を上書きすることをお勧めします。) **New in Fabric 2.0.** デフォルトは0ですが、組織に属するピアの数に基づいて増やす必要があります。この値は、トランザクションを
```suggestion
  - **`pvtData.implicitCollectionDisseminationPolicy.requiredPeerCount`:** (プライベートデータの暗黙的コレクションを使用する場合は、この値を上書きすることをお勧めします。) **New in Fabric 2.0.** デフォルトは0ですが、組織に属するピアの数に基づいて増やす必要があります。この値は、トランザクションをエンドースした後にピアがダウンした場合にデータの冗長性を確保するために、データを配布する必要がある自分の組織内のピアの数を表します。
```

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +ピアに対してTLSコミュニケーションを有効にするために、このセクションを設定します。TLSが有効になった後は、ピアと取り引きをする全てのノードも、TLSを有効にする必要があります。ピアのTLS許可を作成する方法の説明については、 [Registering and enrolling identities with a CA](https://hyperledger-fabric-ca.readt
```suggestion
ピアに対してTLSコミュニケーションを有効にするために、このセクションを設定します。TLSが有効になった後は、ピアとやりとりする全てのノードも、TLSを有効にする必要があります。ピアのTLS証明書を作成する方法の説明については、 [Registering and enrolling identities with a CA](https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/deployguide/use_CA.html) にあるトピックを参照してください。
```

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +- **`cert.file`:** (デフォルト値を上書きする必要があります。) すべてのピアは、組織内の他のノードと安全に取引する前に、TLS CAに登録してエンロールする必要があります。そのため、ピアをデプロイする前に、まずピアのユーザーを登録し、ピアのアイデンティティをTLS CAにエンロールして、ピアのTLS署名付き証明書を生成する必要があります。 [Registering and e
```suggestion
- **`cert.file`:** (デフォルト値を上書きする必要があります。) すべてのピアは、組織内の他のノードと安全にやりとりする前に、TLS CAに登録してエンロールする必要があります。そのため、ピアをデプロイする前に、まずピアのユーザーを登録し、ピアのアイデンティティをTLS CAにエンロールして、ピアのTLS署名付き証明書を生成する必要があります。 [Registering and enrolling identities with a CA](https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/deployguide/use_CA.html) トピックの推奨フォルダ構造を使用している場合は、このファイルを  `config/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls` にコピーする必要があります。
```

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +- **`clientAuthRequired`:** デフォルトは `false` です。 `true` に設定すると、 **mutual TLS** を使用してセキュリティレベルを高くすることができ、クライアント側のTLS証明書の追加の検証ステップとして設定できます。サーバー側のTLSが最低限必要なセキュリティレベルであると考えられる場合、相互TLSは追加で任意のセキュリティレベルです。
```suggestion
- **`clientAuthRequired`:** デフォルトは `false` です。 `true` に設定すると、 **相互TLS** を使用してセキュリティレベルを高くすることができ、クライアント側のTLS証明書の追加の検証ステップとして設定できます。サーバー側のTLSが最低限必要なセキュリティレベルであると考えられる場合、相互TLSは追加で任意のセキュリティレベルです。
```
前段と統一したほうがよいでしょう。

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +このセクションは、台帳のデータベースタイプ( `goleveldb` または `CouchDB` )を選択するために使用します。エラーを回避するには、すべてのピアが同じデータベース **type** を使用する必要があります。JSONクエリが必須である場合、CouchDBが適切です。CouchDBは別のオペレーティングシステムプロセスで実行されますが、ピアノードとCouchDBインスタンスの間に
```suggestion
このセクションは、台帳のデータベースタイプ( `goleveldb` または `CouchDB` )を選択するために使用します。エラーを回避するには、すべてのピアが同じデータベース **type** を使用する必要があります。JSONクエリが必須である場合、CouchDBが適切です。CouchDBは別のオペレーティングシステムプロセスで実行されますが、ピアノードとCouchDBインスタンスの間には依然として1:1の関係があります。つまり、各ピアは1つのデータベースを持ち、そのデータベースはそのピアにのみ関連付けられます。CouchDBの追加のJSONクエリケーパビリティ以外は、データベースの選択はスマートコントラクトには見えません。
```

2022-08-03 16:44 UTC, shimos commented on docs/locale/ja_JP/source/deploypeer/peerchecklist.md
> +2つのピアが同じノードで実行されている可能性が低い場合は、2番目のピアのアドレスを変更して別のポートを使用する必要があります。そうでない場合、2番目のピアを開始すると、開始に失敗し、アドレスがすでに使用中であることが報告されます。
```suggestion
あまりないことですが2つのピアが同じノードで実行されている場合は、2番目のピアのアドレスを変更して別のポートを使用する必要があります。そうでない場合、2番目のピアを開始すると、開始に失敗し、アドレスがすでに使用中であることが報告されます。
```

2022-08-04 13:39 UTC, satomicchy commented
@shimos レビューありがとうございます！修正しましたので、ご確認よろしくお願いいたします。

2022-08-04 16:54 UTC, shimos approved these changes
@satomicchy 修正ありがとうございました。LGTM!

2022-08-04 16:54 UTC, merged