Add full russian translation of Key Concepts, Operations Guides and Glossary
hyperledger/fabric-docs-i18n pull request #80
Opened 2020-08-16 20:49 UTC by SenchoPens

2020-08-16 21:09 UTC, C0rWin commented
Thanks for your contribution, but this is rather too large commit as includes way too many changes for someone to contain in the review. Please consider splitting this into smaller chunks. PR per topic.

2020-08-17 11:03 UTC, SenchoPens commented
> Thanks for your contribution, but this is rather too large commit as includes way too many changes for someone to contain in the review. Please consider splitting this into smaller chunks. PR per topic.

You mean one PR for Key Concepts, one for Operations Guides and one for Glossary?

2020-08-17 12:07 UTC, C0rWin commented
> You mean one PR for Key Concepts, one for Operations Guides and one for Glossary?

I mean, ideally, I would imaging having PR per topic, and pushed them separately, so it will be consumable currently it's nearly impossible to review PR with 746 files changed. This way it will be also easy to address review comments on your side.

2020-09-24 17:45 UTC, ryjones commented
Hi. I pulled out some of the changes to just the documentation and got this down to 36 files.

2020-09-24 18:54 UTC, ryjones commented
If you look in my repo: https://github.com/ryjones/fabric-docs-i18n/commit/aa336aa1563c2f891194088b43cae387585f8583 I have a copy of the `.rej` and `.orig` files from when I made the patch.

2020-09-24 23:07 UTC, C0rWin requested changes

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/blockchain.rst
> +Реестр блокчейна часто называют **децентрализованным**, поскольку он хранится всеми участниками сети, каждый из которых **участвует** в его поддержке. Чуть позже мы поймем, что децентрализация и колл
я думаю, что если уж заменять "коллаборирует", то и "коллаборация" стоит поменять, например на "взаимодействие".

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/blockchain.rst
> +Однако Hyperledger Fabric обладает **private permissioned-сетью**, что отличает его от многих других блокчейн-систем. В отличие от пользователей public permissionless-систем, которые позволяют неизве
Hyperledger Fabric не обладает **private permissioned-сетью**, Fabric по существу и является "permissioned blockchain" хотя в данном контексте я бы все таки использовал - "является приватной блокчейн сетью". Так же "public permissionless", в конексте перевода стоит поменять на публичная блокчейн сеть. 

> которые позволяют неизвестным участвовать в сети

которые предусматривают доступ неавторизорованным участникам

> (требуя протоколы вида “proof of work” для подтверждения транзакций и обеспечения безопасности сети)

это не верно, для обеспечения защита от атаки Сибилы чаще всего используют протоколы вида "proof of work", но никак не то что написанно в скобках, я предлагаю перефразировать.

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/blockchain.rst
> +Все смартконтракты Hyperledger Fabric написаны через **чейнкоды** и вызываются через внешнее приложение, когда ему требуется провзаимодействовать с реестром. В большинстве случаев, чейнкод взаимодейс
Концепция смартконтрактов в Hyperledger Fabirc реализованна с помощью абстракции **чейнкодов** которые вызываются через внешние приложения при необходимости взаимодействия с реестром.

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/blockchain.rst
> +Чейнкод может быть написан на нескольких языках программирования. В настоящее время поддерживаются Go и Node.js.
На данный момент поддерживается Go, Node.js и Java

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/capabilities_concept.md
> +Эта статья предназначается для администраторов каналов и администраторов узлов.
Эта статья предназначена....

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/capabilities_concept.md
> +*Обратите внимание: это продвинутая идея Fabric, новые в Fabric пользователи и разработчики могут ее пропустить.
> это продвинутая идея Fabric, новые в Fabric пользователи и разработчики могут ее пропустить.

понимание этой концепции является не обязательным для начинающих разработчиком и пользователей Hyperledger Fabric, однако с развитием знаний и пониманием настроек сети и конфигурации каналов Hyperledger Fabric понимание управления настройками возможностей становится жизненоважным.

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/capabilities_concept.md
> +Fabric это допускает, и именно это позволяет проводить rolling upgrades узлов (обновлять один узел, потом другой и т.д., без необходимости в одновременном обновлении всей системы).
> rolling upgrades

инкрементальные или постепенные обновления

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/capabilities_concept.md
> +Если пользователи не могут обновиться, то тогда их capabilities должны быть оставлены на низких уровнях.
> должны быть оставлены на низких уровнях.

должны быть сконигурированны в соответствии с версиями бинарных файлов.

2020-09-24 23:07 UTC, C0rWin commented on docs/locale/ru_RU/source/capabilities_concept.md
> +  Так как администраторы ордеринг-службы не контролируют транзакции в канале, изменение этого capability level подвластно только
> подвластно

доступно

2020-09-24 23:09 UTC, C0rWin commented
> Hi. I pulled out some of the changes to just the documentation and got this down to 36 files.

I still think that more fine grained PRs will make this work more consumable.

2021-03-05 20:34 UTC, merged