Newtranslation for Bahasa Indonesia
hyperledger/fabric-docs-i18n pull request #800
Opened 2023-05-31 13:50 UTC by nikofebrianur

This is my first pull request for Bahasa Indonesia Translation.

2023-05-31 14:19 UTC, ryjones commented
Hi, @nikofebrianur . Please follow these [instructions to fix the DCO issue](https://github.com/hyperledger/fabric-docs-i18n/pull/800/checks?check_run_id=13894458078)

2023-05-31 14:20 UTC, ryjones requested changes
Hi, @nikofebrianur . Please follow these [instructions to fix the DCO issue](https://github.com/hyperledger/fabric-docs-i18n/pull/800/checks?check_run_id=13894458078)

2023-05-31 14:22 UTC, ryjones commented on README.md
> +# Fabric Docs id_ID
Please don't change this file; change the one in docs/locale/id_ID

2023-05-31 14:25 UTC, ryjones commented
You'll also want to be in docs/locale/id_ID, not id_ID/pt_BR. You might start from 2.5, not 2.2

2023-06-01 00:13 UTC, nikofebrianur commented
Hi Ry,

Thanks for your advice, this is my first time to contribute and practice
Git. I am following the docs that say to start from the LTS version. I will
do my best to fix this. Thanks in advance, Ry.
[image: image.png]

On Wed, May 31, 2023 at 10:25 PM Ry Jones ***@***.***> wrote:

> You'll also want to be in docs/locale/id_ID, not id_ID/pt_BR. You might
> start from 2.5, not 2.2
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperledger/fabric-docs-i18n/pull/800#issuecomment-1570343251>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKC2VA5NQQYHPEBEREYQP6TXI5IGVANCNFSM6AAAAAAYVQAN7Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-01 12:45 UTC, ryjones approved these changes

2023-06-01 12:45 UTC, merged

2023-06-01 12:46 UTC, ryjones commented
Thank you for contributing!

2023-06-01 12:56 UTC, ryjones commented
@nikofebrianur I don't see any content differences - here is the page: https://fabric-docs-id-id.readthedocs.io/id/release-2.5/