[ja_JP] Translate policies.md into Japanese
hyperledger/fabric-docs-i18n pull request #84
Opened 2020-08-19 19:59 UTC by satota2

This PR translates `policies.md` into Japanese.

Resolves #82

2020-08-20 09:23 UTC, Naoya-Horiguchi requested changes
お疲れさまです。全体的に原文が悪文なので訳が難しいところが多い印象でした。

> 以下は本ページに関してどう訳せばよいか悩ましかった単語です ( ->の先が一旦使った訳語です)
> - MSP principals -> MSPプリンシパル
> - organization unit (OU) -> 組織単位 (OU)

私はこの訳で良いと思います。

以下細かいコメントをさせていただきましたので、ご確認の上適宜アップデートをお願いします。

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +例えば、インシュアランス・ポリシー (保険契約) は、保険の支払いがされる内容条件、制限事項、および有効期限を定義します。
```suggestion
例えば、インシュアランス・ポリシー (保険契約) は、保険の支払いがされる内容条件、期間、制限事項、および有効期限を定義します。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +システムチャネル設定と各アプリケーションチャネル設定の一部により、Orderer組織は、
```suggestion
システムチャネル設定と各アプリケーションチャネル設定の一部により、オーダリング組織は、
```
L62 は「オーダリング組織」と記載していますのでそちらに合わせるのがよいでしょう。

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +また、システムチャネルはコンソーシアムのどのメンバーが新しいチャネルを生成できるかどうかも管理します。
```suggestion
また、システムチャネルはコンソーシアムのどのメンバーが新しいチャネルを生成できるかも管理します。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +そのチェーンコードを承認する必要がある組織を管理します。
```suggestion
そのチェーンコードをどの組織が承認する必要があるかも管理します。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +ネットワーク管理者はACLを用いたFabricの仕様に特に関心があるでしょう。
```suggestion
ネットワーク管理者はFabricのACLの使用に特に関心があるでしょう。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +その他のリソース (例えば、誰がBlockイベントを受信できるか) である可能性があります。
```suggestion
その他のリソース (例えば、誰がブロックイベントを受信できるか) である可能性があります。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +# Chaincode to chaincodeを実行するためのACLポリシー
```suggestion
# チェーンコード間呼び出しのためのACLポリシー
```
これは訳が難しいですね。私としては「チェーンコード間呼び出し」あたりがしっくりきますが、意味が変わって聞こえるようなら「chaincode to chaincode呼び出し」などが良いのかもしれません。

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +オーダリングサービスのノードによって使われるコンセンサスメカニズムを制御できます。
```suggestion
オーダリングサービスのノードによって使われる合意形成機構を制御できます。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +Fabricのポリシーは柔軟であり、ネットワークのニーズに併せて設定することができる一方、
```suggestion
Fabricのポリシーは柔軟であり、ネットワークのニーズに合わせて設定することができる一方、
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +次の図では、デフォルトポリシーが以下のFabricポリシードメインの制御を実装する方法を示しています。
```suggestion
次の図では、デフォルトポリシーがどのように下層のFabricポリシードメインに対する制御を実装しているかを示しています。
```
??

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +独自のビジネスロジックを管理し、ネットワーク上に配置されるデータへのアクセス制限を可能とします。
```suggestion
その組織のビジネスロジックを管理し、ネットワーク上に配置されるデータにアクセス制限できるようにします。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +個別メンバーからの明示的な (署名) 承認、あるいはグループからの暗黙的な (署名) 承認のいずれかによって、
この段落全般的に sign を「承認」としていますが、その必要はあるのでしょうか? L116 で「署名 (承認)」で両者が同一であると確認しているので、ここは原文どおり「署名」で問題ないような気がしました。

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> + **誰** がそれを承認する必要があるかを記述されています。
```suggestion
 **誰** がそれを承認する必要があるかを記述しています。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +保険ドメインでは、明示的な承認は、住宅オーナー保険代理店グループのメンバーオーダリング人とすることができます。
```suggestion
保険ドメインでは、明示的な承認は、住宅オーナー保険代理店グループのメンバーの一人がありえます。
```
この文は explicit sign off の指定方法の例を挙げているようですが、訳しにくいですね。

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +そして、暗黙的な承認は、住宅オーナー保険グループの管理メンバーの過半数の承認を必要とすることに炊事しています。
```suggestion
そして、暗黙的な承認は、住宅オーナー保険グループの管理メンバーの過半数の承認を必要とすることに類似しています。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +そのグループのメンバーは、ポリシーを更新することなく、時間の経過とともに変化する可能性があるため、
```suggestion
ポリシーを更新する必要なしに、そのグループのメンバーを時間の経過とともに変更できるため、
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +Hyperledger Fabricでは、明示的な承認のために、 `Signature` シンタックスが、暗黙的な承認のために、
```suggestion
Hyperledger Fabricでは、明示的な承認のためには `Signature` シンタックスが、暗黙的な承認のためには
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +つまり、 `ImplicitMeta` ポリシーは、コンソーシアムのメンバーが変わったときにも、より柔軟であると考えられます。
```suggestion
従って、 `ImplicitMeta` ポリシーは、コンソーシアムのメンバーが変わったときにも、より柔軟であると考えられます。
```

2020-08-20 09:23 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
>  defined in the channel configuration or by explicitly specifying a Signature policy.
この段落、原文を削除し忘れているようです。

2020-08-20 09:23 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/policies/policies.md
> +ユーザーをCAを用いてエンロールすると、ロールがIDに関連付けられます。
```suggestion
ユーザーをCAを用いてエンロールすると、ロールがアイデンティティに関連付けられます。
```

2020-08-20 23:19 UTC, satota2 commented on docs/locale/ja_JP/source/policies/policies.md
> +# Chaincode to chaincodeを実行するためのACLポリシー
ありがとうございます。おっしゃる通り、チェーンコード間呼び出しがわかりやすいですね。

2020-08-20 23:29 UTC, satota2 commented on docs/locale/ja_JP/source/policies/policies.md
> +個別メンバーからの明示的な (署名) 承認、あるいはグループからの暗黙的な (署名) 承認のいずれかによって、
ご指摘ありがとうございます。あたらめて見返すとくどいですね。原文の通り、署名のみに直したいと思います。

2020-08-20 23:30 UTC, satota2 commented on docs/locale/ja_JP/source/policies/policies.md
> +保険ドメインでは、明示的な承認は、住宅オーナー保険代理店グループのメンバーオーダリング人とすることができます。
すみません。そもそも日本語がおかしなことになってました。。

2020-08-20 23:33 UTC, satota2 commented on docs/locale/ja_JP/source/policies/policies.md
>  defined in the channel configuration or by explicitly specifying a Signature policy.
ご指摘ありがとうございます。削除いたします。

2020-08-20 23:59 UTC, satota2 commented
@Naoya-Horiguchi レビューありがとうございます。
ご指摘頂いた点を更新のうえ、パッチを再投稿いたしました。
ご確認よろしくお願いします。

2020-08-21 05:08 UTC, nhoriguchi reviewed
すみません、あと一点だけビルド時の warning がありました。

2020-08-21 05:08 UTC, nhoriguchi commented on docs/locale/ja_JP/source/policies/policies.md
> + **誰** がそれを承認する必要があるかを記述しています。
ビルドすると WARNING: unexpected indentation が出てしまいますね。
```suggestion
**誰** がそれを承認する必要があるかを記述しています。
```

2020-08-24 18:02 UTC, satota2 commented on docs/locale/ja_JP/source/policies/policies.md
> + **誰** がそれを承認する必要があるかを記述しています。
@Naoya-Horiguchi 
ご指摘ありがとうございます。修正反映いたしました。
私の手元でビルドしてみたのですが、こちらのWARNINGが出てきませんでした(sphinxのバージョンはPipfileとrequirements.txtに記載の1.7.2か1.8.5をそれぞれ試しました)。もしかしたら、利用しているsphinxのバージョンの違いによるものかもしれません。
もし別バージョンをご利用のようでしたら、本家に合わせて1.8.5をご利用いただいたほうがよいかもしれません。

補足: 本家のほうで利用中のsphinxのバージョンが揺れていましたが、これを機にパッチを投げて1.8.5に統一しました。

2020-08-24 18:09 UTC, satota2 commented
@Naoya-Horiguchi レビューありがとうございます。
パッチを再投稿いたしました。ご確認よろしくお願いします。

2020-08-24 22:19 UTC, Naoya-Horiguchi commented on docs/locale/ja_JP/source/policies/policies.md
> + **誰** がそれを承認する必要があるかを記述しています。
すみません。私の方でもコメントしてから気づいたのですが、公式のビルド手段のとおり (`pipenv shell` 内で) ビルドするとこの warning は発生しませんでした。私のビルド方法に問題があったようです。

Wiki のチェックリストも更新しておいたのですが、強調など文字装飾の前後に全角文字が隣接する時に空白が必要というのは rst のときの話で、markdown の場合空白なしでも問題なくレンダリングされるので、その意味で空白が不要とコメントすべきでした。

2020-08-24 22:20 UTC, Naoya-Horiguchi approved these changes
ありがとうございました。

2020-08-24 22:23 UTC, merged

2020-08-24 23:51 UTC, satota2 commented on docs/locale/ja_JP/source/policies/policies.md
> + **誰** がそれを承認する必要があるかを記述しています。
@Naoya-Horiguchi 
ご確認ありがとうございます。

> markdown の場合空白なしでも問題なくレンダリングされるので、その意味で空白が不要とコメントすべきでした。
ご教示いただきありがとうございます。次のパッチからはこちらも確認するようにいたします。