[ja_JP] Architecture Reference / Fabric Gateway
hyperledger/fabric-docs-i18n pull request #952
Opened 2024-11-29 00:51 UTC by satoshi-ito-ht

This patch translates source/gateway.md into Japanese. 
Resolves #907

2024-11-29 09:59 UTC, satota2 requested changes
@satoshi-ito-ht 翻訳ありがとうございます。修正案をコメントしましたのでお手数ですがご確認と対応をお願いします。

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +- **チェーンコードエンドースメントポリシー。** これは、組織のチェーンコード定義を承認する際にチャネルメンバーが合意するポリシーです。
```suggestion
- **チェーンコードエンドースメントポリシー** これは、組織のチェーンコード定義を承認する際にチャネルメンバーが合意するポリシーです。
```
ここでのピリオドは句点としてではなく、見出しの区切りとして利用されているものと思います。
同件の見直しもお願いします。

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +これまでクライアントSDKに求められていた複数組織のピアからトランザクションのエンドースメントを収集するなどの作業が、ピア内で実行されるFabric Gatewayサービスに委任され、v2.4ではアプリケーション開発とトランザクション送信がシンプルになりました。
```suggestion
これまでクライアントSDKに求められていた複数組織のピアからトランザクションのエンドースメントを収集するなどの作業が、ピア内で実行されるFabric Gatewayサービスに委譲され、v2.4ではアプリケーション開発とトランザクション送信がシンプルになりました。
```
IT分野ではDelegateは委任よりも委譲と訳すのがより一般的と思いますがいかがでしょうか。

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +この読み取り/書き込みセットには、現在の台帳の状態とその関数内の状態のget/set指示に応じた変更が含まれています。
```suggestion
この読み取り/書き込みセットには、現在の台帳のステートとその関数内のステートのget/set指示に応じた変更が含まれています。
```

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +これは通常、台帳の現在の状態をクエリする際に使用され、台帳の更新は行われません。
```suggestion
これは通常、台帳の現在のステートをクエリする際に使用され、台帳の更新は行われません。
```

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +このシミュレーションでは、アクセスされた状態に関する情報が取得され、それに基づいてエンドースメントポリシーが組み合わせられます (エンドースメントピアの台帳に保存された個々のState-baseエンドースメントポリシーを含みます) 。
```suggestion
このシミュレーションでは、アクセスされたステートに関する情報が取得され、それに基づいてエンドースメントポリシーが組み合わせられます (エンドースメントピアの台帳に保存された個々のState-baseエンドースメントポリシーを含みます) 。
```

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +ゲートウェイのエンドースメントプロセスは、トランザクション提案内の一時データとして渡されるプライベートデータに機密情報や個人情報が含まれることが多く、それらをすべての組織のピアに渡すべきではないため制限的です。
```suggestion
ゲートウェイのエンドースメントプロセスは、トランザクション提案内の一時データ (Transient data) として渡されるプライベートデータに機密情報や個人情報が含まれることが多く、それらをすべての組織のピアに渡すべきではないため制限的です。
```
初出なので英語名も併記したほうがより親切と思いました。

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +一時的なデータに対するこの制限がエンドースメントポリシーを満たさない場合、ゲートウェイはプライベートデータへのアクセス権がない組織に対して転送するのではなく、クライアントにエラーを返します。
```suggestion
一時データに対するこの制限がエンドースメントポリシーを満たさない場合、ゲートウェイはプライベートデータへのアクセス権がない組織に対して転送するのではなく、クライアントにエラーを返します。
```

表記揺れです。

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +例えば、一時的なデータは個人情報や機密情報が含まれることが多く、それらのデータはプライベートデータコレクションにのみ書き込むべきであり、エンドースメント組織の数を制限する必要があります。
```suggestion
例えば、一時データは個人情報や機密情報が含まれることが多く、それらのデータはプライベートデータコレクションにのみ書き込むべきであり、エンドースメント組織の数を制限する必要があります。
```

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +組織が複数のピアやオーダリングノードを実行している場合は、別の適格なノードで施行されます。
```suggestion
もしある組織が複数のピアやオーダリングノードを動かしている場合には、別の適格なノードが試されます。
```
より自然な文章に修正してみました。

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +組織がトランザクション提案のエンドースに失敗した場合、別の組織が選択されます。
```suggestion
ある組織がトランザクション提案のエンドースに失敗した場合、別の組織が選択されます。
```

2024-11-29 09:59 UTC, satota2 commented on docs/locale/ja_JP/source/gateway.md
> +エンドースメントポリシーを満たす利用可能なピアの組み合わせがない場合にのみゲートウェイは再試行を停止します。
```suggestion
エンドースメントポリシーを満たす利用可能なピアの組み合わせがない場合にのみゲートウェイはリトライを停止します。
```
Retryは再試行はリトライという日本語表記のほうがより一般的に利用されている印象ですがいかがでしょうか。
検討と同件の見直しをお願いします。

2024-12-04 08:34 UTC, satoshi-ito-ht commented
@satota2  ご確認いただきありがとうございます。頂いた修正案を元に反映いたしました。ご確認いただけますと幸いです。

2024-12-05 10:12 UTC, satota2 approved these changes
@satoshi-ito-ht Updateありがとうございます。LGTM！

2024-12-05 10:13 UTC, merged