[ja_JP] Translate "Introduction"
hyperledger/fabric-docs-i18n pull request #96
Opened 2020-08-20 16:48 UTC by shimos

This patch translates "Introduction" (whatis.md) into Japanese.

Resolves #81

2020-08-22 03:06 UTC, nhoriguchi requested changes
作業ありがとうございます。いくつかコメントさせていただきました。

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +暗号資産である[Bitcoin](https://en.wikipedia.org/wiki/Bitcoin) です。
```suggestion
暗号資産 (暗号通貨) である[Bitcoin](https://en.wikipedia.org/wiki/Bitcoin) です。
```
ウェブ検索すると「暗号資産」「暗号通貨」「仮想通貨」と混同して用いられているので、どちらでもよいのだと思いますが原文を尊重して最初だけ併記するというのはいかがでしょう。

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +他の例もこれの後を継いでいますが、暗号資産のEthereumは、新しく _スマートコントラクト_ と
```suggestion
他の例もこれの後を継いでいますが、暗号資産のEthereumは異なるアプローチを取っており、新しく _スマートコントラクト_ と
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +分散台帳、分散アプリケーションプラットフォームの技術を _エンタープライズ_ 向けに適用しようという動きもでてきました。
```suggestion
分散台帳、分散アプリケーションプラットフォームの技術を、より革新的な_エンタープライズ_ 向けのユースケースに適用しようという動きもでてきました。
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +しかし、多くのエンタープライズ向けのユースケースでは、(今のところ)満たすことが不可能な性能が要件になっています。
```suggestion
しかし、多くのエンタープライズ向けのユースケースでは、(今のところ)満たすことが不可能な性能特性が要件になっています。
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +初期のブロックチェーンプラットフォームが、エンタープライズ向けには _それに適応するように変更_ されているのに対し、
```suggestion
初期のブロックチェーンプラットフォームの多くが、現在エンタープライズ向けに _適応するように変更_ されているところである一方、
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +ビザンチン故障耐性のある合意形成アルゴリズムは不要でしょうし、性能やスループットを必要以上に損なうことになるでしょう。
```suggestion
完全なビザンチン故障耐性を持つ合意形成アルゴリズムは不要で、性能やスループットを必要以上に損なうとみなされるかもしれません。
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +Fabricは、暗号資産を必要としない合意形成プロトコルを利用することができます。
```suggestion
Fabricは、**内蔵の暗号資産を必要としない**合意形成プロトコルを利用することができます。
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +今日利用できる高い性能のプラットフォームの一つであり、トランザクションとスマートコントラクト(Fabricではチェーンコードと呼びます)
```suggestion
今日利用できる**高い性能のプラットフォーム**の一つであり、トランザクションとスマートコントラクト(Fabricではチェーンコードと呼びます)
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +の実装によってプライバシーと機密性を実現することができます。
```suggestion
の実装によって**プライバシーと機密性**を実現することができます。
```

2020-08-22 03:06 UTC, nhoriguchi commented on docs/locale/ja_JP/source/whatis.md
> +そのため、チャネルに参加しているノードだけがスマートコントラクトとトランザクションのデータにアクセスすることができるため、
```suggestion
そのため、チャネルに参加しているノードだけがスマートコントラクト (チェーンコード) とトランザクションのデータにアクセスすることができるため、
```

2020-08-24 19:05 UTC, shimos commented
レビューありがとうございます。反映いたしました。

なお、
- "native cryptocurrency"は、ネイティブと訳す方が事例が多そうでしたので、「ネイティブな～」としました。

2020-08-24 22:27 UTC, Naoya-Horiguchi approved these changes
確認しました。どうもありがとうございました。

2020-08-24 22:34 UTC, merged